### ISSUE TITLE
Having trouble running Jest, unhandled Promises

### ISSUE THREAD

**Issue by ncrmro** [Vincit/objection.js#1015]
Awesome project!

Have a database class that has public connect and close methods. Which Jest uses before and afterAll to cleanly connect and disconnect during tests.

Looks like Objection might still be running. Screen shot of code below. Any ideas on how to close this. Log shows 

```
Jest has detected the following 3 open handles potentially keeping Jest from exiting:

  ●  PROMISE

          at Function.resolve (<anonymous>)
      at Object.<anonymous> (node_modules/lodash/_getTag.js:37:32)
      at Object.<anonymous> (node_modules/lodash/_baseIsEqualDeep.js:5:14)


  ●  PROMISE

      at Object.getNativePromise (node_modules/bluebird/js/release/util.js:324:27)
      at Object.<anonymous> (node_modules/bluebird/js/release/schedule.js:7:26)
      at Object.<anonymous> (node_modules/bluebird/js/release/async.js:4:16)


  ●  PROMISE

          at Function.resolve (<anonymous>)
      at Object.<anonymous> (node_modules/objection/lib/utils/clone.js:1569:32)
      at Object.<anonymous> (node_modules/objection/lib/utils/clone.js:2303:3)
      at Object.<anonymous> (node_modules/objection/lib/utils/objectUtils.js:1:57)

```

![dbjest](https://user-images.githubusercontent.com/8276365/43263958-60129f96-90aa-11e8-93c8-cb4da6b4d358.jpeg)

Code base can be found [here](https://gitlab.com/ncrmro/prion/tree/4-docker-images-2)

Thanks again for the awesome tool

**Comment by koskimas** [comment]
Objection doesn't hold on to any promises of run anything in the background. The problem is somewhere I'm afraid.

**Comment by koskimas** [comment]
Are you creating multiple instances of the `Database` class simultaneously? You set the connection in each of them globally using `Model.knex`. Only the last one will be used in all of them.

**Comment by ncrmro** [comment]
@koskimas I am not creating multiple instances, atm it should just be a single sqlite memory instance.

**Comment by heisian** [comment]
@ncrmro You can't just call `this.knex.destroy()`. It has a callback function, and needs to be promisified first:
```node
const { promisify } = require('util')
const disconnect = promisify(this.knex.destroy)

(async() => {
  await this.knex.destroy()
})()
```

**Comment by heisian** [comment]
or, as I do in my jest suites:
```
await promisify(this.knex.destroy)()
```

**Comment by ncrmro** [comment]
@heisian this is very insightful been learning more and more about how async and promises work each day. Will let you guys know when/if resolved.

**Comment by ncrmro** [comment]
@heisian tried 

`await promisify(this.knex.destroy)()`

No luck, do you have any example somewhere with knex, objection and jest working?

Maybe at least versions and snippits? Thinking maybe it's sqlite. I've t ried various combos of async/await and without. this.knex.destroy(cb) never fires the callback either. if I console.log(this.knex) it pops up. Might need to move to knex and reference issue here.

**Comment by ncrmro** [comment]
I do see somethings coming out of objection though?

```
          at Function.resolve (<anonymous>)
      at Object.<anonymous> (node_modules/objection/lib/utils/clone.js:1569:32)
      at Object.<anonymous> (node_modules/objection/lib/utils/clone.js:2303:3)
      at Object.<anonymous> (node_modules/objection/lib/utils/objectUtils.js:1:57)

```

**Comment by ncrmro** [comment]
Seeing this #534

**Comment by ncrmro** [comment]
https://github.com/cynicaloptimist/improved-initiative/issues/250

**Comment by ncrmro** [comment]
Looks like bad timing apologies..

Stiill wonder about that lingering objection promise but we shall see.
https://github.com/facebook/jest/pull/6716

**Comment by excalios** [comment]
Hello,
Just curious on why this is happening? It's also with jest it only happens when objection is there. As [ncrmro](https://github.com/Vincit/objection.js/issues/1015#issuecomment-408257409) said #534 we need to explicitly close the connection. So on each test files I need to add an afterAll() function to close the connection. I don't really like this solution It's very repetitive on each file and jest globalTeardown doesn't work either.
![image](https://user-images.githubusercontent.com/42968441/146536743-43670dd9-48b3-4dae-98c3-70a5d73abac5.png)
