### ISSUE TITLE
Timestamps recipe not working

### ISSUE THREAD

**Issue by rivertam** [Vincit/objection.js#1042]
Hey there.

I'm trying to follow the timestamps recipe using MySQL. My model base looks like this:

```js
import uuid from 'uuid/v4';
import { Model } from 'objection';
import knex from './knex';

Model.knex(knex);

export default class extends Model {
  constructor(...args) {
    super(...args);
  }

  $beforeInsert() {
    this.createdAt = new Date().toISOString();
    if (this.constructor.jsonSchema.properties.id) {
      this.id = uuid();
    }
  }

  $beforeUpdate() {
    this.updatedAt = new Date().toISOString();
  }
}
```

This has actually worked for months locally on MySQL 5.6.

However, on MySQL 5.7 in Google Cloud Platform (I can't test this locally for various reasons, unfortunately), I'm getting the following error messages (I have `DEBUG=knex*` on, so I've included the query as well) (I've also changed some names and stuff for IP reasons, but I see no reason it should be impacting this)

```
2018-08-16T20:13:52.574Z knex:query insert into `users` (`created_at`) values (?) undefined
2018-08-16T20:13:52.575Z knex:bindings [ '2018-08-16T20:13:52.314Z' ] undefined
2018-08-16T20:13:53.071Z knex:client releasing connection to pool: __knexUid1
Internal server error { id: 'client:220ef105-8dce-4822-94df-9d71dcb01ae3',
  type: 'users.create' } { Error: Incorrect datetime value: '2018-08-16T20:13:52.314Z' for column 'created_at' at row
1
    at Packet.asError (/usr/src/app/node_modules/mysql2/lib/packets/packet.js:714:13)
    at Query.Command.execute (/usr/src/app/node_modules/mysql2/lib/commands/command.js:28:22)
    at Connection.handlePacket (/usr/src/app/node_modules/mysql2/lib/connection.js:513:28)
    at PacketParser.onPacket (/usr/src/app/node_modules/mysql2/lib/connection.js:81:16)
    at PacketParser.executeStart (/usr/src/app/node_modules/mysql2/lib/packet_parser.js:76:14)
    at Socket.<anonymous> (/usr/src/app/node_modules/mysql2/lib/connection.js:89:29)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:639:20)
  code: 'ER_TRUNCATED_WRONG_VALUE',
  errno: 1292,
  sqlState: '22007',
  sqlMessage:
   'Incorrect datetime value: \'2018-08-16T20:13:52.314Z\' for column \'created_at\' at row 1' }
```

Any ideas? Or should I be asking in knex?

**Comment by rivertam** [comment]
Given [this StackOverflow post](https://stackoverflow.com/questions/11053941/mysql-insert-to-datetime-is-it-safe-to-use-iso8601-format), it looks like this was actually never a good idea, but it's turned into an error in 5.7. I'm researching alternatives.

**Comment by rivertam** [comment]
I'm having issues at least in part due to the fact that I don't know how I can validate these dates.

My current idea is:

```js
function formatDate(date = new Date()) {
  if (!date) {
    return date;
  }

  return date.toISOString().slice(0, 19)
    .replace('T', ' ');
}
```

as I got that from a StackOverflow post. I don't like how brittle it seems, especially considering it just chops off the time zone information, but it at least mostly works.

I was previously using `{ type: 'string', format: 'date-time' }`, but this no longer works (presumably because I changed the format).

Ideally, I could just use UNIX timestamps everywhere as I consider them the least brittle and easiest to validate, but I don't know if that's possible on a practical level.

**Comment by rivertam** [comment]
I'm still using the `formatDate` as described in the previous comment, and I changed the spec for these fields to:

```js
  { type: 'string', pattern: '^[0-9]+-[0-9][0-9]-[0-9][0-9] [0-9][0-9]:[0-9][0-9]:[0-9][0-9]$' }
```

(yes, I could use `\\d` I think but it was even uglier imo. also this allows me to put in slightly better validation for months and stuff if I ever care enough to do so)

so far this seems to be working, but I don't have tests for my application, so it could have broken other stuff.
