### ISSUE TITLE
error: invalid input syntax for type uuid: "uuid_generate_v4()"

### ISSUE THREAD

**Issue by oipewr** [Vincit/objection.js#1198]
objection.js version: 1.4.0
pg version: 7.8.0
knex version: 0.16.3

```js
// migrations/20190118210104_create_users.js

exports.up = knex => {
  return knex.schema.createTable("users", table => {
    table
      .uuid("id")
      .primary()
      .defaultTo(knex.raw("uuid_generate_v4()"));
    table.string("email").notNullable();
    table.string("hashedPassword").notNullable();
    table.json("profile");
    table.json("address");
    table.string("facebookId");
    table.specificType("tokens", "json[]");
    table.bigInteger("createdAt").notNullable();
    table.bigInteger("updatedAt").notNullable();
  });
};
```

```shell
[2] migration file "20190118210104_create_users.js" failed
[2] migration failed with error: create table "users" ("id" uuid default 'uuid_generate_v4()', "email" varchar(255) not null, "hashedPassword" varchar(255) not null, "profile" json, "address" json, "facebookId" varchar(255), "tokens" json[], "createdAt" bigint not null, "updatedAt" bigint not null) - invalid input syntax for type uuid: "uuid_generate_v4()"
[2] { error: invalid input syntax for type uuid: "uuid_generate_v4()"
[2]     at Connection.parseE (/home/user/Workspace/again_obj/node_modules/pg/lib/connection.js:555:11)
[2]     at Connection.parseMessage (/home/user/Workspace/again_obj/node_modules/pg/lib/connection.js:380:19)
[2]     at Socket.<anonymous> (/home/user/Workspace/again_obj/node_modules/pg/lib/connection.js:120:22)
[2]     at Socket.emit (events.js:182:13)
[2]     at addChunk (_stream_readable.js:283:12)
[2]     at readableAddChunk (_stream_readable.js:264:11)
[2]     at Socket.Readable.push (_stream_readable.js:219:10)
[2]     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
[2]   name: 'error',
[2]   length: 113,
[2]   severity: 'ERROR',
[2]   code: '22P02',
[2]   detail: undefined,
[2]   hint: undefined,
[2]   position: undefined,
[2]   internalPosition: undefined,
[2]   internalQuery: undefined,
[2]   where: undefined,
[2]   schema: undefined,
[2]   table: undefined,
[2]   column: undefined,
[2]   dataType: undefined,
[2]   constraint: undefined,
[2]   file: 'uuid.c',
[2]   line: '137',
[2]   routine: 'string_to_uuid' }
[2] [nodemon] app crashed - waiting for file changes before starting...
```

Please help.

**Comment by koskimas** [comment]
Please use words

**Comment by koskimas** [comment]
This is not related to objection. It seems the the SQL that gets generated is invalid. Maybe `uuid_generate_v4() returns a string?

**Comment by koskimas** [comment]
Maybe this helps? https://github.com/tgriesser/knex/issues/2722

**Comment by oipewr** [comment]
Could you please let me know how to use `uuid`? I read and copied from here: https://github.com/tgriesser/knex/issues/1185 and the one you commented. But still doesn't work. That's why I ended here.

**Comment by koskimas** [comment]
Maybe you could use `gen_random_uuid()` function instead? https://www.postgresql.org/docs/current/pgcrypto.html#id-1.11.7.34.9

**Comment by oipewr** [comment]
Just tried, still got error. 

```js
    table
      .uuid("id")
      .primary()
      .defaultTo(knex.raw("gen_random_uuid()"));
```

```shell
error: function gen_random_uuid() does not exist
```

**Comment by koskimas** [comment]
Should I continue to copy paste links and suggestions for you from google or could you copy paste the error to google yourself and read the results?

**Comment by koskimas** [comment]
I'll give you one last hint: `gen_random_uuid()` is obviously a function in postgres because it's in the documentation. Maybe you should find out why it's not found in your setup? Maybe your postgresql is too old? Maybe you need to load some extension?

**Comment by oipewr** [comment]
Do you think I'm just sitting here without doing anything and wait for your reply? I did google multiple times before I came here and still doing it. The only reason I wrote the last comment is that I just wanted to update and to keep track of the issue until found the solution. If you see it as unnecessary, I'm sorry about that. However, thanks.

**Comment by kibertoad** [comment]
@oipewr That was uncalled for. It's generally not a good idea to be passive-aggressive (or active-aggressive for that matter) towards people who contribute their time and effort without expecting anything in return.

Have you tried calling function directly via DB client not using Node.js at all? If it doesn't work there, not going to work via .raw() either.

**Comment by elhigu** [comment]
From the first error message it seems that knex’s default to might have bug that it is treating knex.raw output as string literal... as @kibertoad said try to figure out first what kind of plain sql you need and then it should be easy to help how to generate that kind of sql.

**Comment by oipewr** [comment]
@kibertoad Thanks for reminding me.

Also it's generally not a good idea to judge, talk like they own us and be passive-aggressive (or active-aggressive for that matter) towards users. 

Objection is a nice project. Thanks for your contributions. This is a lesson for me, next time I will write a fully comprehensive paragraph of how long I have googled and how many times I had to think about not to bother these godly maintainers before describing the problem.

**Comment by oipewr** [comment]
Thanks @elhigu I will try.

**Comment by koskimas** [comment]
@oipewr Yeah I admit that my comments were a little passive aggressive too. It's just that after the first comment, where I said this is not related to objection, I wasn't answering to you as an objection maintainer anymore. I was just a random guy in the internet helping you in your coding problem.
