### ISSUE TITLE
targetValue.replace is not a function

### ISSUE THREAD

**Issue by juanlu91** [Vincit/objection.js#1207]
Hi,
I'm getting the following error when I try to use `insertGraphAndFetch` method:
```
2019-01-25T23:40:17.293Z	d214e79c-2791-45b5-bb0a-fb1a1deb936c	TypeError: targetValue.replace is not a function
at GraphInsertAction._resolvePropertyReferenceNode (/var/task/node_modules/objection/lib/queryBuilder/graph/insert/GraphInsertAction.js:127:54)
at GraphInsertAction._resolveDependency (/var/task/node_modules/objection/lib/queryBuilder/graph/insert/GraphInsertAction.js:82:12)
at GraphInsertAction._resolveDependencies (/var/task/node_modules/objection/lib/queryBuilder/graph/insert/GraphInsertAction.js:72:16)
at GraphInsertAction._beforeInsert (/var/task/node_modules/objection/lib/queryBuilder/graph/insert/GraphInsertAction.js:56:10)
...
```
My code is such as this example from the doc, but using `insertGraphAndFetch` instead of `insertGraph`:
```javascript 
let result = await Person
  .query()
  .insertGraphAndFetch([{
    "#id": 'jenniLaw',
    firstName: 'Jennifer',
    lastName: 'Lawrence',
    pets: [{
      name: "I am the dog of #ref{jenniLaw.firstName} whose id is #ref{jenniLaw.id}",
      species: 'dog'
    }]
  }]);
```
It has been working fine until the last updates. Maybe I've missed any breaking changes?
Thanks!

**Comment by koskimas** [comment]
I tried that code and it works. There are no breaking changes.
