### ISSUE TITLE
WhereExists with related Query fails with `Cannot read property 'columns' of null`

### ISSUE THREAD

**Issue by lopezvit** [Vincit/objection.js#1266]
I'm having this query:

```
    totalNumber = await FormItemResponseOptionsValues.query()
      .count()
      .where("formItemOptionId", formItemOptionId)
      .whereExists(
        FormItemResponseOptionsValues.relatedQuery("formItemResponse")
          .where("formResponse:report.deleted", false)
          .skipUndefined()
          .where("formResponse.created", ">=", fromDateTime)
          .where("formResponse.created", "<=", untilDateTime)
          .eagerAlgorithm(Model.JoinEagerAlgorithm)
          .eager("formResponse.report")
      );
```

This **works** if, for example, I have make other queries and objection has in its cache the columns of `FormItemResponse`, `formResponse` and `report`. But if it is the first query, it fails with this trace:

```
TypeError: Cannot read property 'columns' of null
    at getAllColumnSelectionsForNode (/Users/alejandrolopez/NodeJS/notecrow-forms-backend/node_modules/objection/lib/queryBuilder/join/RelationJoiner.js:285:55)
    at getSelectionsForNode (/Users/alejandrolopez/NodeJS/notecrow-forms-backend/node_modules/objection/lib/queryBuilder/join/RelationJoiner.js:236:33)
    at RelationJoiner._buildSelects (/Users/alejandrolopez/NodeJS/notecrow-forms-backend/node_modules/objection/lib/queryBuilder/join/RelationJoiner.js:143:48)
    at RelationJoiner.build (/Users/alejandrolopez/NodeJS/notecrow-forms-backend/node_modules/objection/lib/queryBuilder/join/RelationJoiner.js:80:12)
    at JoinEagerOperation.onBuild (/Users/alejandrolopez/NodeJS/notecrow-forms-backend/node_modules/objection/lib/queryBuilder/operations/eager/JoinEagerOperation.js:35:8)
    at QueryBuilder.callOperationMethod (/Users/alejandrolopez/NodeJS/notecrow-forms-backend/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:361:33)
    at forEachOperation.op (/Users/alejandrolopez/NodeJS/notecrow-forms-backend/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:457:14)
    at QueryBuilder.forEachOperation (/Users/alejandrolopez/NodeJS/notecrow-forms-backend/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:295:13)
    at QueryBuilder.executeOnBuild (/Users/alejandrolopez/NodeJS/notecrow-forms-backend/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:455:10)
    at QueryBuilder.buildInto (/Users/alejandrolopez/NodeJS/notecrow-forms-backend/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:448:10)
    at buildInto (/Users/alejandrolopez/NodeJS/notecrow-forms-backend/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1352:25)
    at QueryBuilder.build (/Users/alejandrolopez/NodeJS/notecrow-forms-backend/node_modules/objection/lib/queryBuilder/QueryBuilder.js:557:19)
    at convertQueryBuilderBase (/Users/alejandrolopez/NodeJS/notecrow-forms-backend/node_modules/objection/lib/queryBuilder/operations/ObjectionToKnexConvertingOperation.js:92:35)
    at args.map (/Users/alejandrolopez/NodeJS/notecrow-forms-backend/node_modules/objection/lib/queryBuilder/operations/ObjectionToKnexConvertingOperation.js:60:14)
    at Array.map (<anonymous>)
    at convertArgs (/Users/alejandrolopez/NodeJS/notecrow-forms-backend/node_modules/objection/lib/queryBuilder/operations/ObjectionToKnexConvertingOperation.js:56:15)
    at KnexOperation.getKnexArgs (/Users/alejandrolopez/NodeJS/notecrow-forms-backend/node_modules/objection/lib/queryBuilder/operations/ObjectionToKnexConvertingOperation.js:18:12)
    at KnexOperation.onBuildKnex (/Users/alejandrolopez/NodeJS/notecrow-forms-backend/node_modules/objection/lib/queryBuilder/operations/KnexOperation.js:8:52)
    at QueryBuilder.callOperationMethod (/Users/alejandrolopez/NodeJS/notecrow-forms-backend/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:361:33)
    at forEachOperation.op (/Users/alejandrolopez/NodeJS/notecrow-forms-backend/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:465:14)
    at QueryBuilder.forEachOperation (/Users/alejandrolopez/NodeJS/notecrow-forms-backend/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:295:13)
    at QueryBuilder.executeOnBuildKnex (/Users/alejandrolopez/NodeJS/notecrow-forms-backend/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:463:10)
    at QueryBuilder.buildInto (/Users/alejandrolopez/NodeJS/notecrow-forms-backend/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:449:10)
    at buildInto (/Users/alejandrolopez/NodeJS/notecrow-forms-backend/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1352:25)
    at doExecute (/Users/alejandrolopez/NodeJS/notecrow-forms-backend/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1256:23)
    at Bluebird.try.then (/Users/alejandrolopez/NodeJS/notecrow-forms-backend/node_modules/objection/lib/queryBuilder/QueryBuilder.js:574:19)
    at tryCatcher (/Users/alejandrolopez/NodeJS/notecrow-forms-backend/node_modules/objection/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/alejandrolopez/NodeJS/notecrow-forms-backend/node_modules/objection/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/alejandrolopez/NodeJS/notecrow-forms-backend/node_modules/objection/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/alejandrolopez/NodeJS/notecrow-forms-backend/node_modules/objection/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/alejandrolopez/NodeJS/notecrow-forms-backend/node_modules/objection/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/Users/alejandrolopez/NodeJS/notecrow-forms-backend/node_modules/objection/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/alejandrolopez/NodeJS/notecrow-forms-backend/node_modules/objection/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/alejandrolopez/NodeJS/notecrow-forms-backend/node_modules/objection/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/alejandrolopez/NodeJS/notecrow-forms-backend/node_modules/objection/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

Basically, it looks like it doesn't perform the `knex:query select * from information_schema.columns where table_name = ? and table_schema = ?` for the tables inside of a `whereExists`.
At the beginning I thought that it would be related with the eager part, but debugging, I found out that the first table that it tries to get the columns info is formItemResponse.

**Comment by koskimas** [comment]
Use joinRelation instead of joinEager.

**Comment by koskimas** [comment]
I mean this:

```js
    totalNumber = await FormItemResponseOptionsValues.query()
      .count()
      .where("formItemOptionId", formItemOptionId)
      .whereExists(
        FormItemResponseOptionsValues.relatedQuery("formItemResponse")
          .where("formResponse:report.deleted", false)
          .skipUndefined()
          .where("formResponse.created", ">=", fromDateTime)
          .where("formResponse.created", "<=", untilDateTime)
          .joinRelation("formResponse.report")
      );
```

eager loading in a subquery doesn't make any sense.

**Comment by lopezvit** [comment]
Thank you, that solved the issue. I was looking for something like this, but couldn't find it in the documentation. Maybe it could be a good idea to some remark where the eager loading is that it doesn't happen to anybody in the future.

**Comment by koskimas** [comment]
What kind of remark would you add? If I add every remark of every wrong way of doing things to every function, the documentation would be unreadable. Eager loading means eagerly loading the rows of other tables with the "main" result. You are not fetching any rows since you are using it as a subquery. Therefore it should be obvious that it makes no sense.

**Comment by lopezvit** [comment]
I understand your frustration, when you know how things should be done, it is easy to think that it is obvious and also hard to understand how could anybody do it wrong.
But the thing is that many people (including me) don't have time to go through the whole documentation of all the libraries that they use.
My previous comment was only to **thank you** for the answer (that solved my problem) and trying to give something back by giving my opinion on how to improve the documentation the way **I** consumed: I first stumble in the `eager` and then tried to use it as my tool whenever I needed to have some reference to related entities. Since that and `joinRelation` are having similar use, if they would be "related" (as in _see also_ in some documentations) it would make it easier for people fo find it.

**Comment by koskimas** [comment]
I don't mean the documentation is perfect, but adding something that would make them more clear to you doesn't mean it would be more clear to most people. Everyone struggles with different things. I haven't seen anyone else struggle with this particular problem yet. If I get more issues about the same thing, I'll try to improve the documentation.

If I added notes to the docs whenever someone has a problem like that, for example the `eager` documentation would look something like this:

```
eager loads relations bla bla...
...

Note: You cannot use this method in a subquery. Use `joinRelation` instead.

Note: You cannot use this method with an insert query.

Note: You cannot use this method inside a `where` method in a grouped where clause.

Note: You cannot call this method after executing the query.

Note: .....
```

Objection is mostly just a query builder. Often times you need to be familiar with SQL. For example, what you needed here was a join. The join based eager algorithm added joins, so you were able to use the references. What you should have known here was that you want to use a join, and then look through the documentation for possible methods to create joins.

I also cannot start documenting SQL in objection docs. SQL knowledge is kind of a prerequisite for using objection.
