### ISSUE TITLE
problem when upsertGraph with a BelongsToOneRelation

### ISSUE THREAD

**Issue by francoisromain** [Vincit/objection.js#1329]
Hello, 

When we try to use upsertGraph with a BelongsToOneRelation, it returns an error: 

```
error: insert or update on table "foos" violates foreign key constraint "foos_bar_id_foreign"
```

Here is the full repro: 

```js
const connection = {
  host: 'localhost',
  port: 5432,
  database: 'tmp_upsert_bug',
  user: 'postgres',
  password: ''
}

const config = {
  knex: { client: 'pg', connection },
  dbManager: {
    superUser: connection.user,
    superPassword: connection.password
  }
}

const dbManager = require('knex-db-manager').databaseManagerFactory(config)
let Model

try {
  Model = require('./').Model
} catch (err) {
  Model = require('objection').Model
}

const Knex = require('knex')

async function main() {
  await createSchema()

  /// ////////////////////////////////////////////////////////////
  // Your reproduction
  /// ////////////////////////////////////////////////////////////

  const a = await Bars.query().upsertGraph(
    { id: 'bar-id', foo: { bar_id: 'bar-id' } },
    { insertMissing: true }
  )

  console.dir(a, { depth: null })

  await knex.destroy()
}

/// ////////////////////////////////////////////////////////////
// Database
/// ////////////////////////////////////////////////////////////

const knex = Knex(config.knex)

Model.knex(knex)

/// ////////////////////////////////////////////////////////////
// Models
/// ////////////////////////////////////////////////////////////

class Bars extends Model {
  static get tableName() {
    return 'bars'
  }

  static jsonSchema = {
    type: 'object',
    required: ['id'],

    properties: {
      id: { type: 'string' }
    }
  }

  static get relationMappings() {
    return {
      foo: {
        relation: Model.BelongsToOneRelation,
        modelClass: Foos,
        join: {
          from: 'bars.id',
          to: 'foos.bar_id'
        }
      }
    }
  }
}

class Foos extends Model {
  static get tableName() {
    return 'foos'
  }

  static jsonSchema = {
    type: 'object',
    required: ['bar_id'],

    properties: {
      bar_id: { type: 'string' }
    }
  }

  static idColumn = 'bar_id'
}

/// ////////////////////////////////////////////////////////////
// Schema
/// ////////////////////////////////////////////////////////////

async function createSchema() {
  await dbManager.dropDb(connection.database)
  await dbManager.createDb(connection.database)

  await knex.schema.dropTableIfExists('foos').dropTableIfExists('bars')

  await knex.schema
    .createTable('bars', table => {
      table.string('id').primary()
    })
    .createTable('foos', table => {
      table.string('bar_id').primary()
      table
        .foreign('bar_id')
        .references('bars.id')
        .onUpdate('CASCADE')
        .onDelete('CASCADE')
    })
}

main()
  .then(() => console.log('success'))
  .catch(console.error)
```

(Also, this repro works when we use a `sqlite3` driver, but gives the error above on `pg`)'

Are we doing something wrong here?
Thank you

**Comment by koskimas** [comment]
You need to use `onDelete('set null')` for the foreign key

**Comment by francoisromain** [comment]
@koskimas If we change `onDelete` to `SET NULL` on the foreign key, there is still the same error

**Comment by francoisromain** [comment]
@koskimas We still didn't find a solution for this. Could you please try the repro with `onDelete('set null')`. The problem is we try to upsert an object like this `{ id: 'bar-id', foo: { bar_id: 'bar-id' } }`, where the children has an id which points to the parent. 

here is the complete error: 

```
{
	error: ```insert or update on table "foos" violates foreign key constraint "foos_bar_id_foreign"
    at Connection.parseE (/node_modules/pg/lib/connection.js:601:11)
    at Connection.parseMessage (/node_modules/pg/lib/connection.js:398:19)
    at Socket.<anonymous> (/node_modules/pg/lib/connection.js:120:22)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:635:20)```,
  name: 'error',
  length: 238,
  severity: 'ERROR',
  code: '23503',
  detail: 'Key (bar_id)=(bar-id) is not present in table "bars".',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'foos',
  column: undefined,
  dataType: undefined,
  constraint: 'foos_bar_id_foreign',
  file: 'ri_triggers.c',
  line: '3245',
  routine: 'ri_ReportViolation'
}
```

**Comment by francoisromain** [comment]
ok we had to use `HasManyRelation` instead of `bleongsToOneRelation`
