### ISSUE TITLE
Help needed with relationMappings and eager loading

### ISSUE THREAD

**Issue by vladimirice** [Vincit/objection.js#1350]
How to reproduce

Very simplified tables

```
CREATE TABLE ideas (
    id BIGSERIAL NOT NULL primary key,
    text VARCHAR(1024)
);

CREATE TABLE cmt (
    id BIGSERIAL NOT NULL primary key,
    text VARCHAR(1024),
    idea BIGINT NOT NULL
)
```

Models

```
import { Model } from 'objection';

export default class Ideas extends Model {
  readonly id!: number;
  static tableName = 'ideas';
}
```

```
import { Model, RelationMappings } from 'objection';

export default class Cmt extends Model {
  static tableName = 'cmt';


  static modelPaths = [__dirname];

  static relationMappings: RelationMappings = {
    ideas: {
      relation: Model.BelongsToOneRelation,
      modelClass: 'ideas',
      join: {
        from: 'cmt.idea',
        to: 'ideas.id'
      }
    },
  };
}

```

A request somewhere
```
const withIdeas = await Cmt.query()
    .eager('ideas');
```

Response is:
```
Error: Cmt.relationMappings.ideas: join.from must have format TableName.columnName. For example "SomeTable.id" or in case of composite key ["SomeTable.a", "SomeTable.b"].

    at BelongsToOneRelation.createError (/home/vladimir/Projects/ucom/ucom.backend/node_modules/objection/lib/relations/Relation.js:232:14)
    at Object.createError (/home/vladimir/Projects/ucom/ucom.backend/node_modules/objection/lib/relations/Relation.js:46:32)
    at createRelationProperty (/home/vladimir/Projects/ucom/ucom.backend/node_modules/objection/lib/relations/Relation.js:346:17)
    at createJoinProperties (/home/vladimir/Projects/ucom/ucom.backend/node_modules/objection/lib/relations/Relation.js:302:20)
    at BelongsToOneRelation.setMapping (/home/vladimir/Projects/ucom/ucom.backend/node_modules/objection/lib/relations/Relation.js:54:11)
    at Object.keys.reduce (/home/vladimir/Projects/ucom/ucom.backend/node_modules/objection/lib/model/Model.js:735:29)
    at Array.reduce (<anonymous>)
    at getRelations (/home/vladimir/Projects/ucom/ucom.backend/node_modules/objection/lib/model/Model.js:731:46)
    at cachedGet (/home/vladimir/Projects/ucom/ucom.backend/node_modules/objection/lib/model/Model.js:679:61)
    at Function.getRelations (/home/vladimir/Projects/ucom/ucom.backend/node_modules/objection/lib/model/Model.js:465:12)
    at WhereInEagerOperation.onAdd (/home/vladimir/Projects/ucom/ucom.backend/node_modules/objection/lib/queryBuilder/operations/eager/WhereInEagerOperation.js:36:34)
    at QueryBuilder.addOperation (/home/vladimir/Projects/ucom/ucom.backend/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:234:33)
    at addEagerFetchOperation (/home/vladimir/Projects/ucom/ucom.backend/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1259:13)
    at beforeExecute (/home/vladimir/Projects/ucom/ucom.backend/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1138:5)
    at Bluebird.try (/home/vladimir/Projects/ucom/ucom.backend/node_modules/objection/lib/queryBuilder/QueryBuilder.js:568:31)
    at tryCatcher (/home/vladimir/Projects/ucom/ucom.backend/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/home/vladimir/Projects/ucom/ucom.backend/node_modules/bluebird/js/release/method.js:39:29)
    at QueryBuilder.execute (/home/vladimir/Projects/ucom/ucom.backend/node_modules/objection/lib/queryBuilder/QueryBuilder.js:568:24)
    at QueryBuilder.then (/home/vladimir/Projects/ucom/ucom.backend/node_modules/objection/lib/queryBuilder/QueryBuilder.js:473:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

The error is happened here - empty array is returned 
https://github.com/Vincit/objection.js/blob/master/lib/relations/RelationProperty.js#L205

A dirty fix:

https://github.com/Vincit/objection.js/blob/master/lib/utils/objectUtils.js#L64
change the last line

from 
return Array.from(map.values());

to
return Array.from(map);

---------

Please, help. What I'm doing wrong? :(

**Comment by koskimas** [comment]
Yes it does.

**Comment by koskimas** [comment]
Oh, there was a question at the bottom. I thought this was just one of those "your code that has 3600 tests doesn't work!#"!#!"#!"!!" issues.

Is the name of the `ideas` model file `ideas.js` (after compilation to js)?

**Comment by vladimirice** [comment]
Thank you a lot for the quick response, and I'm sorry about not to be obvious enough.

After searching a lot, I finally found a 3rd party dependency, which breaks eager relation. It is not a problem related to PostgreSQL.

Please observe a test project to investigate it.

https://github.com/vladimirice/objection-postgresql

If I add this dependency, an error occurs.
https://github.com/vladimirice/objection-postgresql/blob/master/example.js#L8

I use this dependency for one of my projects. A project above is just a sample project to reproduce an issue.

Maybe It is not a problem of objectionjs. Maybe a dependency `'node-dependency-injection'` breaks something or use some dirty tricks. But maybe not. I'll be pleased if you can take a look at what is happening.

Maybe this issue can help you to improve something in objection.js. Thanks!

**Comment by zazoomauro** [comment]
The conflict happens when require('collections')
https://github.com/montagejs/collections

Nothing related to node-dependency-injection

**Comment by koskimas** [comment]
> Is it possible to somehow avoid objectionjs errors related to collections usage?

It's possible, but I won't do that. No library should ever change the built-in methods like `Array.find`. You should drop whatever library that does this or put your efforts towards those libraries dropping these evil practices. It's insanely dangerous (and quite frankly stupid) to override the built-ins.
