### ISSUE TITLE
Error when inserting into Many to Many table.

### ISSUE THREAD

**Issue by krckyboy** [Vincit/objection.js#1367]
I am trying to make the /createProfile route work, but I'm running into an error which I'll show below. I have a Profile and Skills model, and also tables (profiles, skills). Inside each of the model, I have connected a third table for the many-to-many relation. Profile is created successfully, skills added to skills table, but the many to many table (profile_skill) isn't being filled, instead I get an error. I tried my best following the example in the docs, but I must have missed something. 

Part of migrations regarding three tables: 

```
.createTable('profiles', table => {
	table.increments('id').primary()
	table.string('location')
	table.string('website')
	table.string('bio', '1000')
	table.string('facebook')
	table.string('youtube')
	table.string('twitter')
	table.string('github_user_name')
	table.string('linkedin')
	table.string('instagram')
	table.timestamps(true, true)
	table
		.integer('user_id')
		.unsigned()
		.references('id')
		.inTable('users')
		.onDelete('SET NULL')
		.index()
		.unique()
})
	.createTable('skills', table => {
		table.increments('id').primary()
		table.string('name').unique()
		table.integer('count').defaultTo(0)
		table.specificType('aliases', 'text array')
		table.timestamps(true, true)
	})
	.createTable('profile_skill', table => {
		table.increments('id').primary()
		table.timestamps(true, true)
		table
			.integer('profile_id')
			.unsigned()
			.references('id')
			.inTable('profiles')
			.onDelete('CASCADE')
			.index()
		table
			.integer('skill_id')
			.unsigned()
			.references('id')
			.inTable('skills')
			.onDelete('CASCADE')
			.index()
	})
```

Models: 

```
class Profile extends Model {
	static get tableName() {
		return 'profiles'
	}

	static get relationMappings() {
		return {
			profile: {
				relation: Model.BelongsToOneRelation,
				modelClass: User,
				join: {
					from: 'profiles.user_id',
					to: 'users.id'
				}
			},
			profile_skill: {
				relation: Model.ManyToManyRelation,
				modelClass: Skill,
				join: {
					from: 'profiles.id',
					through: {
						from: 'profile_skill.profile_id',
						to: 'profile_skill.skill_id'
					},
					to: 'skills.id'
				}
			}
		}
	}
}

class Skill extends Model {
	static get tableName() {
		return 'skills'
	}

	static get relationMappings() {
		return {
			profile_skill: {
				relation: Model.ManyToManyRelation,
				modelClass: Profile,
				join: {
					from: 'skills.id',
					through: {
						from: 'profile_skill.skill_id',
						to: 'profile_skill.profile_id',
					},
					to: 'profiles.id'
				}

			}
		}
	}
}
```

Part of the controller:

```
const profile = await Profile.query().findOne({ user_id: req.user.id })

if (profile) {
	return res.status(400).json({ errors: [{ msg: 'Profile already created.' }] })
}

// Create profile
const newProfile = await Profile.query().insert({
	...profileObject
})

// Add skills to the DB that don't exist
for (let skill of skillsArray) {
	const skillInDb = await Skill.query().findOne({ name: skill })
	if (!skillInDb) {
		await Skill.query().insert({ name: skill })
	}
}

// Insert into profile_skill 
for (let skill of skillsArray) {
	const skillInDb = await Skill.query().findOne({ name: skill })
	await newProfile.$relatedQuery('profile_skill').insert({ profile_id: newProfile.id, skill_id: skillInDb.id })
}
```

Error received: 
```
{ error: column "profile_id" of relation "skills"
does not exist
    at Connection.parseE (C:\Users\krcky\Desktop\repos\Collab\node_modules\pg\lib\connection.js:602:11)
    at Connection.parseMessage (C:\Users\krcky\Desktop\repos\Collab\node_modules\pg\lib\connection.js:399:19)
    at Socket.<anonymous> (C:\Users\krcky\Desktop\repos\Collab\node_modules\pg\lib\connection.js:121:22)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  name: 'error',
  length: 189,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '23',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file:
   'd:\\pginstaller.auto\\postgres.windows-x64\\src\\backend\\parser\\parse_target.c',
  line: '1033',
  routine: 'checkInsertTargets' }
```

Graphical presentation of that part of the DB:

![image](https://user-images.githubusercontent.com/11292329/59130236-25cbd000-896f-11e9-89a8-470db96819c5.png)

Just to clarify, rows are successfully added for tables "Profiles", "Skills", but not for the many-to-many table "Profile_Skill".

**Comment by koskimas** [comment]
`newProfile.$relatedQuery('profile_skill').insert(skill)` means "insert a new skill into db **and** related it to `newProfile`". You want to use `relate` here instead.

```js
const profile = await Profile.query().findOne({ user_id: req.user.id })

if (profile) {
	return res.status(400).json({ errors: [{ msg: 'Profile already created.' }] })
}

// Create profile
const newProfile = await Profile.query().insert({
	...profileObject
})

// Add skills to the DB that don't exist
for (let skill of skillsArray) {
	const skillInDb = await Skill.query().findOne({ name: skill })
	if (!skillInDb) {
		await Skill.query().insert({ name: skill })
	}
}

// Insert into profile_skill 
for (let skill of skillsArray) {
	const skillInDb = await Skill.query().findOne({ name: skill })
	await newProfile.$relatedQuery('profile_skill').relate(skillInDb.id)
}
```
