### ISSUE TITLE
`modelPaths` not working as intended

### ISSUE THREAD

**Issue by javanotti** [Vincit/objection.js#1433]
Hi, I`m using Objection.js as an ORM for a simple task management app I`m currently working on. I used, as suggested in the documentation, the `BaseModel` "trick" to define a custom `modelPaths` path to define the path where my model definition files are located. 
ATM i have a simple data structure made of 3 tables: tasks, users, task_assignees, of which the latter is a simple relational table to hold the -obviously many to many- relations between the first two.
FYI my model definition files are named like such: `modelname.model.js`, while the class have a traditional nomenclature like `ModelName`.

I`m encountering the following problems:
If I define a relation like this in the task model:
```
static relationMappings = {
        assignees : {
            relation: BaseModel.ManyToManyRelation,
            modelClass: `User` ,
            join: {
                from: 'tasks.id',
                through: {
                    from: 'task_assignees.task_id',
                    to: 'task_assignees.assignee_id'
                },
                to: 'users.id'
            }
        }
}
```
I get the following error:
```
Error: Task.relationMappings.assignees: Cannot find module 'A:\PROJECTNAME\server\models\Use
r'
Require stack:
- A:\PROJECTNAME\node_modules\objection\lib\utils\resolveModel.js
- A:\PROJECTNAME\node_modules\objection\lib\relations\Relation.js
- A:\PROJECTNAME\node_modules\objection\lib\relations\hasMany\HasManyRelation.js
- A:\PROJECTNAME\node_modules\objection\lib\relations\hasOne\HasOneRelation.js
- A:\PROJECTNAME\node_modules\objection\lib\model\Model.js
- A:\PROJECTNAME\node_modules\objection\lib\objection.js
- A:\PROJECTNAME\server\configs\objection.config.js
- A:\PROJECTNAME\server\models\base.model.js
- A:\PROJECTNAME\server\models\task.model.js
- A:\PROJECTNAME\server\apis\v1\task.api.js
- A:\PROJECTNAME\server\apis\v1\main.api.js
- A:\PROJECTNAME\server\index.js
- A:\PROJECTNAME\index.js
    at ManyToManyRelation.createError (A:\PROJECTNAME\node_modules\objection\lib\relations\R
elation.js:240:14)
    at Object.createError (A:\PROJECTNAME\node_modules\objection\lib\relations\Relation.js:4
8:32)
    at resolveRelatedModelClass (A:\PROJECTNAME\node_modules\objection\lib\relations\Relatio
n.js:291:15)
    at ManyToManyRelation.setMapping (A:\PROJECTNAME\node_modules\objection\lib\relations\Re
lation.js:54:11)
    at ManyToManyRelation.setMapping (A:\PROJECTNAME\node_modules\objection\lib\relations\ma
nyToMany\ManyToManyRelation.js:34:26)
    at Function.getRelationUnsafe (A:\PROJECTNAME\node_modules\objection\lib\model\Model.js:
665:30)
    at Function.getRelation (A:\PROJECTNAME\node_modules\objection\lib\model\Model.js:672:27
)
    at Function.relatedQuery (A:\PROJECTNAME\node_modules\objection\lib\model\Model.js:546:2
7)
    at A:\PROJECTNAME\server\apis\v1\task.api.js:87:50
    at Layer.handle [as handle_request] (A:\PROJECTNAME\node_modules\express\lib\router\laye
r.js:95:5)
    at next (A:\PROJECTNAME\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (A:\PROJECTNAME\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (A:\PROJECTNAME\node_modules\express\lib\router\laye
r.js:95:5)
    at A:\PROJECTNAME\node_modules\express\lib\router\index.js:281:22
    at param (A:\PROJECTNAME\node_modules\express\lib\router\index.js:354:14)
    at param (A:\PROJECTNAME\node_modules\express\lib\router\index.js:365:14)
```

, 
so if I try and change Task`s  `modelClass` to `user.model.js`  ( i did so thinking that maybe the orm was looking for the model  by file name ), the error gets like:
```
TypeError: Cannot read property 'isPartial' of null
    at findFirstNonPartialAncestorQuery (A:\PROJECTNAME\node_modules\objection\lib\rela
\RelationSubqueryOperation.js:22:18)
    at RelationSubqueryOperation.onBuild (A:\PROJECTNAME\node_modules\objection\lib\rel
s\RelationSubqueryOperation.js:14:46)
    at QueryBuilder.callOperationMethod (A:\PROJECTNAME\node_modules\objection\lib\quer
der\QueryBuilderOperationSupport.js:345:33)
    at A:\PROJECTNAME\node_modules\objection\lib\queryBuilder\QueryBuilderOperationSupp
s:437:14
    at QueryBuilder.forEachOperation (A:\PROJECTNAME\node_modules\objection\lib\queryBu
\QueryBuilderOperationSupport.js:282:37)
    at QueryBuilder.executeOnBuild (A:\PROJECTNAME\node_modules\objection\lib\queryBuil
ueryBuilderOperationSupport.js:435:10)
    at callOnBuildHooks (A:\PROJECTNAME\node_modules\objection\lib\queryBuilder\QueryBu
.js:1363:11)
    at doExecute (A:\PROJECTNAME\node_modules\objection\lib\queryBuilder\QueryBuilder.j
3:13)
    at A:\PROJECTNAME\node_modules\objection\lib\queryBuilder\QueryBuilder.js:573:19
    at tryCatcher (A:\PROJECTNAME\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (A:\PROJECTNAME\node_modules\bluebird\js\relea
omise.js:517:31)
    at Promise._settlePromise (A:\PROJECTNAME\node_modules\bluebird\js\release\promise.
4:18)
    at Promise._settlePromise0 (A:\PROJECTNAME\node_modules\bluebird\js\release\promise
19:10)
    at Promise._settlePromises (A:\PROJECTNAME\node_modules\bluebird\js\release\promise
99:18)
    at _drainQueueStep (A:\PROJECTNAME\node_modules\bluebird\js\release\async.js:138:12
    at _drainQueue (A:\PROJECTNAME\node_modules\bluebird\js\release\async.js:131:9)
```

**Comment by koskimas** [comment]
Cannot reproduce. Please provide enough information for us to reproduce the bug.

**Comment by koskimas** [comment]
Oh, you need to use `modelClass: 'filename'` instead of the model class name. So in your case something like `modelClass: 'user.model'`

**Comment by koskimas** [comment]
Objection cannot know the class name without opening the file and we don't do that to keep the module loading to a minimum. Consider for example awa lambdas: we want to parse and compile the minimum amount of code. A single lambda may only need one model.

**Comment by javanotti** [comment]
I imagined that, but the problem here was the lack of eloquence in the error messages, since as you can see I did try to use 'modelClass: filename'. Turned out I had a typo in a find query somewhere in my code, but the error messages gave me no hints.
Anyway thank you for the fast answers and all the efforts you are putting in working on this orm, it's highly appreciated.
