### ISSUE TITLE
Objection ref is not working

### ISSUE THREAD

**Issue by mstaniewski** [Vincit/objection.js#1443]
Hello Objection community,

Yesterday i've been working with this wonderful ORM, but met one obstacle on my way.
I was trying to rewrite this SQL query:
```
 SELECT h.name, hs.title, hhs.created_at, hhs.value FROM horseman.horses h 
      JOIN horseman.horses_health_statuses hhs ON hhs.horses_id = h.id
      JOIN horseman.health_statuses hs ON hhs.health_statuses_id = hs.id
      WHERE h.id =1 AND hhs.created_at = 
      (SELECT MAX(created_at) FROM horseman.horses_health_statuses hhs2 
      WHERE hhs2.horses_id = h.id AND hhs2.health_statuses_id = hs.id);
```

Into a `query builder` form, but unfortunately it didn't work. According to docs, in order to make a where query on a subquery, i have to pass a callback to where method, which will have query builder provided as a param. 

Later on docs mention about `ref` function, to access parent table. Unfortunately this is a part that doesn't want to go further.

Right now I have a `Horse` model, which has relation with `HealthStatus` model. The point is to fetch `Horse.relationMappings.statuses` with such definition:
```
    statuses: {
      relation: BaseModel.ManyToManyRelation,
      modelClass: "HealthStatus",
      filter: qb =>
        qb
          .select(
            "health_statuses.title",
            "health_statuses.average",
            "health_statuses.treshold",
            "horses_health_statuses.created_at",
            "horses_health_statuses.value"
          )
          .where(
            "horses_health_statuses.created_at",
            HorseHealthStatus.query()
              .max("created_at")
              .where("horses_id", "=", ref("horses.id"))
          ),
      join: {
        from: "horses.id",
        through: {
          from: "horses_health_statuses.horses_id",
          to: "horses_health_statuses.health_statuses_id",
          extra: ["value"]
        },
        to: "health_statuses.id"
      }
    }
```

Eager loading this relation results with:
`Error: Unknown column 'horses.id' in 'where clause'`

Which references to the line with `ref` function usage. Is it `ref` working not as expected, or am I doing something wrong?

**Comment by koskimas** [comment]
I'd reconsider adding that much logic in the relation filter. For example, there are not tests for adding selects in there. There's no reason it wouldn't work, but I'd be cautious.

To answer your question, I think the problem is that in some cases (eager loading, joinRelation etc.) objection gives aliases for the tables so that their names don't collide. In that query, table `horses` probably has an alias.

Does this work?

```js
      filter: qb =>
        qb
          .select(
            "health_statuses.title",
            "health_statuses.average",
            "health_statuses.treshold",
            "horses_health_statuses.created_at",
            "horses_health_statuses.value"
          )
          .where(
            "horses_health_statuses.created_at",
            HorseHealthStatus.query()
              .max("created_at")
              .where("horses_id", "=", Horse.ref("id"))
          ),
```

`Model.ref` is not yet documented, but it will soon be. It's already tested and can be considered part of the public API.

When you use `Horse.ref`, objection knows that you want to refer to that table's columns and it uses the correct alias under the hood.

**Comment by mstaniewski** [comment]
@koskimas unfortunately it results with the same error:
```
api      | { Error: Unknown column 'horses.id' in 'where clause'
api      |     at Packet.asError (/var/www/api/node_modules/mysql2/lib/packets/packet.js:684:17)
api      |     at Query.execute (/var/www/api/node_modules/mysql2/lib/commands/command.js:28:26)
api      |     at Connection.handlePacket (/var/www/api/node_modules/mysql2/lib/connection.js:449:32)
api      |     at PacketParser.Connection.packetParser.p [as onPacket] (/var/www/api/node_modules/mysql2/lib/connection.js:72:12)
api      |     at PacketParser.executeStart (/var/www/api/node_modules/mysql2/lib/packet_parser.js:75:16)
api      |     at Socket.Connection.stream.on.data (/var/www/api/node_modules/mysql2/lib/connection.js:79:25)
api      |     at Socket.emit (events.js:198:13)
api      |     at addChunk (_stream_readable.js:288:12)
api      |     at readableAddChunk (_stream_readable.js:269:11)
api      |     at Socket.Readable.push (_stream_readable.js:224:10)
api      |     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
api      | From previous event:
api      |     at Client_MySQL2._query (/var/www/api/node_modules/knex/lib/dialects/mysql/index.js:124:12)
api      |     at Client_MySQL2.query (/var/www/api/node_modules/knex/lib/client.js:158:17)
api      |     at Runner.query (/var/www/api/node_modules/knex/lib/runner.js:135:36)
api      |     at /var/www/api/node_modules/knex/lib/runner.js:39:23
api      | From previous event:
api      |     at Runner.run (/var/www/api/node_modules/knex/lib/runner.js:25:16)
api      |     at Builder.Target.then (/var/www/api/node_modules/knex/lib/interface.js:14:43)
api      |   code: 'ER_BAD_FIELD_ERROR',
api      |   errno: 1054,
api      |   sqlState: '42S22',
api      |   sqlMessage: 'Unknown column \'horses.id\' in \'where clause\'' }
```

Objection version: 1.6.9

**Comment by koskimas** [comment]
Seeing the query itself would help :wink:

**Comment by mstaniewski** [comment]
@koskimas query from debug:
```
'select `health_statuses`.`title`, `health_statuses`.`average`, `health_statuses`.`treshold`, `horses_health_statuses`.`created_at`, `horses_health_statuses`.`value`, `horses_health_statuses`.`horses_id` as `objectiontmpjoin0`, `health_statuses`.`id` from `health_statuses` inner join `horses_health_statuses` on `health_statuses`.`id` = `horses_health_statuses`.`health_statuses_id` where `horses_health_statuses`.`horses_id` in (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) and `horses_health_statuses`.`created_at` = (select max(`created_at`) from `horses_health_statuses` where `horses_id` = `horses`.`id`)'
```

**Comment by koskimas** [comment]
You are not even joining the horses table. How could that possibly work?
