### ISSUE TITLE
Cyclic references error with simple #id / #ref graph data

### ISSUE THREAD

**Issue by lehni** [Vincit/objection.js#1482]
As mentioned on Gitter today, I am encountering an issue that I managed to reduce to this simple test-case. I don't think that reference is cyclic?

The code throws this error:

```
Error: the object graph contains cyclic references
    at GraphInsert._createNormalActions (/Users/lehni/Development/Lineto/objection.js/lib/queryBuilder/graph/insert/GraphInsert.js:91:13)
    at GraphInsert.createActions (/Users/lehni/Development/Lineto/objection.js/lib/queryBuilder/graph/insert/GraphInsert.js:15:21)
    at operations.reduce (/Users/lehni/Development/Lineto/objection.js/lib/queryBuilder/graph/GraphUpsert.js:244:33)
    at Array.reduce (<anonymous>)
    at currentGraph (/Users/lehni/Development/Lineto/objection.js/lib/queryBuilder/graph/GraphUpsert.js:242:23)```
```

Reproduction:

```js
let Model;

try {
  Model = require('./').Model;
} catch (err) {
  Model = require('objection').Model;
}

const Knex = require('knex');
const chai = require('chai');

async function main() {
  await createSchema();

  ///////////////////////////////////////////////////////////////
  // Your reproduction
  ///////////////////////////////////////////////////////////////

  await Person.query().insertGraph({
    firstName: 'Jennifer',
    lastName: 'Lawrence',

    pets: [
      {
        name: 'Doggo',
        species: 'dog'
      },
      {
        '#id': 'felix',
        name: 'Felix',
        species: 'cat'
      }
    ],

    favoritePet: {
      '#ref': 'felix'
    }
  }, { relate: true });

  const jennifer = await Person.query()
    .findOne({ firstName: 'Jennifer' })
    .eager('[pets, favoritePet]');

  chai.expect(jennifer.pets[0].name).to.equal('Doggo');
  chai.expect(jennifer.favoritePet && jennifer.favoritePet.name).to.equal('Felix');
}

///////////////////////////////////////////////////////////////
// Database
///////////////////////////////////////////////////////////////

const knex = Knex({
  client: 'sqlite3',
  useNullAsDefault: true,
  debug: false,
  connection: {
    filename: ':memory:'
  }
});

Model.knex(knex);

///////////////////////////////////////////////////////////////
// Models
///////////////////////////////////////////////////////////////

class Person extends Model {
  static get tableName() {
    return 'Person';
  }

  static get jsonSchema() {
    return {
      type: 'object',
      required: ['firstName', 'lastName'],

      properties: {
        id: { type: 'integer' },
        favoritePetId: { type: ['integer', 'null'] },
        firstName: { type: 'string', minLength: 1, maxLength: 255 },
        lastName: { type: 'string', minLength: 1, maxLength: 255 },
        age: { type: 'number' },

        address: {
          type: 'object',
          properties: {
            street: { type: 'string' },
            city: { type: 'string' },
            zipCode: { type: 'string' }
          }
        }
      }
    };
  }

  static get relationMappings() {
    return {
      pets: {
        relation: Model.HasManyRelation,
        modelClass: Animal,
        join: {
          from: 'Person.id',
          to: 'Animal.ownerId'
        }
      },

      favoritePet: {
        relation: Model.BelongsToOneRelation,
        modelClass: Animal,
        join: {
          from: 'Person.favoritePetId',
          to: 'Animal.id'
        }
      }
    };
  }
}

class Animal extends Model {
  static get tableName() {
    return 'Animal';
  }

  static get jsonSchema() {
    return {
      type: 'object',
      required: ['name'],

      properties: {
        id: { type: 'integer' },
        ownerId: { type: ['integer', 'null'] },
        name: { type: 'string', minLength: 1, maxLength: 255 },
        species: { type: 'string', minLength: 1, maxLength: 255 }
      }
    };
  }

  static get relationMappings() {
    return {
      owner: {
        relation: Model.BelongsToOneRelation,
        modelClass: Person,
        join: {
          from: 'Animal.ownerId',
          to: 'Person.id'
        }
      }
    };
  }
}

///////////////////////////////////////////////////////////////
// Schema
///////////////////////////////////////////////////////////////

async function createSchema() {
  await knex.schema
    .dropTableIfExists('Animal')
    .dropTableIfExists('Person');

  await knex.schema
    .createTable('Person', table => {
      table.increments('id').primary();
      table
        .integer('favoritePetId')
        .unsigned()
        .references('id')
        .inTable('Animal');
      table.string('firstName');
      table.string('lastName');
      table.integer('age');
    })
    .createTable('Animal', table => {
      table.increments('id').primary();
      table
        .integer('ownerId')
        .unsigned()
        .references('id')
        .inTable('Person');
      table.string('name');
      table.string('species');
    })
}

main()
  .then(() => {
    console.log('success')
    return knex.destroy()
  })
  .catch(err => {
    console.error(err)
    return knex.destroy()
  });
```

**Comment by koskimas** [comment]
Actually, with `insertGraph` that only does inserts, it is circular.

1. `pets` need Jennifer to be inserted because of the `ownerId` foreign key.
2. Jennifer needs `favoritePet` to be inserted because it has a foreign key to Pet.
3. `favoritePet` needs `felix` the pet to be inserted.

With `upsertGraph` that would be possible to solve, but I'm pretty sure currently even that would fail

**Comment by lehni** [comment]
Oh, I see! Ah, darn. Yes, it also fails with upsertGraph currently. Do you consider this worth fixing?

**Comment by lehni** [comment]
I'm using this approach now as a work-around... Not very efficient, but it seems to work for now:

```js
import {
  isObject,
  isArray,
  getDataPath,
  parseDataPath,
  clone
} from '@ditojs/utils'

async function upsertReferencedGraphAndFetch(query, data, options) {
  // TODO: This is a workaround for the following Objection.js issue.
  // Replace with a normal `upsertGraphAndFetch()` once it is fixed:
  // https://github.com/Vincit/objection.js/issues/1482

  // First, collect all #id identifiers and #ref references in the graph, along
  // with their data paths.
  const identifiers = {}
  const references = {}

  walkData(data, (item, path) => {
    if (isObject(item)) {
      const { '#id': id, '#ref': ref } = item
      if (id) {
        identifiers[id] = path.join('/')
      } else if (ref) {
        references[path.join('/')] = ref
      }
    }
  })

  // Now clone the data and delete all references from it, for the initial
  // upsert.
  const cloned = clone(data)
  for (const path of Object.keys(references)) {
    const parts = parseDataPath(path)
    const key = parts.pop()
    const parent = getDataPath(cloned, parts)
    delete parent[key]
  }

  const model = await query.clone().upsertGraphAndFetch(cloned, options)

  // Now for each identifier, create an object containing only the final id in
  // the fetched model data:
  const links = {}
  for (const [identifier, path] of Object.entries(identifiers)) {
    const { id } = getDataPath(model, path)
    links[identifier] = { id }
  }

  // And finally replace all references with the final ids, before upserting
  // once again:
  for (const [path, reference] of Object.entries(references)) {
    const link = links[reference]
    if (link) {
      setDataPath(model, path, link)
    }
  }

  return query.upsertGraphAndFetch(model, options)
}

function walkData(data, callback, path = []) {
  if (isObject(data) || isArray(data)) {
    for (const [key, value] of Object.entries(data)) {
      walkData(value, callback, [...path, key])
    }
  }
  callback(data, path)
}
```

**Comment by koskimas** [comment]
I don't think I'll be implementing this anytime soon. `upsertGraph` is such a pain to maintain that I want to focus on ironing out its more obvious bugs before complicating it further. I'll close this issue for now. Fully tested PR is still welcome though.
