### ISSUE TITLE
Pagination result size promise not returned

### ISSUE THREAD

**Issue by johanneslumpe** [Vincit/objection.js#159]
In https://github.com/Vincit/objection.js/blob/master/src/queryBuilder/QueryBuilder.js#L431 the promise which runs the query for the result size is not returned so it runs in parallel. Unfortunately this triggers bluebird to complain that a promise is not being returned.

Is there something we can do here to still return the promise to get rid of the error? Maybe a new method like `runInParallel` or `runWithQuery` which can return a promise. The result of the returned promise could be passed to `runAfter` as a second argument.

Thoughts?

**Comment by koskimas** [comment]
I'm not getting a complaint from bluebird. Do you have some debug options enabled for bluebird or something? I tested with bluebird 3.4.1 which is newest right now.

**Comment by johanneslumpe** [comment]
No, nothing. Using bluebird 3.4.1 here as well. As soon as I hit an endpoint which uses pagination bluebird complains about a promise not being returned. Running things in a development and not production environment though. The offending code:

```js
export default async ({ page, pageSize }) => (
  await Account
    .query()
    .page(page, pageSize)
);
```

bluebird then logs `Warning: a promise was created in a handler but was not returned from it` and references `CustomBuilder.resultSize` in the stack.

**Comment by gsenior** [comment]
Not sure if this helps, but I'm also encountering the same warning when using the `.range()` method after upgrading from 0.5.0 RC1 to 0.5.5. I double checked my Bluebird version which is also 3.4.1. The full warning:

```
Warning: a promise was created in a handler but was not returned from it
    at Runner.ensureConnection (/api/node_modules/knex/lib/runner.js:186:39)
    at Runner.run (/api/node_modules/knex/lib/runner.js:41:44)
    at QueryBuilder.Target.then (/api/node_modules/knex/lib/interface.js:32:43)
    at QueryBuilder.resultSize (/api/node_modules/objection/lib/queryBuilder/QueryBuilder.js:611:23)
    at QueryBuilder.<anonymous> (/api/node_modules/objection/lib/queryBuilder/QueryBuilder.js:642:34)
    at RunBeforeOperation.onBefore (/api/node_modules/objection/lib/queryBuilder/operations/RunBeforeOperation.js:44:22)
    at /api/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1279:19
    at /api/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1324:14
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
From previous event:
    at /api/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1323:23
    at arrayEach (/api/node_modules/objection/node_modules/lodash/lodash.js:485:11)
    at Function.forEach (/api/node_modules/objection/node_modules/lodash/lodash.js:8847:14)
    at promiseChain (/api/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1318:20)
    at chainBeforeOperations (/api/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1278:10)
    at QueryBuilder.execute (/api/node_modules/objection/lib/queryBuilder/QueryBuilder.js:704:15)
    at QueryBuilder.then (/api/node_modules/objection/lib/queryBuilder/QueryBuilder.js:527:24)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by koskimas** [comment]
This only happens when `NODE_ENV=development` which I never use. I'll try to figure out a fix for this.
