### ISSUE TITLE
Async errors don't show full stack trace

### ISSUE THREAD

**Issue by rclmenezes** [Vincit/objection.js#1618]
Using node 12.4.0, objection@2.0.7 and knex@0.20.4

If we make a very simple error:

```javascript
const knex = require("knex");
const { Model } = require("objection");

const db = knex({
  // This makes async stack traces work for raw knex queries
  asyncStackTraces: true,

  client: "postgres",
  connection: {
    host: "localhost",
    user: "postgres",
    password: "postgres",
    database: "postgres",
  },
  debug: true,
});

Model.knex(db);

class User extends Model {
  static get tableName() {
    return "users";
  }
}

async function main() {
  const user = await User.query().select("columnThatDoesntExist");
  console.log(user);
}

main()
  .catch(e => {
    console.log(e);
  })
  .finally(() => {
    db.destroy();
  });
```

And we run our script, we don't see any mention to the line that invoked the query:

```
$ NODE_ENV=development node ./src/bin/testObjection.ts 
{
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: 'f73a5d54-280f-4b7b-96cd-f68b56bd9c7b',
  sql: 'select "columnThatDoesntExist" from "users"'
}
DBError: select "columnThatDoesntExist" from "users" - column "columnThatDoesntExist" does not exist
    at wrapError (/Users/me/code/seedfi/web/node_modules/db-errors/lib/dbErrors.js:19:14)
    at handleExecuteError (/Users/me/code/seedfi/web/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1494:32)
    at QueryBuilder.execute (/Users/me/code/seedfi/web/node_modules/objection/lib/queryBuilder/QueryBuilder.js:685:13) {
  name: 'DBError',
  nativeError: error: column "columnThatDoesntExist" does not exist
      at buildKnexQuery (/Users/me/code/seedfi/web/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1579:63)
      at doExecute (/Users/me/code/seedfi/web/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1470:31)
      at QueryBuilder.execute (/Users/me/code/seedfi/web/node_modules/objection/lib/queryBuilder/QueryBuilder.js:682:28) {
    name: 'error',
    length: 120,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '8',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3294',
    routine: 'errorMissingColumn',
    originalStack: 'error: column "columnThatDoesntExist" does not exist\n    at ' +
      'Connection.parseE ' +
      '(/Users/me/code/seedfi/web/node_modules/pg/lib/connection.js:604:11)\n' +
      '    at Connection.parseMessage ' +
      '(/Users/me/code/seedfi/web/node_modules/pg/lib/connection.js:401:19)\n' +
      '    at Socket.<anonymous> ' +
      '(/Users/me/code/seedfi/web/node_modules/pg/lib/connection.js:121:22)\n' +
      '    at Socket.emit (events.js:200:13)\n    at addChunk ' +
      '(_stream_readable.js:294:12)\n    at readableAddChunk ' +
      '(_stream_readable.js:275:11)\n    at Socket.Readable.push ' +
      '(_stream_readable.js:210:10)\n    at TCP.onStreamRead ' +
      '(internal/stream_base_commons.js:166:17)\nFrom previous event:\n    at ' +
      'Client_PG._query ' +
      '(/Users/me/code/seedfi/web/node_modules/knex/lib/dialects/postgres/index.js:236:12)\n' +
      '    at Client_PG.query ' +
      '(/Users/me/code/seedfi/web/node_modules/knex/lib/client.js:168:17)\n' +
      '    at Runner.query ' +
      '(/Users/me/code/seedfi/web/node_modules/knex/lib/runner.js:133:36)\n' +
      '    at ' +
      '/Users/me/code/seedfi/web/node_modules/knex/lib/runner.js:39:23\n' +
      '    at ' +
      '/Users/me/code/seedfi/web/node_modules/knex/lib/runner.js:253:24\n' +
      '    at processImmediate (internal/timers.js:439:21)\nFrom previous ' +
      'event:\n    at Runner.ensureConnection ' +
      '(/Users/me/code/seedfi/web/node_modules/knex/lib/runner.js:251:8)\n' +
      '    at Runner.run ' +
      '(/Users/me/code/seedfi/web/node_modules/knex/lib/runner.js:25:12)\n' +
      '    at Builder.Target.then ' +
      '(/Users/me/code/seedfi/web/node_modules/knex/lib/interface.js:15:43)'
  },
  client: 'postgres'
}
```

This makes it pretty tricky to debug large applications running objection.

The invoking function is provided in raw knex. If you replace `main` with:

```javascript
async function main() {
  const user = await db.raw("select blah from users");
  console.log(user);
}
```

You get:

```
$ NODE_ENV=development node ./src/bin/testKnex.ts 
{
  method: 'raw',
  sql: 'select blah from users',
  bindings: [],
  options: {},
  __knexQueryUid: '013eeba9-90e2-4f04-a04d-cf28e65cbb1c'
}
error: column "blah" does not exist
    at Function.raw (/Users/me/code/seedfi/web/node_modules/knex/lib/util/make-knex.js:28:30)
    at main (/Users/me/code/seedfi/web/src/bin/testKnex.ts:17:25)
    at Object.<anonymous> (/Users/me/code/seedfi/web/src/bin/testKnex.ts:21:1)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11 {
```

**Comment by rclmenezes** [comment]
If I had to guess, the bug is in losing the old stack trace when creating a new error. [In QueryBuilder](https://github.com/Vincit/objection.js/blob/2d1bbf1af0ceb4bf62f1dca833a77b6fe3ddc8d3/lib/queryBuilder/QueryBuilder.js#L1493):

```
function handleExecuteError(builder, err) {
  let promise = Promise.reject(wrapError(err));

  builder.forEachOperation(true, op => {
    if (op.hasOnError()) {
      promise = promise.catch(err =>
        builder.callAsyncOperationMethod(op, 'onError', [builder, err])
      );
    }
  });

  return promise;
}
```

We can do something like:

```
const newErr = wrapError(err);
newErr.stack = err.stack;
let promise = Promise.reject(newErr);
```

Or handle it within db-errors! [In dbErrors.js](https://github.com/Vincit/db-errors/blob/master/lib/dbErrors.js#L11):

```
function wrapError(err) {
  const dbs = Object.keys(parsers);

  for (let i = 0, l = dbs.length; i < l; ++i) {
    const parserTree = parsers[dbs[i]];
    const result = parse(parserTree, err, null);

    if (result !== null) {
      return new result.node.error(result.args);
    }
  }

  return err;
}
```

We can do something like:

```
if (result !== null) {
  const newErr = new result.node.error(result.args);
  newErr.stack = err.stack;
  return newErr;
}
```

Either works!

**Comment by koskimas** [comment]
I'd merge a PR for the db-errors library.

**Comment by rclmenezes** [comment]
Ah! Turns out this is because custom Promise implementations don't get traces in v8. For example:

```
class CustomPromise {
  then(resolve, reject) {
    reject(new Error('wat'));
  }
}

async function main() {
  await new CustomPromise();
}

main().catch(e => {
  console.log(e);
});
```

[Knex also has this issue](https://github.com/knex/knex/pull/2505/files), since they make their own custom promise implementation. They get around it by preemptively copying the stack when the `asyncStackTraces` option is set to true:

https://github.com/knex/knex/pull/2505

Maybe we should re-open this issue?

One solution is to look at knex's configuration and implement similar behavior :)

```javascript
static query(trx) {
    const query = this.QueryBuilder.forClass(this).transacting(trx);

    const knex = this.knex();
    if (knex && knex.client && knex.client.config && knex.client.config.asyncStackTraces) {
      const err = new Error();
      const lines = err.stack.split('\n').slice(1);
      query._asyncStack = lines;
    }

    this.onCreateQuery(query);
    return query;
  }
```

Make sure it gets copied in .clone():

```javascript
clone() {
    ...

    builder._asyncStack = this._asyncStack;

    return builder;
  }
```

And then use it in handleExecuteError:

```javascript
function handleExecuteError(builder, err) {
  if (builder._asyncStack) {
    const originalStack = err.stack.split('\n');
    const newStack = originalStack.concat(builder._asyncStack);
    err.stack = newStack.join('\n');
    delete builder._asyncStack;
  }

  let promise = Promise.reject(wrapError(err));

  ...
}
```

Thoughts?
