### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by casalot** [Vincit/objection.js#167]
I'm trying to implement some exception handling on my API endpoints, but I'm not too sure if I'm doing this right. I have the following controller (which works 100% for successful inserts):

```javascript
class EventController {
  addEvent (req, res) {
    Event
    .query()
    .insert(req.payload)
    .then(event => {
      res(event);
    })
    .catch(err => {
      res(err);  // implement Boom
      console.log(err);
    })
  }
}
```
I have implemented `jsonSchema` on the `Event` model. As a test, I pass an empty body into the POST request.

I see quite a nasty stack trace in the console, and the response fails. Is this expected behaviour, or am I supposed to only get an `Error` object back in the `catch`?
```
{ Error: {
  "eventTypeId": "Missing required property: eventTypeId",
  "organisationId": "Invalid type: string (expected integer)",
  "agentUserId": "Invalid type: string (expected integer)",
  "teamLeaderUserId": "Invalid type: string (expected integer)",
  "interactionCategoryId": "Invalid type: string (expected integer)",
  "CSATRelated": "Invalid type: string (expected integer)",
  "firstCallResolution": "Invalid type: string (expected integer)"
}
    at parseValidationError (/Users/cas/source/takealot/tal-admin-api/node_modules/objection/lib/model/ModelBase.js:585:10)
    at Event.$validate (/Users/cas/source/takealot/tal-admin-api/node_modules/objection/lib/model/ModelBase.js:134:27)
    at Event.$setJson (/Users/cas/source/takealot/tal-admin-api/node_modules/objection/lib/model/ModelBase.js:250:23)
    at Event.$setJson (/Users/cas/source/takealot/tal-admin-api/node_modules/objection/lib/model/Model.js:305:35)
    at Function.fromJson (/Users/cas/source/takealot/tal-admin-api/node_modules/objection/lib/model/ModelBase.js:440:11)
    at Function.ensureModel (/Users/cas/source/takealot/tal-admin-api/node_modules/objection/lib/model/Model.js:546:25)
    at Function.ensureModelArray (/Users/cas/source/takealot/tal-admin-api/node_modules/objection/lib/model/Model.js:573:26)
    at InsertOperation.call (/Users/cas/source/takealot/tal-admin-api/node_modules/objection/lib/queryBuilder/operations/InsertOperation.js:51:40)
    at QueryBuilder.callQueryBuilderOperation (/Users/cas/source/takealot/tal-admin-api/node_modules/objection/lib/queryBuilder/QueryBuilderBase.js:279:19)
    at QueryBuilder.insert (/Users/cas/source/takealot/tal-admin-api/node_modules/objection/lib/queryBuilder/QueryBuilder.js:983:17)
    at QueryBuilder.decorator$writeQueryOperation [as insert] (/Users/cas/source/takealot/tal-admin-api/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1154:12)
    at addEvent (/Users/cas/source/takealot/tal-admin-api/api/controllers/knex/event.js:10:6)
    at Object.internals.handler (/Users/cas/source/takealot/tal-admin-api/node_modules/hapi/lib/handler.js:96:36)
    at request._protect.run (/Users/cas/source/takealot/tal-admin-api/node_modules/hapi/lib/handler.js:30:23)
    at internals.Protect.run (/Users/cas/source/takealot/tal-admin-api/node_modules/hapi/lib/protect.js:64:5)
    at exports.execute (/Users/cas/source/takealot/tal-admin-api/node_modules/hapi/lib/handler.js:24:22)
    at each (/Users/cas/source/takealot/tal-admin-api/node_modules/hapi/lib/request.js:383:16)
    at iterate (/Users/cas/source/takealot/tal-admin-api/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at done (/Users/cas/source/takealot/tal-admin-api/node_modules/hapi/node_modules/items/lib/index.js:28:25)
    at Hoek.once (/Users/cas/source/takealot/tal-admin-api/node_modules/hapi/lib/protect.js:52:16)
    at wrapped (/Users/cas/source/takealot/tal-admin-api/node_modules/hapi/node_modules/hoek/lib/index.js:872:20)
    at done (/Users/cas/source/takealot/tal-admin-api/node_modules/hapi/node_modules/items/lib/index.js:31:25)
    at Function.wrapped (/Users/cas/source/takealot/tal-admin-api/node_modules/hapi/node_modules/hoek/lib/index.js:872:20)
    at Function.internals.continue (/Users/cas/source/takealot/tal-admin-api/node_modules/hapi/lib/reply.js:107:10)
    at /Users/cas/source/takealot/tal-admin-api/node_modules/dogwater/lib/index.js:68:35
    at Items.serial (/Users/cas/source/takealot/tal-admin-api/node_modules/hapi/lib/request.js:402:22)
    at iterate (/Users/cas/source/takealot/tal-admin-api/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at Object.exports.serial (/Users/cas/source/takealot/tal-admin-api/node_modules/hapi/node_modules/items/lib/index.js:39:9)
    at _protect.run (/Users/cas/source/takealot/tal-admin-api/node_modules/hapi/lib/request.js:397:15)
    at internals.Protect.run (/Users/cas/source/takealot/tal-admin-api/node_modules/hapi/lib/protect.js:64:5)
    at internals.Request._invoke (/Users/cas/source/takealot/tal-admin-api/node_modules/hapi/lib/request.js:395:19)
    at each (/Users/cas/source/takealot/tal-admin-api/node_modules/hapi/lib/request.js:380:25)
    at iterate (/Users/cas/source/takealot/tal-admin-api/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at done (/Users/cas/source/takealot/tal-admin-api/node_modules/hapi/node_modules/items/lib/index.js:28:25)
    at internals.cleanupJSONP (/Users/cas/source/takealot/tal-admin-api/node_modules/hapi/lib/route.js:469:12)
    at each (/Users/cas/source/takealot/tal-admin-api/node_modules/hapi/lib/request.js:383:16)
    at iterate (/Users/cas/source/takealot/tal-admin-api/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at done (/Users/cas/source/takealot/tal-admin-api/node_modules/hapi/node_modules/items/lib/index.js:28:25)
    at onParsed (/Users/cas/source/takealot/tal-admin-api/node_modules/hapi/lib/route.js:395:20)
    at Subtext.parse (/Users/cas/source/takealot/tal-admin-api/node_modules/hapi/lib/route.js:416:20)
  data:
   { eventTypeId: 'Missing required property: eventTypeId',
     organisationId: 'Invalid type: string (expected integer)',
     agentUserId: 'Invalid type: string (expected integer)',
     teamLeaderUserId: 'Invalid type: string (expected integer)',
     interactionCategoryId: 'Invalid type: string (expected integer)',
     CSATRelated: 'Invalid type: string (expected integer)',
     firstCallResolution: 'Invalid type: string (expected integer)' },
  statusCode: 400,
  message: '{\n  "eventTypeId": "Missing required property: eventTypeId",\n  "organisationId": "Invalid type: string (expected integer)",\n  "agentUserId": "Invalid type: string (expected integer)",\n  "teamLeaderUserId": "Invalid type: string (expected integer)",\n  "interactionCategoryId": "Invalid type: string (expected integer)",\n  "CSATRelated": "Invalid type: string (expected integer)",\n  "firstCallResolution": "Invalid type: string (expected integer)"\n}' }
Debug: internal, implementation, error
    Error: Error: {
  "eventTypeId": "Missing required property: eventTypeId",
  "organisationId": "Invalid type: string (expected integer)",
  "agentUserId": "Invalid type: string (expected integer)",
  "teamLeaderUserId": "Invalid type: string (expected integer)",
  "interactionCategoryId": "Invalid type: string (expected integer)",
  "CSATRelated": "Invalid type: string (expected integer)",
  "firstCallResolution": "Invalid type: string (expected integer)"
}
    at Event.query.insert.then.catch.err (/Users/cas/source/takealot/tal-admin-api/api/controllers/knex/event.js:16:16)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at tryCatcher (/Users/cas/source/takealot/tal-admin-api/node_modules/objection/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/cas/source/takealot/tal-admin-api/node_modules/objection/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/Users/cas/source/takealot/tal-admin-api/node_modules/objection/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/Users/cas/source/takealot/tal-admin-api/node_modules/objection/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/Users/cas/source/takealot/tal-admin-api/node_modules/objection/node_modules/bluebird/js/release/promise.js:681:18)
    at Async._drainQueue (/Users/cas/source/takealot/tal-admin-api/node_modules/objection/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/cas/source/takealot/tal-admin-api/node_modules/objection/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/cas/source/takealot/tal-admin-api/node_modules/objection/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

**Comment by koskimas** [comment]
You should always get an subclass instance of `Error` in a promise `catch` method. I don't know what you mean by "nasty stacktrace". That's what you get when you console.log an error. You can call `console.log(err.stack)` for a stack trace without the properties.

The error is an instance of `objection.ValidationError` and as you see, there is a `data` property that contains the jsonSchema errors.

What would you like the `error` to be?

**Comment by koskimas** [comment]
I don't know why the response fails. Maybe you can try `res(err.data)`?

**Comment by casalot** [comment]
I was wondering if the `parseValidationError`,etc was supposed to be there? But, I suppose the `catch` will get the "raw" error stack, including the `Error` object, as well as the stack trace.

Yes, I'm using a combination of `err.data` and `err.responseCode` to build my own error responses now.

**Comment by koskimas** [comment]
Yeah, the stack trace is the stack trace 😄 I don't want to design my methods and call hierarchies to make the stack traces look pretty.
