### ISSUE TITLE
"AnyOf" string and integer: replace is not a function

### ISSUE THREAD

**Issue by mcchrish** [Vincit/objection.js#171]
```js
  static jsonSchema = {
    type: 'object',
    properties: {
      id: {anyOf: [
        {type: 'string', pattern: /[0-9]?$/},
        {type: 'integer'}
      ]}
  }
```

Seems to be a problem with the new ajv validator.

```
     TypeError: str.replace is not a function
      at escapeQuotes (node_modules/ajv/lib/compile/util.js:111:14)
      at Object.toQuotedString (node_modules/ajv/lib/compile/util.js:188:17)
      at Object.generate_pattern [as code] (node_modules/ajv/lib/dotjs/pattern.js:34:28)
      at Object.generate_validate [as validate] (node_modules/ajv/lib/dotjs/validate.js:196:35)
      at Object.generate_anyOf [as code] (node_modules/ajv/lib/dotjs/anyOf.js:34:27)
      at Object.generate_validate [as validate] (node_modules/ajv/lib/dotjs/validate.js:196:35)
      at Object.generate_properties [as code] (node_modules/ajv/lib/dotjs/properties.js:198:26)
      at generate_validate (node_modules/ajv/lib/dotjs/validate.js:196:35)
      at localCompile (node_modules/ajv/lib/compile/index.js:79:22)
      at Ajv.compile (node_modules/ajv/lib/compile/index.js:47:13)
      at _compile (node_modules/ajv/lib/ajv.js:299:29)
      at Ajv.compile (node_modules/ajv/lib/ajv.js:110:34)
      at compileJsonSchemaValidator (node_modules/objection/lib/model/ModelBase.js:772:16)
      at Function.defaultJsonSchemaValidator (node_modules/objection/lib/model/ModelBase.js:527:12)
      at Function.descriptor.value [as defaultJsonSchemaValidator] (node_modules/objection/lib/utils/decorators/memoize.js:51:26)
      at Function.jsonSchemaValidator (node_modules/objection/lib/model/ModelBase.js:501:19)
      at User.$validate (node_modules/objection/lib/model/ModelBase.js:145:32)
      at User.$validate (node_modules/objection/lib/model/Model.js:273:45)
      at User.$setJson (node_modules/objection/lib/model/ModelBase.js:262:23)
      at User.$setJson (node_modules/objection/lib/model/Model.js:314:35)
      at Function.fromJson (node_modules/objection/lib/model/ModelBase.js:464:11)
      at Function.ensureModel (node_modules/objection/lib/model/Model.js:560:25)
      at Function.ensureModelArray (node_modules/objection/lib/model/Model.js:587:26)
      at InsertOperation.call (node_modules/objection/lib/queryBuilder/operations/InsertOperation.js:51:40)
      at QueryBuilder.callQueryBuilderOperation (node_modules/objection/lib/queryBuilder/QueryBuilderBase.js:279:19)
      at QueryBuilder.insert (node_modules/objection/lib/queryBuilder/QueryBuilder.js:989:17)
      at QueryBuilder.decorator$writeQueryOperation [as insert] (node_modules/objection/lib/queryBuilder/QueryBuilder.js:1200:12)
      at src/objection-adapter/index.js:204:8
      at undefined.next (native)
      at step (src/objection-adapter/index.js:5:1)
      at src/objection-adapter/index.js:5:1
      at new Promise (node_modules/core-js/modules/es6.promise.js:193:7)
      at src/objection-adapter/index.js:5:1
      at Object.create (src/objection-adapter/index.js:196:31)
      at node_modules/feathers-hooks/lib/hooks.js:74:31
      at new Promise (node_modules/core-js/modules/es6.promise.js:193:7)
      at node_modules/feathers-hooks/lib/hooks.js:58:16
      at run (node_modules/core-js/modules/es6.promise.js:89:22)
      at node_modules/core-js/modules/es6.promise.js:102:28
      at flush (node_modules/core-js/modules/_microtask.js:18:9)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

Works when the `{type: 'string', pattern: /[0-9]?$/}` is removed.

**Comment by mcchrish** [comment]
Update:

If I change the regex to string, it will work:
```
{type: 'string', pattern: '[0-9]?$'}
```

Is this a breaking change?

**Comment by koskimas** [comment]
JSON schema states that the pattern must be a string. Json schema is itself json and json doesn't have a regex type. tv4 incorrectly supported regular expression type.
