### ISSUE TITLE
JsonSchema Validation Error on upsertGraph

### ISSUE THREAD

**Issue by youmustfight** [Vincit/objection.js#1713]
Still exploring this issue. Will try to make a reproduction asap.

## Summary:

In one part of our application, we're looking to use upsertGraph because we have a situation where an update is 2 relations deep. A user is able to edit an `asset` they own, the organization it's `managedBy`, and the `address` for that organization.

When I started, `upsertGraphAndFetch`, it correctly was updating the `asset` and the `asset.managedBy` models. However, when I started adding properties to the `asset.managedBy.address` model and an insertion was required, a validation error began to be thrown:

**Stacktrace**:
```
TypeError: id.replace is not a function\n    at Function.normalizeId (/usr/src/backends/node_modules/objection/node_modules/ajv/lib/compile/resolve.js:221:18)\n    at Ajv._addSchema (/usr/src/backends/node_modules/objection/node_modules/ajv/lib/ajv.js:301:20)\n    at Ajv.compile (/usr/src/backends/node_modules/objection/node_modules/ajv/lib/ajv.js:113:24)\n    at AjvValidator.compileNormalValidator (/usr/src/backends/node_modules/objection/lib/model/AjvValidator.js:140:21)\n    at AjvValidator.getValidator (/usr/src/backends/node_modules/objection/lib/model/AjvValidator.js:125:26)\n    at AjvValidator.validate (/usr/src/backends/node_modules/objection/lib/model/AjvValidator.js:70:28)\n    at validate (/usr/src/backends/node_modules/objection/lib/model/modelValidate.js:35:20)\n    at Address.$validate (/usr/src/backends/node_modules/objection/lib/model/Model.js:93:12)\n    at GraphInsertAction._insert (/usr/src/backends/node_modules/objection/lib/queryBuilder/graph/insert/GraphInsertAction.js:177:16)\n    at GraphInsertAction._insertBatch (/usr/src/backends/node_modules/objection/lib/queryBuilder/graph/insert/GraphInsertAction.js:48:16)\n    at <anonymous>"}
```

**Node Version: 8.12.0**
**Objection Version: 2.1.3**

## Initial Guesses

**On `modelValidate.js:35`, is `ctx.jsonSchema` the correct values? I feel like it should be the model's jsonSchema mappings, not the properties of the row to be inserted.**

![image](https://user-images.githubusercontent.com/4956240/76558060-02403380-6473-11ea-9739-b979b5b6ec91.png)

## UpsertGraphAndFetch Call

```javascript
Asset.query(req.trx).upsertGraphAndFetch({ ...asset })
```

**Example Asset (and graph) JSON used in upsertGraphAndFetch**
```json
{
        "id": 2286,
        "caseId": 75,
        "type": "financial",
        "subType": "checking_account",
        "subTypeOtherDescription": null,
        "tertiaryType": null,
        "value": 303,
        "portionOwned": 100,
        "description": "",
        "interest": "debtor1",
        "interestExplanation": null,
        "communityProperty": null,
        "addressId": null,
        "address": null,
        "vehicleMake": null,
        "vehicleModel": null,
        "vehicleYear": null,
        "estimatedMileage": null,
        "accountNumber": null,
        "closedAt": null,
        "name": null,
        "ein": null,
        "startedAt": null,
        "endedAt": null,
        "isSurrendering": null,
        "isRetainRedeem": null,
        "isRetainReaffirm": null,
        "isRetainOther": null,
        "isRetainOtherExplanation": null,
        "hazardous": false,
        "hazardousExplanation": null,
        "exemptions": [],
        "managedBy": {
            "id": 4222,
            "caseId": 75,
            "type": null,
            "name": "Solidarity Community Federal Credit Unions",
            "age": null,
            "relationship": null,
            "livesWithDebtor": null,
            -- Model to Insert --
            "addressId": null,
            "address": {
                "street1": "11 str",
                "street2": "5a",
                "city": "nyc",
                "state": "ny"
            },
            -- Model to Insert --
            "createdAt": "2020-02-09T03:26:51.549Z",
            "updatedAt": null
        },
        "accessibleBy": [],
        "beneficiaries": [],
        "createdAt": "2020-02-09T03:26:51.549Z",
        "updatedAt": "2020-03-12T02:55:15.443Z"
}
```

## Models

Will list out our asset, party, and address models below

**Asset Model**
```javascript
class AssetQueryBuilder<M extends Model, R = M[]> extends QueryBuilder<M, R> {
  forUser = idMethod<User>((userId: number) => this
    .joinRelated('case')
    .where('case.user_id', userId));
}

export default class Asset extends BaseModel {
  QueryBuilderType!: AssetQueryBuilder<this, this[]>;
  static QueryBuilder = AssetQueryBuilder;

  static get tableName() {
    return 'assets';
  }

  static get jsonSchema(): JSONSchema {
    return {
      type: 'object',
      properties: {
        id: { type: ['integer', 'null'] },
        caseId: { type: ['integer'] },
        type: { type: ['string', 'null'] },
        subType: { type: ['string', 'null'] },
        subTypeOtherDescription: { type: ['string', 'null'] },
        tertiaryType: { type: ['string', 'null'] },
        value: { type: ['number', 'null'] },
        valueOwned: { type: ['number', 'null'] },
        valueLiens: { type: ['number', 'null'] },
        portionOwned: { type: ['integer', 'null'] },
        description: { type: ['string', 'null'] },
        interest: { type: ['string', 'null'] },
        interestExplanation: { type: ['string', 'null'] },
        communityProperty: { type: ['string', 'null'] },
        addressId: { type: ['integer', 'null'] },
        vehicleMake: { type: ['string', 'null'] },
        vehicleModel: { type: ['string', 'null'] },
        vehicleYear: { type: ['integer', 'null'] },
        estimatedMileage: { type: ['integer', 'null'] },
        accountNumber: { type: ['string', 'null'] },
        closedAt: { type: ['string', 'null'], format: 'date-time' },
        name: { type: ['string', 'null'] },
        ein: { type: ['string', 'null'] },
        isSurrendering: { type: ['boolean', 'null'] },
        isRetainRedeem: { type: ['boolean', 'null'] },
        isRetainReaffirm: { type: ['boolean', 'null'] },
        isRetainOther: { type: ['boolean', 'null'] },
        isRetainOtherExplanation: { type: ['string', 'null'] },
        hazardous: { type: ['boolean', 'null'] },
        hazardousExplanation: { type: ['string', 'null'] },
        startedAt: { type: ['string', 'null'], format: 'date-time' },
        endedAt: { type: ['string', 'null'], format: 'date-time' },
        createdAt: { type: ['string', 'null'], format: 'date-time' },
        updatedAt: { type: ['string', 'null'], format: 'date-time' },
      },
    };
  }

  static relationMappings(): RelationMappings {
    return {
      case: {
        relation: BaseModel.BelongsToOneRelation,
        modelClass: Case,
        join: {
          from: 'assets.caseId',
          to: 'cases.id',
        },
      },
      address: {
        relation: BaseModel.BelongsToOneRelation,
        modelClass: Address,
        join: {
          from: 'assets.addressId',
          to: 'addresss.id',
        },
      },
      claims: {
        relation: BaseModel.ManyToManyRelation,
        modelClass: Claim,
        join: {
          from: 'assets.id',
          through: {
            from: 'assets_claims.assetId',
            to: 'assets_claims.claimId',
          },
          to: 'claims.id',
        },
      },
      contracts: {
        relation: BaseModel.ManyToManyRelation,
        modelClass: Contract,
        join: {
          from: 'assets.id',
          through: {
            from: 'assets_contracts.assetId',
            to: 'assets_contracts.contractId',
          },
          to: 'contracts.id',
        },
      },
      exemptions: {
        relation: BaseModel.HasManyRelation,
        modelClass: Exemption,
        join: {
          from: 'assets.id',
          to: 'exemptions.assetId',
        },
      },
      managedBy: {
        relation: BaseModel.HasOneThroughRelation,
        modelClass: Party,
        join: {
          from: 'assets.id',
          through: {
            from: 'assets_partys.assetId',
            to: 'assets_partys.partyId',
          },
          to: 'partys.id',
        },
        filter: (qb) => qb.where('assets_partys.relation', '=', ASSET_PARTY_RELATION.MANAGED_BY),
      },
      accessibleBy: {
        relation: BaseModel.ManyToManyRelation,
        modelClass: Party,
        join: {
          from: 'assets.id',
          through: {
            from: 'assets_partys.assetId',
            to: 'assets_partys.partyId',
          },
          to: 'partys.id',
        },
        filter: (qb) => qb.where('assets_partys.relation', '=', ASSET_PARTY_RELATION.ACCESSIBLE_BY),
      },
      beneficiaries: {
        relation: BaseModel.ManyToManyRelation,
        modelClass: Party,
        join: {
          from: 'assets.id',
          through: {
            from: 'assets_partys.assetId',
            to: 'assets_partys.partyId',
          },
          to: 'partys.id',
        },
        filter: (qb) => qb.where('assets_partys.relation', '=', ASSET_PARTY_RELATION.BENEFICIARY),
      },
    };
  }
}
```

**Party (What the "managedBy" relation is)**
```javascript
export default class Party extends BaseModel {
  static get tableName() {
    return 'partys';
  }

  static get jsonSchema(): JSONSchema {
    return {
      type: 'object',
      properties: {
        id: { type: ['integer', 'null'] },
        caseId: { type: ['integer'] },
        type: { type: ['string', 'null'] },
        name: { type: ['string', 'null'] },
        age: { type: ['number', 'null'] },
        relationship: { type: ['string', 'null'] },
        livesWithDebtor: { type: ['boolean', 'null'] },
        addressId: { type: ['integer', 'null'] },
        createdAt: { type: ['string', 'null'], format: 'date-time' },
        updatedAt: { type: ['string', 'null'], format: 'date-time' },
      },
    };
  }

  static relationMappings(): RelationMappings {
    return {
      asset: {
        relation: BaseModel.BelongsToOneRelation,
        modelClass: Asset,
        join: {
          from: 'partys.id',
          through: {
            from: 'assets_partys.partyId',
            to: 'assets_partys.assetId',
            extra: ['relation'],
          },
          to: 'assets.id',
        },
      },
      case: {
        relation: BaseModel.BelongsToOneRelation,
        modelClass: Case,
        join: {
          from: 'partys.casesId',
          to: 'cases.id',
        },
      },
      address: {
        relation: BaseModel.HasOneRelation,
        modelClass: Address,
        join: {
          from: 'partys.addressId',
          to: 'addresss.id',
        },
      },
      claims: {
        relation: BaseModel.ManyToManyRelation,
        modelClass: Claim,
        join: {
          from: 'partys.id',
          through: {
            from: 'claims_partys.partyId',
            to: 'claims_partys.claimId',
          },
          to: 'claims.id',
        },
        filter: (qb) => qb.where('claims_partys.relation', '=', CLAIM_PARTY_RELATION.CODEBTOR),
      },
      contracts: {
        relation: BaseModel.ManyToManyRelation,
        modelClass: Contract,
        join: {
          from: 'partys.id',
          through: {
            from: 'contracts_partys.partyId',
            to: 'contracts_partys.contractId',
          },
          to: 'contracts.id',
        },
        filter: (qb) => qb.where('contracts_partys.relation', '=', CONTRACT_PARTY_RELATION.CODEBTOR),
      },
    };
  }
}
```

**Address**
This is the inserted model
```javascript
import { JSONSchema, RelationMappings, TransactionOrKnex } from 'objection';

export default class Address extends BaseModel {
  static get tableName() {
    return 'addresss';
  }

  static get jsonSchema(): JSONSchema {
    return {
      type: 'object',
      properties: {
        id: { type: ['integer', 'null'] },
        type: { type: ['string', 'null'] }, // physical, mailing
        attention: { type: ['string', 'null'] },
        street1: { type: ['string', 'null'] },
        street2: { type: ['string', 'null'] },
        street3: { type: ['string', 'null'] },
        street4: { type: ['string', 'null'] },
        unit: { type: ['string', 'null'] },
        city: { type: ['string', 'null'] },
        county: { type: ['string', 'null'] },
        state: { type: ['string', 'null'] },
        zipcode: { type: ['string', 'null'] },
        country: { type: ['string', 'null'] },
        startedAt: { type: ['string', 'null'] },
        endedAt: { type: ['string', 'null'] },
        latitude: { type: ['number', 'null'] },
        longitude: { type: ['number', 'null'] },
        point: { type: ['string', 'null'] }, // geographic?
        createdAt: { type: 'string', format: 'date-time' },
        updatedAt: { type: 'string', format: 'date-time' },
        // Virtuals
        formatted: { type: ['string', 'null'] },
      },
    };
  }

  static relationMappings(): RelationMappings {
    return {
      attorney: {
        relation: BaseModel.BelongsToOneRelation,
        modelClass: Attorney,
        join: {
          from: 'addresss.id',
          to: 'attorneys.addressId',
        },
      },
      filer: {
        relation: BaseModel.HasOneThroughRelation,
        modelClass: Filer,
        join: {
          from: 'addresss.id',
          through: {
            from: 'filers_addresss.addressId',
            to: 'filers_addresss.filerId',
            extra: ['primary'],
          },
          to: 'filers.id',
        },
      },
    }
  }

}
```

**Comment by youmustfight** [comment]
Well some progress, new issue, but this may have been the problem causer. Our base model has a $beforeValidate method:

```javascript
$beforeValidate(jsonSchema, json, opt) {
    json = super.$beforeValidate(json);
    ...
    return json;
  }
```

We incorrectly passed in arguments to the `super`, which might be why our model properties were being treated like the jsonSchema
```javascript
$beforeValidate(jsonSchema, json, opt) {
    json = super.$beforeValidate(jsonSchema, json, opt);
    ...
    return json;
  }
```

**Comment by youmustfight** [comment]
Going to close cause this is now a separate concern
