### ISSUE TITLE
How to read information from a join table in a many to many relationship

### ISSUE THREAD

**Issue by jonnyom** [Vincit/objection.js#1769]
Hey there, I'm using Object 2.5.1 and I'm having a bit of trouble with a many to many relationship.

I have this many to many relationship that looks like this on my Team model.

```javascript
users: {
        relation: Model.ManyToManyRelation,
        modelClass: User,
        join: {
          from: 'teams.id',
          through: {
            from: 'teamsToUsers.teamId',
            to: 'teamsToUsers.userId',
          },
          to: 'users.id',
        },
      },
```

I can pull out the users no problem, but my join table `teamsToUsers` also contains information that I need about each user, specific to that team.

How can I fetch information from the join table itself, and append it to the user record? 

e.g. a response would ideally look something like this, where the individual users in the relation have the information from `teamsToUsers` appended to their object (specifically, `joinedTeamAt` and `teamRoleId`)

```javascript
Team {
  id: 1,
  name: 'test',
  isPersonal: false,
  deletedAt: null,
  createdAt: 2020-05-29T16:08:58.423Z,
  updatedAt: 2020-05-29T16:08:58.423Z,
  users: [
    User {
      id: 1,
      roleId: 1,
      deletedAt: null,
      createdAt: 2020-05-29T16:08:58.421Z,
      updatedAt: 2020-05-29T16:08:58.421Z,
      email: 'glorious-admin-000000@test.com',
      uuid: '123-123-123-123',
      joinedTeamAt: 2020-05-29T17:08:58.421Z,
      teamRoleId: 2
    },
    User {
      id: 2,
      roleId: 2,
      deletedAt: null,
      createdAt: 2020-06-05T11:41:26.867Z,
      updatedAt: 2020-06-05T11:41:26.867Z,
      email: 'blah',
      uuid: 'bfb76150-dae5-4259-953c-fdef42caeaf4',
      joinedTeamAt: 2020-06-05T12:41:26.867Z,
      teamRoleId: 3,
    }
  ]
}
```

My current query pattern looks like this
```javascript
await Team.query().findById(1).withGraphJoined('users')
```

I've added a select using the `users_join` that gets created, but that appends to the Team object, instead of the individual users.
```javascript
 await Team.query().findById(1).withGraphJoined('users').select('*', 'users_join.createdAt AS joinedAt')
```
That unfortunately returns a response like this, only fetching the information about the first user, and appending the information to the team instead of the user.
```javascript
Team {
  id: 1,
  name: 'test',
  isPersonal: false,
  deletedAt: null,
  createdAt: 2020-05-29T16:08:58.423Z,
  updatedAt: 2020-05-29T16:08:58.423Z,
  teamId: 1,
  userId: 1,
  userRoleId: 1,
  roleId: 1,
  email: 'glorious-admin-000000@test.com',
  uuid: '123-123-123-123',
  joinedAt: 2020-05-29T16:08:58.424Z,
  users: [
    User {
      id: 1,
      roleId: 1,
      deletedAt: null,
      createdAt: 2020-05-29T16:08:58.421Z,
      updatedAt: 2020-05-29T16:08:58.421Z,
      email: 'glorious-admin-000000@test.com',
      uuid: '123-123-123-123'
    },
    User {
      id: 2,
      roleId: 2,
      deletedAt: null,
      createdAt: 2020-06-05T11:41:26.867Z,
      updatedAt: 2020-06-05T11:41:26.867Z,
      email: 'blah',
      uuid: 'bfb76150-dae5-4259-953c-fdef42caeaf4'
    }
  ]
}
```

Is there a simple way to do this without having to make a separate query to the join table?

**Comment by koskimas** [comment]
The feature your are looking for is **extra properties**. See [this recipe](https://vincit.github.io/objection.js/recipes/extra-properties.html#join-table-extra-properties).

**Comment by jonnyom** [comment]
Thanks for the quick response @koskimas that works well, but for the `createdAt` column on my join table, I'm getting
```javascript
Uncaught TypeError: Cannot read property 'getColumnForColumnAlias' of undefined
    at Function.create (/Users/jonathanomahony/ev/api/node_modules/objection/lib/queryBuilder/join/JoinResultColumn.js:16:23)
    at /Users/jonathanomahony/ev/api/node_modules/objection/lib/queryBuilder/join/JoinResultParser.js:98:24
    at Array.map (<anonymous>)
    at JoinResultParser._createColumns (/Users/jonathanomahony/ev/api/node_modules/objection/lib/queryBuilder/join/JoinResultParser.js:97:38)
    at JoinResultParser.parse (/Users/jonathanomahony/ev/api/node_modules/objection/lib/queryBuilder/join/JoinResultParser.js:25:36)
    at RelationJoiner.parseResult (/Users/jonathanomahony/ev/api/node_modules/objection/lib/queryBuilder/join/RelationJoiner.js:90:19)
    at JoinEagerOperation.onRawResult (/Users/jonathanomahony/ev/api/node_modules/objection/lib/queryBuilder/operations/eager/JoinEagerOperation.js:39:24)
    at QueryBuilder.callAsyncOperationMethod (/Users/jonathanomahony/ev/api/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:365:39)
```

I've defined it like this, is there something I'm missing?
```javascript
users: {
        relation: Model.ManyToManyRelation,
        modelClass: User,
        join: {
          from: 'teams.id',
          through: {
            from: 'teamsToUsers.teamId',
            to: 'teamsToUsers.userId',
            extra: ['createdAt AS joinedTeamAt', 'userRoleId'],
          },
          to: 'users.id',
        },
      },
```

**Comment by jonnyom** [comment]
@koskimas quick bump on this, appreciate you're busy but would love to know if this is an actual bug, or if this is a clear case of PEBKAC.

**Comment by koskimas** [comment]
Not a bug. `createdAt AS joinedTeamAt` is definitely not a column name.

**Comment by koskimas** [comment]
There's no recipe that says you can use raw SQL statements or `as` in a a column name. You can provide an object:

```js
{
  userRoleId: 'teamRoleId'
}
```

**Comment by jonnyom** [comment]
Ah amazing, that is so much clearer. Thanks!
