### ISSUE TITLE
Insert strange behaviour

### ISSUE THREAD

**Issue by frenzymind** [Vincit/objection.js#1799]
I get some issue with insert query builder operation:
I have model:

```
module.exports = class extends Model {
  constructor(task) {
    super();
      this.phone_number = task.phone_number;
      this.task_status = task.task_status;
      this.error = task.error;
      this.call_status = task.call_status;
      this.voice_length = task.voice_length;
      this.drop_time = task.drop_time;
      this.call_time = task.call_time;
  }

  static get tableName() {
    return 'archive';
  }
};
```

task here is model instance. Then I go through tasks array and do this:

```
await Task.transaction(async trx => {
      const arch = new Archive(task);

      await arch
        .$query(trx)
        .insert()
        .catch(err => {
          console.log(err);
        });

      await task.$query(trx).delete();
    });
```

**I expect:** New record in archive table and deleted record from task table.

**What I get:**

As far as I create arch as instance of Archive class (I log it and see all fields are there from task), I want to insert it and call insert and get error:
```

TypeError: Cannot read property 'phone_number' of undefined
    at new module.exports (/opt/node_app/app/models/Archive.js:8:30)
    at columnNameToPropertyName (/opt/node_app/node_modules/objection/lib/model/modelColPropMap.js:6:17)
    at Function.columnNameToPropertyName (/opt/node_app/node_modules/objection/lib/model/Model.js:432:22)
    at /opt/node_app/node_modules/objection/lib/relations/RelationProperty.js:191:29
    at Array.map (<anonymous>)
    at createPaths (/opt/node_app/node_modules/objection/lib/relations/RelationProperty.js:180:15)
    at new RelationProperty (/opt/node_app/node_modules/objection/lib/relations/RelationProperty.js:36:19)
    at getIdRelationProperty (/opt/node_app/node_modules/objection/lib/model/Model.js:882:10)
    at cachedGet (/opt/node_app/node_modules/objection/lib/model/Model.js:861:61)
    at Function.getIdRelationProperty (/opt/node_app/node_modules/objection/lib/model/Model.js:456:12)
    at Function.getIdPropertyArray (/opt/node_app/node_modules/objection/lib/model/Model.js:464:17)
    at Function.getIdProperty (/opt/node_app/node_modules/objection/lib/model/Model.js:468:26)
    at getId (/opt/node_app/node_modules/objection/lib/model/modelId.js:49:36)
    at getSetId (/opt/node_app/node_modules/objection/lib/model/modelId.js:7:12)
    at module.exports.$id (/opt/node_app/node_modules/objection/lib/model/Model.js:51:12)
    at InstanceInsertOperation.onAfter1 (/opt/node_app/node_modules/objection/lib/queryBuilder/operations/InsertOperation.js:67:20)
```

BUT, transaction is complete: I see created record in archive table with right values and my task record deleted.

**Question:**
It seems objection create archive again somewhere without task argument, but why ? Here is already archive instance. And more wonder that transaction complete well, so that creation doesn't matter ?
Can you explain this behaviour ? Or I think wrong some where.

p.s. I add check if statement in Archive constructor and error gone.

**Comment by koskimas** [comment]
You shouldn't use constructors with objection models. That's probably not made clear enough by the documentation. Instead you should call the static `fromJson` method. You can create a static creator function that does the things you now do in the constructor and calls the `fromJson` method to create the instance.
