### ISSUE TITLE
targetValue.replace is not a function when trying to use insertGraph

### ISSUE THREAD

**Issue by helixion** [Vincit/objection.js#1808]
"knex": "^0.20.13",
"objection": "^2.1.3",
"pg": "^7.18.2",
"pg-range": "^1.1.0",

node version 12.16.1

Problem: Using "#id" and "#ref{}" results in an error of targetValue.replace is not a function while trying to use insertGraph.

Models (I'm using module alias to keep my module paths sane):

```
"use strict";
const Base = require("$base");

class Form extends Base {
  static get tableName() {
    return "forms";
  }

  static get jsonSchema() {
    return {
      type: "object",
      properties: {
        id: { type: "integer" },
        category_id: { type: "integer" },
        name: { type: "string " },
        created_at: { type: "string" },
        updated_at: { type: "string" },
      },
    };
  }

  static get relationMappings() {
    const Field = require("$models/Field");
    const FormField = require("$models/FormFields");
    return {
     
      fields: {
        relation: Base.ManyToManyRelation,
        modelClass: Field,
        join: {
          from: "forms.id",
          through: {
            from: "form_fields.form_id",
            to: "form_fields.field_id",
          },
          to: "fields.id",
        },
      },
    };
  }
}

module.exports = Form;

```

```
const { Model } = require("objection");
class Field extends Model {
  static get tableName() {
    return "fields";
  }

  static get jsonSchema() {
    return {
      type: "object",
      properties: {
        id: { type: "integer" },

        value: { type: "string" },
        type: { type: "string" },
        optional: { type: "boolean" },
      },
    };
  }

  static get relationMappings() {
    const FieldOptions = require("$models/FieldOptions");
    const FormFields = require("$models/FormFields");
    return {
      form: {
        relation: Model.HasOneRelation,
        modelClass: FormFields,
        join: {
          from: "fields.id",
          to: "form_fields.field_id",
        },
      },
      options: {
        relation: Model.HasManyRelation,
        modelClass: FieldOptions,
        join: {
          from: "fields.id",
          to: "form_field_children.field_parent_id",
        },
      },
    };
  }
}

module.exports = Field;

```

```
"use strict";
const { Model } = require("objection");
class FormField extends Model {
  static get tableName() {
    return "form_fields";
  }

  static get jsonSchema() {
    return {
      type: "object",
      properties: {
        form_id: { type: "integer" },
        field_id: { type: "integer" },
      },
    };
  }
}

module.exports = FormField;

```

```
"use strict";
const { Model } = require("objection");
class FieldOption extends Model {
  static get tableName() {
    return "form_fields_children";
  }

  static get jsonSchema() {
    return {
      type: "object",
      properties: {
        id: { type: "integer" },
        field_parent_id: { type: "integer" },
        value: { type: "string" },
      },
    };
  }
}

module.exports = FieldOption;

```
The insertGraph function
```
const insertFn = (form, fields) => {
  return {
    "#id": "form",
    ...form,
    fields: fields.map((field, idx) => {
      const { options, ..._field } = field;
      const parent = "field" + idx;
      const result = {
        "#id": parent,
        ..._field,
        form: {
          form_id: "#ref{form.id}",
          field_id: "#ref{" + parent + ".id}",
        },
      };

      if (options && options.length) {
        const opts = options.map((o) => ({
          field_parent_id: "#ref{" + parent + ".id}",
          value: o.value,
        }));

        Object.assign(result, { options: opts });
      }

      return result;
    }),
  };
};
```

the payload:
```
{
  form: { name: '' },
  fields: [ { value: 'Test', type: 'textfield', optional: true, options: [] } ]
}
```

the route:
```
const addForm = async function (req, res, next) {
  const { form, fields } = req.body;

  try {
    const result = await Form.query()
      .insertGraph(insertFn(form, fields), {
        allowRefs: true,
      })
      .returning("*");

    console.log(result);
  } catch (err) {
    console.log(err);
    next(err);
  }
```

the error:
```
TypeError: targetValue.replace is not a function
    at GraphInsertAction._resolvePropertyReferenceNode (/home/cf/node-projects/api-v1/api.blackoutgg.com/node_modules/objection/lib/queryBuilder/graph/insert/GraphInsertAction.js:124:54)
    at GraphInsertAction._resolveDependency (/home/cf/node-projects/api-v1/api.blackoutgg.com/node_modules/objection/lib/queryBuilder/graph/insert/GraphInsertAction.js:79:12)
    at GraphInsertAction._resolveDependencies (/home/cf/node-projects/api-v1/api.blackoutgg.com/node_modules/objection/lib/queryBuilder/graph/insert/GraphInsertAction.js:69:16)
    at GraphInsertAction._beforeInsert (/home/cf/node-projects/api-v1/api.blackoutgg.com/node_modules/objection/lib/queryBuilder/graph/insert/GraphInsertAction.js:53:10)
    at GraphInsertAction._insertBatch (/home/cf/node-projects/api-v1/api.blackoutgg.com/node_modules/objection/lib/queryBuilder/graph/insert/GraphInsertAction.js:47:16)
    at promiseUtils.map.concurrency.concurrency (/home/cf/node-projects/api-v1/api.blackoutgg.com/node_modules/objection/lib/queryBuilder/graph/insert/GraphInsertAction.js:29:52)
    at mapOne (/home/cf/node-projects/api-v1/api.blackoutgg.com/node_modules/objection/lib/utils/promiseUtils/map.js:23:26)
    at Object.promiseMap [as map] (/home/cf/node-projects/api-v1/api.blackoutgg.com/node_modules/objection/lib/utils/promiseUtils/map.js:11:14)
    at GraphInsertAction.run (/home/cf/node-projects/api-v1/api.blackoutgg.com/node_modules/objection/lib/queryBuilder/graph/insert/GraphInsertAction.js:29:25)
    at /home/cf/node-projects/api-v1/api.blackoutgg.com/node_modules/objection/lib/queryBuilder/graph/GraphUpsert.js:294:52
```

Explanation of what's going on here:
I'm building a form generator. I'm inserting a single form, a form has fields, I have a table which builds a relation between the form and the fields. Each field has a sub field (an option). This is usually when the field is of select, checkbox or multiple type. I have another table which builds a relation between the option and the field.

I use "#id" to reference the form that's being inserted, I also have a "#id" which uses the index of the field to build a reference for the fields when it comes to inserting it into the join table.

**Comment by helixion** [comment]
The solution was to wrap the ref in a while, so #ref{parent.id} became `#{ref${parent}.id}`
