### ISSUE TITLE
"TypeError: key.charAt is not a function" in Model.toJSON

### ISSUE THREAD

**Issue by jeff-kilbride** [Vincit/objection.js#183]
```
TypeError: key.charAt is not a function
    at assignJsonValue (../node_modules/objection/lib/model/ModelBase.js:666:11)
    at ../node_modules/objection/lib/model/ModelBase.js:647:5
    at ../node_modules/objection/node_modules/lodash/lodash.js:4714:15
    at Function.forEach (../node_modules/objection/node_modules/lodash/lodash.js:9011:14)
    at toJsonImpl (../node_modules/objection/lib/model/ModelBase.js:646:20)
    at Video.$$toJson (../node_modules/objection/lib/model/ModelBase.js:430:16)
    at Video.$toJson (../node_modules/objection/lib/model/Model.js:347:19)
    at Video.toJSON (../node_modules/objection/lib/model/ModelBase.js:226:17)
    at Object.stringify (native)
    at ../node_modules/cache-manager-redis/index.js:196:22
    at ../node_modules/cache-manager-redis/index.js:53:7
    at dispense (../node_modules/generic-pool/lib/generic-pool.js:251:16)
    at Object.me.acquire (../node_modules/generic-pool/lib/generic-pool.js:321:5)
    at RedisPool.acquire (../node_modules/sol-redis-pool/index.js:101:14)
    at connect (../node_modules/cache-manager-redis/index.js:42:10)
    at Object.self.set (../node_modules/cache-manager-redis/index.js:192:5)
    at ../node_modules/cache-manager/lib/caching.js:116:32
    at ../node_modules/cache-manager/lib/caching.js:52:21
 key.charAt is not a function

    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)
From previous event:
    at ../node_modules/cache-manager/lib/caching.js:51:18
    at ../node_modules/cache-manager/lib/caching.js:105:17
    at Command.callback (../node_modules/cache-manager-redis/index.js:87:9)
    at normal_reply (../node_modules/redis/index.js:714:21)
    at RedisClient.return_reply (../node_modules/redis/index.js:816:9)
    at JavascriptRedisParser.Parser.returnReply (../node_modules/redis/index.js:188:18)
    at JavascriptRedisParser.execute (../node_modules/redis-parser/lib/parser.js:415:12)
    at Socket.<anonymous> (../node_modules/redis/index.js:267:27)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)
```
I have a model with a `length` property. ModelBase#toJsonImpl() is calling the Lodash `each` function on line 507:
```javascript
  _.each(model, (value, key) => {
    assignJsonValue(json, key, value, omit, pick, omitFromJson, createDbJson);
  });
```
The `each` implementation does not work with objects that include a `length` property. If an object has a `length` property, `each` treats it as an array and returns the wrong type of iterator. (See isArrayLike() @ lodash.js:4706 and lodash.js:11020) This behavior is also mentioned in the [Lodash forEach documentation](https://lodash.com/docs#forEach).

If Model.toJSON always acts on a single model object, as opposed to an array or collection of objects, it may be more appropriate to use either the [Lodash forOwn](https://lodash.com/docs#forOwn) or [Lodash forIn](https://lodash.com/docs#forIn) method to iterate the keys, rather than `each`. I have replaced `each` with `forOwn` on line 646 in the transpiled source and it seems to be working with my models.
```javascript
  _lodash2.default.forOwn(model, function (value, key) {
    assignJsonValue(json, key, value, omit, pick, omitFromJson, createDbJson);
  });
```
However, I see that `each` is being used quite a bit and am wondering if it should be replaced in other areas, too.

Thanks!

**Comment by koskimas** [comment]
This is already fixed in 39cbad7823036a8b09963a41b81e8dc4708ec8da. Not yet released though.
