### ISSUE TITLE
upsertGraph fails to run insert/update instance methods on relations in data

### ISSUE THREAD

**Issue by deconstructionalism** [Vincit/objection.js#1831]
Hi,

## Problem
I am having an issue with `upsertGraph` when used with related tables that have instance methods. I have a model which needs to perform a minor transformation on incoming data before it can commit an insert or update that fits the underlying postgres table schema. The transformations are specified in `$beforeInsert` and `$beforeUpdate` class methods, but it does not seem to occur when data is inserted using the model's `upsertGraph` method, causing the model to throw an error.

## Code
Here is the code the describes the issue. I have provided the related **models**  related through a has many relationship, the **transformation function**,  a JSON representation of **table data**, and some **data insertion code** that should insert new items.

You will notice that the `LineItem` model has some instance methods that should be run before insertion or update and that if this transform were not to occur, the jsonSchema (which matches the postgres table schema exactly) would reject the queries.

### Models
```js
class LineItem extends Model {
  static get tableName () {
    return 'line_items'
  }
  
  $beforeInsert () {
    transformWithMetadata(this)
  }
  
  $beforeUpdate () {
    transformWithMetadata(this)
  }
  
  static get jsonSchema () {
    return {
      type: 'object',
      required: [
        'line_item_type_id',
        'amount'
      ],
      properties: {
        id: { type: 'integer' },
        amount: { type: 'number' },
        line_item_type_id: { type: 'integer' },
        line_item_type_metadata: { type: 'object', default: {} }
      }
    }
  }
  
  static get relationMappings () {
    return {
      line_item_type: {
        relation: Model.BelongsToOneRelation,
        modelClass: __dirname + '/LineItemType.js',
        join: {
          from: 'line_items.line_item_type_id',
          to: 'line_item_types.id'
        }
      }
    }
  }
}

class LineItemType extends Model {
  static get tableName () {
    return 'line_item_types'
  }

  static get jsonSchema () {
    return {
      type: 'object',
      required: [
        'name',
      ],
      properties: {
        id: { type: 'integer' },
        name: { type: 'string' }
      }
    }
  }
  
  static get relationMappings () {
    return {
      line_item_type: {
        relation: Model.HasManyRelation,
        modelClass: __dirname + '/LineItem.js',
        join: {
          from: 'line_item_types.id',
          to: 'line_items.line_item_type_id'
        }
      }
    }
  }
}
```

### Transformation Function
```js
function transformWithMetadata() {
  const { 
    id,
    line_item_type_id,
    ...rest
  } = this
  
  // put all keys other than id and line_item_type_id in line_item_type_metadata
  this.line_item_type_metadata = rest
  
  // delete all keys moved to line_item_type_metadata
  Object.keys(rest)
    .forEach((key) => delete this[key])
}
``` 

### Table Data
```json
{
  "line_items": [
    {
      "id": 1,
      "amount": 20.33,
      "line_item_type_id": 1,
      "line_item_type_metadata": {}
    },
    {
      "id": 2,
      "amount": 40.44,
      "line_item_type_id": 2,
      "line_item_type_metadata": {
        "min": 22.40,
        "max": 60.00
      }
    }
  ],
  "line_item_types": [
    {
      "id": 1,
      "name": "noRange"
    },
    {
      "id": 2,
      "name": "minMaxRange"
    },
    {
      "id": 3,
      "name": "categoryRange"
    }
  ]
}
```

### Data Insertion Code
```js
const insertLineItems = async (lineItems) => {
  const updatedLineItems = await LineItem
    .query()
    .upsertGraph(lineItems)
    
  return updatedLineItems
}

const lineItems = [
  {
    amount: 40.33,
    line_item_type_id: 2,
    min: 0.02,
    max: 500.00
  },
  {
    amount: 10.00,
    line_item_type_id: 3,
    category: 'low cost'
  }
]

insertLineItems(lineItems)
  .then(console.log)
```

### Expected
I would expect that the `$beforeInsert` method would be called for each element in `lineItems`, transforming the data prior to insertion and resulting in returned data such as:

```json
[
  {
    "id": 3,
    "amount": 40.33,
    "line_item_type_id": 2,
    "line_item_type_metadata": {
      "min": 0.02,
      "max": 500.00
    }
  },
  {
    "id": 4,
    "amount": 10.00,
    "line_item_type_id": 3,
    "line_item_type_metadata": {
      "category": "low cost"
    }
  }
]
```

### Received
Instead what I'm getting is something like:

```
DBError: select "line_items"."id", "line_items"."line_item_type_id", "line_items"."amount", "line_items"."min",
"line_items"."max" where "line_items"."id" in ($1) - column line_items.min does not exist
    at wrapError (/Users/arjunray/Projects/AQF/aqf-server/node_modules/db-errors/lib/dbErrors.js:19:14)
    at handleExecuteError (/Users/arjunray/Projects/AQF/aqf-server/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1494:32)
    at QueryBuilder.execute (/Users/arjunray/Projects/AQF/aqf-server/node_modules/objection/lib/queryBuilder/QueryBuilder.js:685:13
```

#### Do you have any idea why `upsertGraph` seems not to be running the `$beforeInsert` method for each incoming data? Thanks in advance!

**Comment by koskimas** [comment]
You are passing `this` as the first argument for the `transformWithMetadata` method. `this` inside the function is NOT the `this` passed as the first argument. You have probably written python before right?

You need to change the function like this:

```js
function transformWithMetadata(self) {
  const { 
    id,
    line_item_type_id,
    ...rest
  } = self
  
  // put all keys other than id and line_item_type_id in line_item_type_metadata
  self.line_item_type_metadata = rest
  
  // delete all keys moved to line_item_type_metadata
  Object.keys(rest)
    .forEach((key) => delete self[key])
}
```

Or optionally call the function like this

```js
  $beforeInsert () {
    transformWithMetadata.call(this)
  }
  
  $beforeUpdate () {
    transformWithMetadata.call(this)
  }
```
