### ISSUE TITLE
Cannot read property 'forClass' of undefined

### ISSUE THREAD

**Issue by nguyentuannhat** [Vincit/objection.js#1969]
Hi,

I have an issue with extends QueryBuilder.
I have some codes:

```
//CustomQueryBuilder.js
const { QueryBuilder } = require('objection');

class CustomQueryBuilder extends QueryBuilder {
  myCustomMethod(something) {
    console.log('CUSTOMIZE QUERY', something);
    return this;
  }
}

export default CustomQueryBuilder;

// BaseModel.js
import { Model, fn } from 'objection';

const { CustomQueryBuilder } = require('./CustomQueryBuilder');

class BaseModel extends Model {

  static get QueryBuilder() {
    return CustomQueryBuilder;
  }
}
export default BaseModel;

// GloEduCert.js
class GloEduCert extends BaseModel {
  static get tableName() {
    return 'edu_certs';
  }
}
export default GloEduCert;
```

when I execute a query with GloEduCert: GloEduCert.query().findById(1);

And I had receive a error

```
"TypeError: Cannot read property 'forClass' of undefined\n    at Function.query (/Applications/MAMP/htdocs/jobvid-api-backend/node_modules/objection/lib/model/Model.js:526:37)\n    at _callee4$ (/Applications/MAMP/htdocs/jobvid-api-backend/src/modules/common/controllers/global.controller.js:89:45)\n    at tryCatch (/Applications/MAMP/htdocs/jobvid-api-backend/node_modules/regenerator-runtime/runtime.js:63:40)\n    at Generator.invoke [as _invoke] (/Applications/MAMP/htdocs/jobvid-api-backend/node_modules/regenerator-runtime/runtime.js:293:22)\n    at Generator.next (/Applications/MAMP/htdocs/jobvid-api-backend/node_modules/regenerator-runtime/runtime.js:118:21)\n    at asyncGeneratorStep (/Applications/MAMP/htdocs/jobvid-api-backend/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)\n    at _next (/Applications/MAMP/htdocs/jobvid-api-backend/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)\n    at /Applications/MAMP/htdocs/jobvid-api-backend/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at /Applications/MAMP/htdocs/jobvid-api-backend/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12\n    at /Applications/MAMP/htdocs/jobvid-api-backend/src/modules/common/controllers/global.controller.js:86:1\n    at Layer.handle [as handle_request] (/Applications/MAMP/htdocs/jobvid-api-backend/node_modules/express/lib/router/layer.js:95:5)\n    at next (/Applications/MAMP/htdocs/jobvid-api-backend/node_modules/express/lib/router/route.js:137:13)\n    at /Applications/MAMP/htdocs/jobvid-api-backend/node_modules/express-validation/lib/index.js:31:18"
```

**Comment by koskimas** [comment]
You are exporting default but importing named. Your imports are undefined.

**Comment by koskimas** [comment]
```js
//CustomQueryBuilder.js
const { QueryBuilder } = require('objection');

class CustomQueryBuilder extends QueryBuilder {
  myCustomMethod(something) {
    console.log('CUSTOMIZE QUERY', something);
    return this;
  }
}

export default CustomQueryBuilder;

// BaseModel.js
import { Model, fn } from 'objection';
import { CustomQueryBuilder } from './CustomQueryBuilder';

class BaseModel extends Model {

  static get QueryBuilder() {
    return CustomQueryBuilder;
  }
}
expor BaseModel;

// GloEduCert.js
import { BaseModel } from 'BaseModel.js';

class GloEduCert extends BaseModel {
  static get tableName() {
    return 'edu_certs';
  }
}
export default GloEduCert;
```
