### ISSUE TITLE
How to properly do Many to Many relationship between two tables and a junction table

### ISSUE THREAD

**Issue by devYusuf** [Vincit/objection.js#2004]
Hi devs.

I'm having issues specifying the many to many relations between two tables and a junction table.
I have a many to many relationship between my users table and my companies table and my junction table is users_companies

So whenever I tried to query through the users table it works fine but when I query through the companies table it throws error.

This is how my User model looks like:
```ts
class User extends Model {
    static tableName = "users";

    static relationMappings = {
        companies: {
            relation: Model.ManyToManyRelation,
            modelClass: Company,
            join: {
                from: "users.id",
                to: "companies.id",
                through: {
                    from: "users_companies.user_id",
                    to: "users_companies.company_id"
                }
            }
        }
    }
}
```

My Company Model:
```ts
class Company extends Model {
    static tableName = "companies";

    static relationMappings = {
        users: {
            relation: Model.ManyToManyRelation,
            modelClass: User,
            join: {
                from: "companies.id",
                to: "users.id",
                through: {
                    from: "users_companies.company_id",
                    to: "users_companies.user_id"
                }
            }
        }
    }
}
```

The junction table:
```ts
class UserCompany extends Model {
    static tableName = "users_companies";
}
```

The cause of the problem:
If I try to run query through the users table, it works fine:
```ts
let user = User.query().findById(id)
user = user.$relatedQuery('companies')
```

But if I try via the companies table, I get errors:
```ts
let company = Company.query().findById(id)
company = company.$relatedQuery('users')
```

Please help!!!

**Comment by devYusuf** [comment]
@koskimas please do you have anything to say on this?

**Comment by koskimas** [comment]
Please read the instructions on opening an issue. We cannot help you if you don't even tell us what the error is.

**Comment by devYusuf** [comment]
> Please read the instructions on opening an issue. We cannot help you if you don't even tell us what the error is.

I'm sorrr for not specifying the error before, I've updated the issue with the error. 
This is the error
```
Error: Company.relationMappings.users: modelClass is not defined
    at ManyToManyRelation.createError (/home/abdulrahman/Documents/Projects/intercord/backend/node_modules/objection/lib/relations/Relation.js:225:14)
    at Object.createError (/home/abdulrahman/Documents/Projects/intercord/backend/node_modules/objection/lib/relations/Relation.js:44:34)
    at checkRelatedModelClass (/home/abdulrahman/Documents/Projects/intercord/backend/node_modules/objection/lib/relations/Relation.js:268:15)
    at ManyToManyRelation.setMapping (/home/abdulrahman/Documents/Projects/intercord/backend/node_modules/objection/lib/relations/Relation.js:49:11)
    at ManyToManyRelation.setMapping (/home/abdulrahman/Documents/Projects/intercord/backend/node_modules/objection/lib/relations/manyToMany/ManyToManyRelation.js:30:26)
    at Function.getRelationUnsafe (/home/abdulrahman/Documents/Projects/intercord/backend/node_modules/objection/lib/model/Model.js:649:30)
    at Function.getRelation (/home/abdulrahman/Documents/Projects/intercord/backend/node_modules/objection/lib/model/Model.js:656:27)
    at relatedQuery (/home/abdulrahman/Documents/Projects/intercord/backend/node_modules/objection/lib/model/Model.js:817:31)
    at Company.$relatedQuery (/home/abdulrahman/Documents/Projects/intercord/backend/node_modules/objection/lib/model/Model.js:74:12)
    at GetCompany.main (/home/abdulrahman/Documents/Projects/intercord/backend/src/modules/companies/services/get-company.service.ts:16:22)
```
I don't understand why its saying that modelClass is undefined, even though I imported the model and specified the property

**Comment by koskimas** [comment]
You have a circular depency. Company imports user and User imports company. If you are using typescript or babel, you can fix that by making the `relationMappings` a getter or a method. If you are using raw node you need to also move the `require` statements inside the `relationMappings` getter/method.
