### ISSUE TITLE
Having trouble with related subquery, count, and where 

### ISSUE THREAD

**Issue by Brando753** [Vincit/objection.js#2020]
I have tried a few ways to do this but have been unsuccessful. I have two tables one is Person the other is Animal, the Person has a HasManyRelation of Animals. I want to query all People who have more than one animal but less than three. I built the following query:
```js
  const petOwners = await Person.query()
    .select(
      "Person.*",
      Person.relatedQuery('pets')
        .count()
        .as('petCount')
    )
    .where('petCount', '<', 3)
    .where('petCount', '>=', 1)
```

And it works as expected in Sqlite3! However in postgresql it throws an exception:
```
DBError: select "Person".*, (select count(*) from "Animal" as "pets" where "pets"."ownerId" = "Person"."id") as "petCount" from "Person" where "petCount" < $1 and "petCount" >= $2 - column "petCount" does not exist
    at wrapError (/home/anderson/sandbox/objectionTest/node_modules/db-errors/lib/dbErrors.js:19:14)
    at handleExecuteError (/home/anderson/sandbox/objectionTest/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1489:32)
    at QueryBuilder.execute (/home/anderson/sandbox/objectionTest/node_modules/objection/lib/queryBuilder/QueryBuilder.js:670:20)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  nativeError: error: select "Person".*, (select count(*) from "Animal" as "pets" where "pets"."ownerId" = "Person"."id") as "petCount" from "Person" where "petCount" < $1 and "petCount" >= $2 - column "petCount" does not exist
      at Parser.parseErrorMessage (/home/anderson/sandbox/objectionTest/node_modules/pg-protocol/dist/parser.js:278:15)
      at Parser.handlePacket (/home/anderson/sandbox/objectionTest/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/home/anderson/sandbox/objectionTest/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/home/anderson/sandbox/objectionTest/node_modules/pg-protocol/dist/index.js:10:42)
      at Socket.emit (events.js:314:20)
      at addChunk (_stream_readable.js:298:12)
      at readableAddChunk (_stream_readable.js:273:9)
      at Socket.Readable.push (_stream_readable.js:214:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
    length: 109,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '135',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3284',
    routine: 'errorMissingColumn'
  },
  client: 'postgres'
}
```

I have included a Minimal example that works in Sqlite3 but does not work with Postgresql. (Rename it from .txt to .js) Is this a bug, or is the above query just not compatible with postgresql? If so whats the proper way to write it?

**Comment by Brando753** [comment]
[test.txt](https://github.com/Vincit/objection.js/files/6177925/test.txt)
Minimal Test file. Rename to .js

**Comment by Brando753** [comment]
I want to thank @koskimas for explaning this in Gitter very shortly after I posted this issue. I am documenting in case anyone else is looking how to properly do this:

```
  // NOTE: Don't `await` this. This will be compiled as a subquery.
  const subquery = Person.query()
    .select(
      "Person.*",
      Person.relatedQuery('pets')
        .count()
        .as('petCount')
    ).as('petsSubQuery');

  const petOwners = await Person.query()
    .from(subquery)
    .where('petCount', '>=', 1)
    .where('petCount', '<', 3);
```
