### ISSUE TITLE
Error with insertGraph

### ISSUE THREAD

**Issue by gaetansenn** [Vincit/objection.js#2128]
Hello,

I have an issue with the `insertGraph` method.

```js
TypeError: targetValue.replace is not a function
    at GraphInsertAction._resolvePropertyReferenceNode (/Users/gaetansenn/Development/dewib/clients/useradgents/argos/api/node_modules/objection/lib/queryBuilder/graph/insert/GraphInsertAction.js:124:54)
    at GraphInsertAction._resolveDependency (/Users/gaetansenn/Development/dewib/clients/useradgents/argos/api/node_modules/objection/lib/queryBuilder/graph/insert/GraphInsertAction.js:79:12)
    at GraphInsertAction._resolveDependencies (/Users/gaetansenn/Development/dewib/clients/useradgents/argos/api/node_modules/objection/lib/queryBuilder/graph/insert/GraphInsertAction.js:69:16)
    at GraphInsertAction._beforeInsert (/Users/gaetansenn/Development/dewib/clients/useradgents/argos/api/node_modules/objection/lib/queryBuilder/graph/insert/GraphInsertAction.js:53:10)
    at GraphInsertAction._insertBatch (/Users/gaetansenn/Development/dewib/clients/useradgents/argos/api/node_modules/objection/lib/queryBuilder/graph/insert/GraphInsertAction.js:47:16)
    at promiseUtils.map.concurrency.concurrency (/Users/gaetansenn/Development/dewib/clients/useradgents/argos/api/node_modules/objection/lib/queryBuilder/graph/insert/GraphInsertAction.js:29:54)
    at mapOne (/Users/gaetansenn/Development/dewib/clients/useradgents/argos/api/node_modules/objection/lib/utils/promiseUtils/map.js:23:26)
    at Object.promiseMap [as map] (/Users/gaetansenn/Development/dewib/clients/useradgents/argos/api/node_modules/objection/lib/utils/promiseUtils/map.js:11:14)
    at GraphInsertAction.run (/Users/gaetansenn/Development/dewib/clients/useradgents/argos/api/node_modules/objection/lib/queryBuilder/graph/insert/GraphInsertAction.js:29:25)
    at /Users/gaetansenn/Development/dewib/clients/useradgents/argos/api/node_modules/objection/lib/queryBuilder/graph/GraphUpsert.js:294:52
```

This is what I have from the GraphInsertAction.js logs
https://gist.github.com/gaetansenn/5024ff6321daec8537a21d2f303ff108

And here what i'm trying to insert
https://gist.github.com/gaetansenn/2436438b1fd8f88e16d2a66cf64ccc7a

The problem comes from the slot id ref from entities
"slotId":"#ref{slot0.id}"

I had to add the reference because the slotId was not inserted from childrens entities.
Has I can see in your code your only go up from one level maybe the solution will be to get parent node until find the good node ?

Here the modelClass of EventEntity:
```ts
export class EventEntity extends mixin(Model, [
  DateObjectionMixin,
  VersioningMixin,
]) {
  static tableName = 'event_entities';

  id: number;

  @IsString()
  name: string;

  @IsText()
  description: string;

  @IsString()
  mobility: EventEntityMobility;

  @IsString()
  type: EventEntityFixType | EventEntityMobileType;

  @IsString()
  status: EventEntityMobileStatus | EventEntityFixStatus;

  @IsInteger()
  capacity: number;

  @IsInteger()
  parentId: number;

  @IsInteger()
  slotId: number;

  @IsInteger()
  targetPositionId: number;

  @IsInteger()
  currentPositionId: number;

  slot: EventSlot;

  static get relationMappings() {
    return {
      // eslint-disable-next-line
      // @ts-ignore
      ...super.relationMappings,
      parent: {
        relation: Model.HasOneRelation,
        modelClass: EventEntity,
        join: {
          from: 'event_entities.parentId',
          to: 'event_entities.id',
        },
      },
      entities: {
        relation: Model.HasManyRelation,
        modelClass: EventEntity,
        join: {
          from: 'event_entities.id',
          to: 'event_entities.parentId',
        },
      },
      slot: {
        relation: Model.BelongsToOneRelation,
        modelClass: EventSlot,
        join: {
          from: 'event_entities.slotId',
          to: 'event_slots.id',
        },
      },
      targetPosition: {
        relation: Model.BelongsToOneRelation,
        modelClass: EventPosition,
        join: {
          from: 'event_entities.targetPositionId',
          to: 'event_positions.id',
        },
      },
      currentPosition: {
        relation: Model.BelongsToOneRelation,
        modelClass: EventPosition,
        join: {
          from: 'event_entities.currentPositionId',
          to: 'event_positions.id',
        },
      },
      vehicles: {
        relation: Model.ManyToManyRelation,
        modelClass: Vehicle,
        join: {
          from: 'event_entities.id',
          through: {
            modelClass: EventEntityVehicle,
            from: 'event_entities_vehicles.entityId',
            to: 'event_entities_vehicles.vehicleId',
          },
          to: 'vehicles.id',
        },
      },
      persons: {
        relation: Model.ManyToManyRelation,
        modelClass: EventPerson,
        join: {
          from: 'event_entities.id',
          through: {
            modelClass: EventEntityPerson,
            from: 'event_entities_persons.entityId',
            to: 'event_entities_persons.personId',
          },
          to: 'event_persons.id',
        },
      },
      equipments: {
        relation: Model.ManyToManyRelation,
        modelClass: Equipment,
        join: {
          from: 'event_entities.id',
          through: {
            modelClass: EventEntityEquipment,
            from: 'event_entities_equipments.entityId',
            to: 'event_entities_equipments.equipmentId',
          },
          to: 'equipments.id',
        },
      },
    };
  }
}
```

**Comment by koskimas** [comment]
Way too complex to debug. Would take me a full day.

**Comment by gaetansenn** [comment]
If I provide to you a simple example from your template can you try to find the bug ? As I said it look like the problem come from insertion of children's of children's. It's really important to me to fix it as if not I will have to change all my code 😢
