### ISSUE TITLE
Typescript version: Unexpected token ; examples\koa-ts\dist\models\Person.js:10  id;

### ISSUE THREAD

**Issue by hs-dev-web** [Vincit/objection.js#2151]
After cloning the repo, I run "npm install", and then run "npm start"

At this point I got this error:

```
examples\koa-ts\dist\models\Person.js:10
    id;
      ^

SyntaxError: Unexpected token ;
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\LearnObjectionJs\examples\koa-ts\dist\api.js:6:34)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

this is the compiled javascript:

```
class Person extends objection_1.Model {
    id; // ----> this is the line 10 which mentioned in the error above
    firstName;
    lastName;
    age;
    pets;
    movies;
    children;
    parent;
...
...
...
}
```

**Comment by kibertoad** [comment]
Which TS version? Which knex and objection versions?

**Comment by hs-dev-web** [comment]
this is the default package.json inside koa-ts folder:

```
"dependencies": {
    "axios": "^0.19.0",
    "knex": "^0.95.13",
    "koa": "^2.11.0",
    "koa-bodyparser": "^4.2.1",
    "koa-router": "^7.4.0",
    "objection": "^3.0.0-rc.4",
    "sqlite3": "^5.0.2"
  },
  "devDependencies": {
    "@types/koa": "^2.11.0",
    "@types/koa-bodyparser": "^4.3.0",
    "@types/koa-router": "^7.0.42",
    "typescript": "4.4.4"
  }
```

and after run "npm install" this is the installed ones inside node_modules folder:

```
"typescript": "4.4.4"
"knex": "0.95.14"
"objection": "3.0.0"
```

**Comment by hs-dev-web** [comment]
Ok I suppose this is because my installed Nodejs version doesn't support "esnext".

when I change the target setting to ES2018 

`"target": "ES2018",`

it works... thanks.

**Comment by koskimas** [comment]
Objection only supports node.js 12 and above.
