### ISSUE TITLE
Update operation fails when using knex.raw expression

### ISSUE THREAD

**Issue by kratos-42** [Vincit/objection.js#2225]
I'm trying to upsert a field on a `jsonb` column by providing a `knex.raw` expression as follow:

```js
const metadata = `jsonb_set(metadata, '{date}', '"2001-01-01T00:00:00.000Z"')`;

await model.query().patchAndFetchById(id, { metadata: knex.raw(metadata) });
```

**Expected:**
`metadata.date` to be set to `'2001-01-01T00:00:00.000Z'`, as it did with previous versions.

**Observed:**
```
TypeError: Converting circular structure to JSON
        --> starting at object with constructor 'Timeout'
        |     property '_idlePrev' -> object with constructor 'TimersList'
        --- property '_idleNext' closes the circle
        at JSON.stringify (<anonymous>)

at formatJsonAttributes (.../node_modules/objection/lib/model/modelJsonAttributes.js:39:27)
at TransactionModel.$formatDatabaseJson (.../node_modules/objection/lib/model/Model.js:110:12)
at toDatabaseJson (.../node_modules/objection/lib/model/modelToJson.js:39:16)
at TransactionModel.$toDatabaseJson (.../node_modules/objection/lib/model/Model.js:156:12)
at UpdateOperation.onBefore3 (.../node_modules/objection/lib/queryBuilder/operations/UpdateOperation.js:31:28)
at UpdateAndFetchOperation.onBefore3 (.../node_modules/objection/lib/queryBuilder/operations/DelegateOperation.js:39:26)
at QueryBuilder.callAsyncOperationMethod (.../node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:387:39)
at .../node_modules/objection/lib/queryBuilder/QueryBuilder.js:1143:19
```

**Versions:**
`Objection: 3.1.0`
`Knex: 1.0.3`
`Node: 16.14.0`

If you need any other information, please let me know.
Thanks.

**Comment by koskimas** [comment]
You metadata object contains circular references.
