### ISSUE TITLE
Cannot read property 'columns' of undefined when using Model.JoinEagerAlgorithm

### ISSUE THREAD

**Issue by ssljivic** [Vincit/objection.js#320]
When I use Model.JoinEagerAlgorithm in objection@0.7.0-rc.3:

```
User
  .query()
  .eagerAlgorithm(Model.JoinEagerAlgorithm)
  .eager('pet');
```

I am getting error:

```
TypeError: Cannot read property 'columns' of undefined
    at JoinEagerOperation.buildSelects (node_modules\objection\lib\queryBuilder\operations\JoinEagerOperation.js:354:37)
    at JoinEagerOperation.build (node_modules\objection\lib\queryBuilder\operations\JoinEagerOperation.js:258:10)
    at JoinEagerOperation.onBeforeBuild (node_modules\objection\lib\queryBuilder\operations\JoinEagerOperation.js:113:10)
    at QueryBuilder.buildInto (node_modules\objection\lib\queryBuilder\QueryBuilderOperationSupport.js:316:10)
    at _build (node_modules\objection\lib\queryBuilder\QueryBuilder.js:1389:25)
    at QueryBuilder.build (node_modules\objection\lib\queryBuilder\QueryBuilder.js:740:23)
    at QueryBuilder.toString (node_modules\objection\lib\queryBuilder\QueryBuilder.js:508:17)
    at QueryBuilder.toSql (node_modules\objection\lib\queryBuilder\QueryBuilder.js:517:17)
```

user.ts:
```
import * as objection from 'objection';

export default class User extends objection.Model {
  static tableName = 'user';

  static relationMappings = {
    pets: {
      relation: objection.Model.HasManyRelation,
      modelClass: __dirname + '/pet',
      join: {
        from: 'User.id',
        to: 'Pet.user_id'
      }
    }
  };
}
```

pet.ts:
```
import * as objection from 'objection';

export default class Pet extends objection.Model {
  static tableName = 'pet';

  static relationMappings = {
    owner: {
      relation: objection.Model.BelongsToOneRelation,
      modelClass: __dirname + '/user',
      join: {
        from: 'Pet.user_id',
        to: 'User.id'
      }
    }
  };
}

```

Any help would be appreciated.

**Comment by fl0w** [comment]
In your mappings, you've defined:
```js
join: {
  from: 'Pet.user_id',
  to: 'User.id'
}
```

But according to your `tableName` it's lower case. The examples in docs assume you have uppercased table names.

**Comment by ssljivic** [comment]
@fl0w that was a typo. With proper casing it still returns the error. Without JoinEagerAlgorithm query works.

With JoinEagerAlgorithm the error is located here:

```
objection\lib\queryBuilder\operations\JoinEagerOperation.js:354
    columnInfo[modelClass.tableName].columns.forEach(function (col) {

TypeError: Cannot read property 'columns' of undefined
```

**Comment by ssljivic** [comment]
@koskimas, from I could see it looks like `JoinEagerOperation.prototype.onBeforeInternal` is never called, therefore `columnInfo` is not populated.

**Comment by koskimas** [comment]
@ssljivic In all my tests `onBeforeInternal` is called correctly. Can you create a small sample program or a test in objection test suite that reproduces the problem as I am unable to reproduce it. What database are you using?

**Comment by ssljivic** [comment]
@koskimas, I deleted node_modules and `npm install`-ed again and now it works. Sorry for confusion.
