### ISSUE TITLE
Error: Post.relationMappings.author: join: either `from` or `to` must point to the owner model table.

### ISSUE THREAD

**Issue by helixion** [Vincit/objection.js#414]
I'm trying to do fetch a relation using eager, however I get the following error:
```
Error: Post.relationMappings.author: join: either `from` or `to` must point to the owner model table.
    at BelongsToOneRelation.createError (/home/michael/Projects/vue-projects/bis-server/node_modules/objection/lib/relations/Relation.js:362:14)
    at BelongsToOneRelation.setMapping (/home/michael/Projects/vue-projects/bis-server/node_modules/objection/lib/relations/Relation.js:90:18)
    at Object.keys.reduce (/home/michael/Projects/vue-projects/bis-server/node_modules/objection/lib/model/Model.js:574:33)
    at Array.reduce (native)
    at Function.getRelations (/home/michael/Projects/vue-projects/bis-server/node_modules/objection/lib/model/Model.js:571:61)
    at WhereInEagerOperation.call (/home/michael/Projects/vue-projects/bis-server/node_modules/objection/lib/queryBuilder/operations/eager/WhereInEagerOperation.js:44:34)
    at QueryBuilder.callQueryBuilderOperation (/home/michael/Projects/vue-projects/bis-server/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:142:19)
    at callEagerFetchOperation (/home/michael/Projects/vue-projects/bis-server/node_modules/objection/lib/queryBuilder/QueryBuilder.js:902:13)
    at QueryBuilder.execute (/home/michael/Projects/vue-projects/bis-server/node_modules/objection/lib/queryBuilder/QueryBuilder.js:439:7)
    at QueryBuilder.then (/home/michael/Projects/vue-projects/bis-server/node_modules/objection/lib/queryBuilder/QueryBuilder.js:347:26)
    at fetchAll (/home/michael/Projects/vue-projects/bis-server/routes/v2/posts.js:8:3)
    at Layer.handle [as handle_request] (/home/michael/Projects/vue-projects/bis-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/michael/Projects/vue-projects/bis-server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/michael/Projects/vue-projects/bis-server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/michael/Projects/vue-projects/bis-server/node_modules/express/lib/router/layer.js:95:5)
    at /home/michael/Projects/vue-projects/bis-server/node_modules/express/lib/router/index.js:281:22

```
My post model relationshipmapping is as follows:
```
static get relationMappings() {
		return {
			author: {
				relation: Model.BelongsToOneRelation,
				modelClass: __dirname + '/User',
				join: {
					from: 'Post.user_id',
					to: 'User.id'
				}
			},
			comments: {
				relation: Model.BelongsToManyRelation,
				modelClass: __dirname + '/Comments',
				join: {
					from: 'Post.id',
					through: {
						from: 'Posts_Comments.post_id',
						to: 'Posts_Comments.comments_id'
					},
					to: 'Comments.id'
				}
			}
		}
	}

```
What exactly am I doing wrong?

**Comment by helixion** [comment]
Solved it.
