### ISSUE TITLE
Advice on integration testing and how to manually rollback transaction

### ISSUE THREAD

**Issue by dcominottim** [Vincit/objection.js#437]
I am trying to create some integration tests and I need to rollback my transactions after objection's queries complete, just as in

```
it('should be able to persist Notificacao', () => {
      return objection.transaction(Notificacao.knex(), trx => {
          return Notificacao
              .query(trx).insert(notificacao1)
              .then(notificacao => {
                  expect(notificacao).to.include(notificacao1);
                    
                 // trx.rollback() here wouldn't work because objection will call commit and the transaction will be closed already, from what I understood

                 // the following attempt to let objection rollback on its own doesn't work either
                 // return new Promise((resolve, reject) => {
                 //     reject('rollback')
                 //});
              })
      });
});
```

Can someone please offer some advice?

**Comment by newhouse** [comment]
Hmm, based on my experience and the documentation, you should be able to simply do:

```
return objection.transaction(Notificao.knex(), txn => {
  return Notificao
    .query(txn)
    .insert(...)
    ...
    .then(notificao => {
      // Perform assertions
      ...
      // Roll it all back by returning a rejected promise
      return Promise.reject();
    });
});
```

...which is basically what it looks like you are doing already. What exactly are you experiencing as output for your code? Can you log out the value of `txn` to make sure it looks like a transaction object? If it's `undefined` somehow, passing it to query like `query(txn)` will not use a/the transaction.

**Comment by koskimas** [comment]
Your example and what newhouse suggested, should work. You should also be able to use `trx.rollback()`, but in that case you shouldn't return anything from the `transaction` callback. Your problem is probably somewhere else. What does "doesn't work" mean in this case? What happens? Error message? Stack trace? Something?

**Comment by dcominottim** [comment]
Thanks for the replies. However, the suggestion from @newhouse doesn't work; it is equivalent to the last lines I commented out in my original post. By "doesn't work" I mean that in the case of returning a rejected promise, the data is commited anyway; and in the case of manually invoking trx.rollback(), an error is thrown (because the transaction has been closed already when I invoke the method or objection tries to commit the data after that).

```
Error: Transaction query already complete, run with DEBUG=knex:tx for more info
      at completedError (node_modules/knex/lib/transaction.js:299:9)
      at node_modules/knex/lib/transaction.js:273:22
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Function.Promise.attempt.Promise.try (node_modules/bluebird/js/release/method.js:39:29)
      at Client_PG.trxClient.query (node_modules/knex/lib/transaction.js:271:34)
      at Transaction.query (node_modules/knex/lib/transaction.js:156:28)
      at Transaction.commit (node_modules/knex/lib/transaction.js:130:17)
      at Function.transactor.commit (node_modules/knex/lib/transaction.js:232:18)
      at Object.<anonymous> (node_modules/knex/lib/transaction.js:87:31)
      at Object.tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)
```

**Comment by dcominottim** [comment]
My specific test case passes, but that's because it tests the return of the insert query. I only posted my test case in order to show the exact usage of the framework; it passes perfectly even with the rejected promise, because of where the assertion is placed.

I will try to provide a standalone example then, but from what I saw in objection's test suite it only tests against MySQL -- and I am using PostgreSQL.

Either way, if calling rollback() should work, -- as per your own comment, -- but instead throws the error I showed, that is already a problem that should be fixed. What is the purpose of having access to the transaction object if it can't be interacted with?

**Comment by koskimas** [comment]
I'll take a look at the `rollback` method since there are no tests for it. Did you test what I suggested earlier about not returning a promise from the callback when calling `rollback`? Because if you do both, you are using it wrong. You an also see knex documentation about transactions. Objection transaction object is just a knex transaction object.

All tests are ran for sqlite, postgresql and mysql.

**Comment by koskimas** [comment]
I just wrote a test case for the `rollback` method and it works as it should:

```js
    it('should rollback if an error occurs (rollback method)', done => {
      let lastThenCalled = false;

      transaction(Model1.knex(), trx => {

        Model1
          .query(trx)
          .insertGraph([{
            model1Prop1: 'a',
            model1Relation1: {
              model1Prop1: 'b'
            },
            model1Relation2: [{
              model2Prop1: 'c',
              model2Relation1: [{
                model1Prop1: 'd'
              }]
            }]
          }])
          .then(models => {
            return models[0]
              .$relatedQuery('model1Relation2', trx)
              .insert({model2Prop1: 'e'})
              .return(models);
          })
          .then(models => {
            return models[0]
              .$relatedQuery('model1Relation2')
              .transacting(trx)
              .insert({model2Prop1: 'f'})
              .return(models);
          })
          .then(models => {
            expect(models[0].$query(trx).knex() === trx);
          })
          .then(() => {
            lastThenCalled = true;
            trx.rollback(new Error('whoops'));
          });

      }).catch(err => {
        expect(lastThenCalled).to.equal(true);
        expect(err.message).to.equal('whoops');

        return [
          session.knex('Model1'),
          session.knex('model_2'),
          session.knex('Model1Model2')
        ];
      }).spread((rows1, rows2, rows3) => {
        expect(rows1).to.have.length(0);
        expect(rows2).to.have.length(0);
        expect(rows3).to.have.length(0);

        done();
      }).catch(done);

    });
```

**Comment by koskimas** [comment]
Alternatively you __can__ use return if you also return the result from `rollback` since it is an async operation.

```js
    it('should rollback if an error rollback method is called (with return)', done => {
      transaction(Model1.knex(), trx => {

        return Model1
          .query(trx)
          .insertGraph([{
            model1Prop1: 'a',
            model1Relation1: {
              model1Prop1: 'b'
            },
            model1Relation2: [{
              model2Prop1: 'c',
              model2Relation1: [{
                model1Prop1: 'd'
              }]
            }]
          }])
          .then(() => {
            return trx.rollback(new Error('whoops'));
          });

      }).catch(err => {
        expect(err.message).to.equal('whoops');

        return [
          session.knex('Model1'),
          session.knex('model_2'),
          session.knex('Model1Model2')
        ];
      }).spread((rows1, rows2, rows3) => {
        expect(rows1).to.have.length(0);
        expect(rows2).to.have.length(0);
        expect(rows3).to.have.length(0);

        done();
      }).catch(done);
    });
```

**Comment by koskimas** [comment]
@dcominottim Did you solve this? Can I close the issue?

**Comment by dcominottim** [comment]
@koskimas Thanks for your replies. Unfortunately, the problem persists, although I seem to be doing things exactly as in your tests. I am preparing a standalone test case that I intend to show you today or tomorrow at last. I will try to have it ready in a couple hours.

**Comment by dcominottim** [comment]
Done. Please run the `schema.sql `script against your local `objection_test` DB, then `npm install`, place `persistence.test.js` in a `test` folder, and `npm test.` It should result in 

```
1) Persistence... should be able to save Notification and rollback the transaction:
     Error: Transaction query already complete, run with DEBUG=knex:tx for more info

```

https://gist.github.com/dcominottim/8142e68bd0c890012fce63182a7fe495

**Comment by koskimas** [comment]
I just looked at the code and you are not doing the rollback using either of the ways I told that would work. You are using this:

```js
it('should be able to save Notification and rollback the transaction', () => {
  return objection.transaction(Notificacao.knex(), trx => {
    return Notificacao
      .query(trx).insert(notificacao1)
      .then(notificacao => {
        expect(notificacao).to.include(notificacao1);
        trx.rollback(new Error('ok'));
      })
    });
});
```

when you should be doing this:

```js
it('should be able to save Notification and rollback the transaction', () => {
  return objection.transaction(Notificacao.knex(), trx => {
    return Notificacao
      .query(trx).insert(notificacao1)
      .then(notificacao => {
        expect(notificacao).to.include(notificacao1);
        return trx.rollback(new Error('ok'));
      })
    });
});
```

or this:

```js
it('should be able to save Notification and rollback the transaction', () => {
  return objection.transaction(Notificacao.knex(), trx => {
    Notificacao
      .query(trx).insert(notificacao1)
      .then(notificacao => {
        expect(notificacao).to.include(notificacao1);
        trx.rollback(new Error('ok'));
      })
    });
});
```

**Comment by dcominottim** [comment]
Oh, reading the whole discussion again, I definitely misunderstood your explanation about when to return promises. Indeed, both of your last examples do work. Thanks a lot for the great support and library. The issue can be closed.

**Comment by koskimas** [comment]
Great! I probably should document the `rollback` method better.
