### ISSUE TITLE
joinEager doesn't work with table names that contain a postgresql schema

### ISSUE THREAD

**Issue by pineapplemachine** [Vincit/objection.js#439]
I have a query that looks similar to this:

``` js
Thing.query().first().select(
    "thingId", "creationTime", "author.emailAddress"
).joinRelation("author" /* Join on users table */ ).where({
    "thingId": thingId
}).then(thing => doStuff(thing))
```

Both the thing and user tables have a `creationTime` column. When I try to express the query like above I get an error `column reference "creationTime" is ambiguous`.

One solution would be to do this, but I really don't want to because it's verbose and repetitive and I'd have to do it in lots of places. It wouldn't help maintainability at all.

``` js
Thing.query().first().select(
    "thingId", "thingSchemaName.thingTableName.creationTime", "author.emailAddress"
).joinRelation("author" /* Join on users table */ ).where({
    "thingId": thingId
}).then(thing => doStuff(thing))
```

What I would very much like to do and would expect to be able to do - except I haven't worked out any way how - is to select the model table with an alias. Something nice and sensible and readable like

``` js
Thing.query().as("thing").first().select(
    "thing.thingId", "thing.creationTime", "author.emailAddress"
).joinRelation("author" /* Join on users table */ ).where({
    "thing.thingId": thingId
}).then(thing => doStuff(thing))
```

Or, it would be quite nice if objection was able to automagically prepend the models' table name to selected columns that don't otherwise specify.

What's the best way to fix this?

**Comment by koskimas** [comment]
You can use the `alias` method:

```js
Thing.query().alias("thing").first().select(
    "thing.thingId", "thing.creationTime", "author.emailAddress"
).joinRelation("author" /* Join on users table */ ).where({
    "thing.thingId": thingId
}).then(thing => doStuff(thing))
```

**Comment by pineapplemachine** [comment]
This solved the problem, thank you!

**Comment by pineapplemachine** [comment]
I have another question related to the same example actually -

Is it possible to cause the returned object to look something like this or will it be necessary to construct a new object meeting this format from the one acquired by the query?

``` js
{
    thingId: ...,
    creationTime: ...,
    author: {
        emailAddress: ...,
        ...other selected fields of the author relation
    }
}
```

**Comment by koskimas** [comment]
Yes:

```js
Thing.query().alias("thing").first().select(
    "thing.thingId", "thing.creationTime", "author.emailAddress"
).joinEager("author" /* Join on users table */ ).where({
    "thing.thingId": thingId
}).then(thing => doStuff(thing))
```

**Comment by pineapplemachine** [comment]
This didn't work for me - if I use `select("*")` none of the author columns are included in the output and there is no "author" object. If I try to select e.g. "author.emailAddress" it produces an error `missing FROM-clause entry for table "author"`. I'm using objection@0.8.4.

**Comment by koskimas** [comment]
Can you add `.debug()` to the queries and post the generated sql here?

**Comment by koskimas** [comment]
By the way, I think `author` should be a `BelongsToOneRelation` instead of `HasOneRelation` because the source table `Things` has the foreign key.

**Comment by pineapplemachine** [comment]
I made the relation change you suggested, that makes sense - still having the same issue though

In my use case the Things are Questionnaires that Users may create.

Postgres schema: https://pastebin.com/BPtpp5du

Models: https://pastebin.com/EYEgmeVc

The query: https://pastebin.com/YZGuSYiX

Console output:

``` text
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 3, false ],
  __knexQueryUid: '0df096b2-876f-4d1e-a531-42a564cc7c06',
  sql: 'select * from "maptionnaire"."Questionnaires" as "questionnaire" left join "maptionnaire"."MultilingualText" as "title" on "title"."textId" = "questionnaire"."titleTextId" where "questionnaire"."questionnaireId" = ? and "questionnaire"."disabled" = ?' }
Questionnaire {
  questionnaireId: 3,
  name: 'New questionnaire',
  titleTextId: null,
  authorUserId: 6,
  creationTime: 2017-07-11T08:10:18.104Z,
  lastModifiedTime: 2017-07-11T08:10:18.104Z,
  disabled: false,
  textId: null,
  languageCode: null,
  content: null,
  contentOrigin: null,
  title: [] }
```

**Comment by koskimas** [comment]
There might be a bug with using `*` in select with joinEager. I'll look into that. It should work if you leave out the `select`. You never need to say `select('*')` since it's the default.

You seem to have two eager's in your query: `eager` and `joinEager`. The latter overwrites the first. You can simply say `joinEager('[author, title]')`.

**Comment by koskimas** [comment]
This is unrelated, but there is now a `findOne({foo: 'bar'})` method that can be used instead of `where({foo: 'bar'}.first()`.

**Comment by pineapplemachine** [comment]
I rewrote the query as

``` js
    const query = app.db.Questionnaire.first().alias("questionnaire").joinEager("[author, title]").where({
            // TODO: Distinguish between public and private questionnaires.
            // Consider whether a user/respondent has view permission.
            "questionnaire.questionnaireId": request.body.questionnaireId,
            "questionnaire.disabled": false,
        });
```

The resulting object does have an `author` attribute but it's null.

The console output reads:

``` js
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 3, false ],
  __knexQueryUid: '4cdb3ad9-5c06-49ad-8d4d-0cd14302593d',
  sql: 'select "questionnaire".* from "maptionnaire"."Questionnaires" as "questionnaire" left join "maptionnaire"."Users" as "author" on "author"."userId" = "questionnaire"."authorUserId" left join "maptionnaire"."MultilingualText" as "title" on "title"."textId" = "questionnaire"."titleTextId" where "questionnaire"."questionnaireId" = ? and "questionnaire"."disabled" = ?' }
Questionnaire {
  questionnaireId: 3,
  name: 'New questionnaire',
  titleTextId: null,
  authorUserId: 6,
  creationTime: 2017-07-11T08:10:18.104Z,
  lastModifiedTime: 2017-07-11T08:10:18.104Z,
  disabled: false,
  author: null,
  title: [] }
```

If I manually run the query and add `"author".*` to the select statement then I do get the user information I expect; this seems not to be an issue with the User not existing but rather with the query not selecting that data. (The `title` attribute should in fact be an empty list as there are no rows with the corresponding ID.)

**Comment by koskimas** [comment]
That's not the SQL that should be generated. Are you sure that's __exactly__ the query you are running? And you don't have any custom hooks or query builders that add selects or something like that to the query? Where does the `select "questionnaire".*` come from?

**Comment by pineapplemachine** [comment]
Hey, thank you for your help so far - I'm leaving the office for the day but I will return to troubleshooting tomorrow morning around 7:00 AM UTC

**Comment by koskimas** [comment]
I found a bug in `joinEager` when a table name has a schema in it. I'll fix it tomorrow. Maybe you could test it before I create a release?

**Comment by pineapplemachine** [comment]
I'd be happy to test. Thank you very much for the quick response!

**Comment by koskimas** [comment]
Awesome!

You can test the HEAD version by putting this in your package.json:

```
"objection": "git://github.com/Vincit/objection.js.git#28be316"
```

**Comment by pineapplemachine** [comment]
My package.json dependencies object now looks like this:

``` json
  "dependencies": {
    "bcrypt": "^1.0.2",
    "bluebird": "^3.5.0",
    "body-parser": "^1.16.0",
    "cookie-parser": "^1.4.3",
    "express": "^4.14.1",
    "knex": "0.13.0",
    "minimist": "^1.2.0",
    "moment": "^2.17.1",
    "node-uuid": "^1.4.7",
    "objection": "git://github.com/Vincit/objection.js.git#28be316",
    "pg": "^6.2.2",
    "speakeasy": "^2.0.0"
  },
```

I get this error when attempting to `npm install` with npm v3.10.10

``` text
sophie:server pineapple$ npm install
npm ERR! git rev-list -n1 28be316: fatal: ambiguous argument '28be316': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 28be316: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 28be316: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 28be316:
npm ERR! Darwin 13.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git rev-list -n1 28be316
npm ERR! fatal: ambiguous argument '28be316': unknown revision or path not in the working tree.
npm ERR! Use '--' to separate paths from revisions, like this:
npm ERR! 'git <command> [<revision>...] -- [<file>...]'
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by koskimas** [comment]
I messed up the original commit, force pushed a new one and edited the message. That's why 😄

**Comment by pineapplemachine** [comment]
This query quite unintuitively fails:

``` js
        const query = app.db.Questionnaire.first().joinEager("[author, title]").where({
            "questionnaireId": request.body.questionnaireId,
            "disabled": false,
        });
```

with this error:

``` text
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 4, false ],
  __knexQueryUid: '6b2999d3-40d3-479f-8bf8-64270f62ddc4',
  sql: 'select "maptionnaire"."Questionnaires".* from "maptionnaire"."Questionnaires" left join "maptionnaire"."Users" as "author" on "author"."userId" = "maptionnaire"."Questionnaires"."authorUserId" left join "maptionnaire"."MultilingualText" as "title" on "title"."textId" = "maptionnaire"."Questionnaires"."titleTextId" where "questionnaireId" = ? and "disabled" = ?' }
{ error: select "maptionnaire"."Questionnaires".* from "maptionnaire"."Questionnaires" left join "maptionnaire"."Users" as "author" on "author"."userId" = "maptionnaire"."Questionnaires"."authorUserId" left join "maptionnaire"."MultilingualText" as "title" on "title"."textId" = "maptionnaire"."Questionnaires"."titleTextId" where "questionnaireId" = $1 and "disabled" = $2 - column reference "disabled" is ambiguous
    at Connection.parseE (/Users/pineapple/git/mapita/maptionnaire2/src/server/node_modules/pg/lib/connection.js:567:11)
    at Connection.parseMessage (/Users/pineapple/git/mapita/maptionnaire2/src/server/node_modules/pg/lib/connection.js:391:17)
    at Socket.<anonymous> (/Users/pineapple/git/mapita/maptionnaire2/src/server/node_modules/pg/lib/connection.js:129:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TCP.onread (net.js:547:20)
  name: 'error',
  length: 107,
  severity: 'ERROR',
  code: '42702',
  detail: undefined,
  hint: undefined,
  position: '350',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '563',
  routine: 'scanRTEForColumn' }
```

This query succeeds but the `author ` attribute of the outputted object is incorrectly `null`:

``` js
        const query = app.db.Questionnaire.alias("questionnaire").first().joinEager(
            "[author, title]"
        ).where({
            "questionnaire.questionnaireId": request.body.questionnaireId,
            "questionnaire.disabled": false,
        });
```

The query debug output followed by the received object:

``` text
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 4, false ],
  __knexQueryUid: 'f6b2d82f-226f-47bd-9685-d4a1d857638e',
  sql: 'select "questionnaire".* from "maptionnaire"."Questionnaires" as "questionnaire" left join "maptionnaire"."Users" as "author" on "author"."userId" = "questionnaire"."authorUserId" left join "maptionnaire"."MultilingualText" as "title" on "title"."textId" = "questionnaire"."titleTextId" where "questionnaire"."questionnaireId" = ? and "questionnaire"."disabled" = ?' }
Questionnaire {
  questionnaireId: 4,
  name: 'New questionnaire',
  titleTextId: null,
  authorUserId: 6,
  creationTime: 2017-07-11T11:09:36.285Z,
  lastModifiedTime: 2017-07-11T11:09:36.285Z,
  disabled: false,
  author: null,
  title: [] }
```

It appears that it is correctly joining on the users table but failing to select any fields.

This query selects the author table column I'm interested in but it places it in the root returned questionnaire object instead of making it an attribute of the `author` object

``` js
        const query = app.db.Questionnaire.alias("questionnaire").first().joinEager(
            "[author, title]"
        ).select(
            "questionnaire.questionnaireId", "questionnaire.creationTime",
            "author.emailAddress"
        ).where({
            "questionnaire.questionnaireId": request.body.questionnaireId,
            "questionnaire.disabled": false,
        });
```

The output:

``` text
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 4, false ],
  __knexQueryUid: '5430bc0f-77b8-4014-b47d-592f41a02c55',
  sql: 'select "questionnaire"."questionnaireId", "questionnaire"."creationTime", "author"."emailAddress" from "maptionnaire"."Questionnaires" as "questionnaire" left join "maptionnaire"."Users" as "author" on "author"."userId" = "questionnaire"."authorUserId" left join "maptionnaire"."MultilingualText" as "title" on "title"."textId" = "questionnaire"."titleTextId" where "questionnaire"."questionnaireId" = ? and "questionnaire"."disabled" = ?' }
Questionnaire {
  questionnaireId: 4,
  creationTime: 2017-07-11T11:09:36.285Z,
  emailAddress: 'cool@3cool.com',
  author: null,
  title: [] }
```

**Comment by pineapplemachine** [comment]
I did also try selecting `author.emailAddress as author.emailAddress` but this only changed the key in the object rather than placing `emailAddress` in the author object

``` js
        const query = app.db.Questionnaire.alias("questionnaire").first().joinEager(
            "[author, title]"
        ).select(
            "questionnaire.questionnaireId", "questionnaire.creationTime",
            "author.emailAddress as author.emailAddress"
        ).where({
            "questionnaire.questionnaireId": request.body.questionnaireId,
            "questionnaire.disabled": false,
        });
```

produces

``` text
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 4, false ],
  __knexQueryUid: '867caf8d-9e99-482f-8c7a-fd780cc0a1e8',
  sql: 'select "questionnaire"."questionnaireId", "questionnaire"."creationTime", "author"."emailAddress" as "author.emailAddress" from "maptionnaire"."Questionnaires" as "questionnaire" left join "maptionnaire"."Users" as "author" on "author"."userId" = "questionnaire"."authorUserId" left join "maptionnaire"."MultilingualText" as "title" on "title"."textId" = "questionnaire"."titleTextId" where "questionnaire"."questionnaireId" = ? and "questionnaire"."disabled" = ?' }
Questionnaire {
  questionnaireId: 4,
  creationTime: 2017-07-11T11:09:36.285Z,
  'author.emailAddress': 'cool@3cool.com',
  author: null,
  title: [] }
```

**Comment by koskimas** [comment]
Argh! The knex method `columnInfo` doesn't work with schemas. I need to open an issue in knex before this can be solved. It may take a while. Fortunately @elhigu has push rights to knex 😄

**Comment by pineapplemachine** [comment]
Aaaaa ok. What would you suggest as the best workaround to use in the meantime?

**Comment by koskimas** [comment]
I had one more idea. Could you try out commit `0f3094010ea`

**Comment by pineapplemachine** [comment]
the good: it populates the author object! sweet

the bad: there doesn't seem to be a way to specify which columns should be included. it's important that I be able to select specific fields so that there's no chance of e.g. password hashes being accidentally included in an API response

**Comment by koskimas** [comment]
You can select columns using `modifyEager` like this:

```js
        const query = app.db.Questionnaire.alias("questionnaire").first().joinEager(
            "[author, title]"
        ).select(
            "questionnaire.questionnaireId", "questionnaire.creationTime"
        ).modifyEager('author', builder => {
            builder.select('emailAddress', 'blaaBlaa');
        }).where({
            "questionnaire.questionnaireId": request.body.questionnaireId,
            "questionnaire.disabled": false,
        });
```

You need to use modifyEager or follow the weird naming convention `joinEager` uses to be able to parse the flat result rows into a tree. `modifyEager` works with normal `eager` as well as the join based `joinEager`.

**Comment by pineapplemachine** [comment]
Aha I believe I have what I need

``` js
        const query = app.db.Questionnaire.alias("questionnaire").first().joinEager(
            "[author, title]"
        ).modifyEager("author", qb => {
            qb.select("emailAddress");
        }).select(
            "questionnaireId", "name",
            "creationTime", "lastModifiedTime"
        ).where({
            "questionnaireId": request.body.questionnaireId,
            "disabled": false,
        });
```

produces

``` text
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 4, false ],
  __knexQueryUid: '535fb6f8-50ad-45df-8b88-872dda4bc068',
  sql: 'select "questionnaireId", "name", "creationTime", "lastModifiedTime", "author"."userId" as "author:userId", "author"."emailAddress" as "author:emailAddress", "title"."textId" as "title:textId", "title"."languageCode" as "title:languageCode", "title"."content" as "title:content", "title"."contentOrigin" as "title:contentOrigin" from "maptionnaire"."Questionnaires" as "questionnaire" left join (select "emailAddress", "userId" from "maptionnaire"."Users") as "author" on "author"."userId" = "questionnaire"."authorUserId" left join "maptionnaire"."MultilingualText" as "title" on "title"."textId" = "questionnaire"."titleTextId" where "questionnaireId" = ? and "disabled" = ?' }
Questionnaire {
  questionnaireId: 4,
  name: 'New questionnaire',
  creationTime: 2017-07-11T11:09:36.285Z,
  lastModifiedTime: 2017-07-11T11:09:36.285Z,
  author: User { emailAddress: 'cool@3cool.com' },
  title: [] }
```

**Comment by koskimas** [comment]
By the way, a useful pattern to remove password hashes is to delete them in `$formatJson` like this:

```js
class User extends Model {
  $formatJson(json) {
    // Never leak password to the outside world.
    delete json.password;
    return json;
  }
}

**Comment by pineapplemachine** [comment]
That is awesome, thank you for letting me know about that

**Comment by pineapplemachine** [comment]
Is the pattern for limiting columns selected from a `HasManyRelation` different from a `BelongsToOneRelation`? What worked for `author` isn't working for `text` -

``` js
        const query = app.db.Questionnaire.alias("questionnaire").first().joinEager(
            "[author, title]"
        ).modifyEager("author", qb => {
            qb.select("emailAddress");
        }).modifyEager("title", qb => {
            qb.select("languageCode", "content", "contentOrigin");
        }).select(
            "questionnaireId", "name", "titleTextId",
            "creationTime", "lastModifiedTime"
        ).where({
            "questionnaireId": request.body.questionnaireId,
            "disabled": false,
        });
```

which outputs the _almost_ correct

``` text
found user User {
  userId: 6,
  passwordHash: '$2a$08$PYFdeKpp9ZF.Py3DeoMKZuTYfgwWylkfKgSCpV72Esf.3n1GFtxL2',
  otpEnabled: false }
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 4, false ],
  __knexQueryUid: '35e41952-134c-4dcf-a5bc-7e198e5332d5',
  sql: 'select "questionnaireId", "name", "creationTime", "lastModifiedTime", "author"."userId" as "author:userId", "author"."emailAddress" as "author:emailAddress", "author"."passwordHash" as "author:passwordHash", "title"."textId" as "title:textId", "title"."languageCode" as "title:languageCode", "title"."content" as "title:content", "title"."contentOrigin" as "title:contentOrigin" from "maptionnaire"."Questionnaires" as "questionnaire" left join (select "emailAddress", "passwordHash", "userId" from "maptionnaire"."Users") as "author" on "author"."userId" = "questionnaire"."authorUserId" left join "maptionnaire"."MultilingualText" as "title" on "title"."textId" = "questionnaire"."titleTextId" where "questionnaireId" = ? and "disabled" = ?' }
Questionnaire {
  questionnaireId: 4,
  name: 'New questionnaire',
  creationTime: 2017-07-11T11:09:36.285Z,
  lastModifiedTime: 2017-07-11T11:09:36.285Z,
  author:
   User {
     emailAddress: 'cool@3cool.com',
     passwordHash: '$2a$08$PYFdeKpp9ZF.Py3DeoMKZuTYfgwWylkfKgSCpV72Esf.3n1GFtxL2' },
  title:
   [ Text {
       textId: 'test',
       languageCode: 'en',
       content: 'test text neato',
       contentOrigin: 'userEntry' },
     Text {
       textId: 'test',
       languageCode: 'es',
       content: 'hola',
       contentOrigin: 'userEntry' },
     Text {
       textId: 'test',
       languageCode: 'fi',
       content: 'terve',
       contentOrigin: 'userEntry' } ] }
```

Except I was expecting only the `languageCode`, `content`, and `contentOrigin` columns to be included in the results

**Comment by pineapplemachine** [comment]
I also just realized that the query neglected to select the `titleTextId` column from the `Questionnaire` table

**Comment by pineapplemachine** [comment]
Sorry I'm an idiot

I forgot to restart the server
