### ISSUE TITLE
Bug: whereNotExists missing from generated query

### ISSUE THREAD

**Issue by pineapplemachine** [Vincit/objection.js#447]
I have this query:

``` js
app.db.Text.query().whereNotExists({
    "textId": request.body.textId,
    "languageCode": text.languageCode,
}).insert({
    "textId": request.body.textId,
    "languageCode": text.languageCode,
    "content": text.content,
    "contentOrigin": text.contentOrigin,
})
```

It produces this output:

``` text
insert into "maptionnaire"."MultilingualText" ("content", "contentOrigin", "languageCode", "textId") values ('LOL', 'userEntry', '??', 'test') returning "textId", "languageCode"
{ method: 'insert',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 'LOL', 'userEntry', '??', 'test' ],
  __knexQueryUid: '49df64ca-0730-49c6-884f-c5e00e9d5a98',
  sql: 'insert into "maptionnaire"."MultilingualText" ("content", "contentOrigin", "languageCode", "textId") values (?, ?, ?, ?) returning "textId", "languageCode"',
  returning: [ 'textId', 'languageCode' ] }
```

And because the `where not exists` clause is missing from the generated query I then get this error:

``` text
{ error: insert into "maptionnaire"."MultilingualText" ("content", "contentOrigin", "languageCode", "textId") values ($1, $2, $3, $4) returning "textId", "languageCode" - duplicate key value violates unique constraint "MultilingualText_pkey"
    at Connection.parseE (/Users/pineapple/git/mapita/maptionnaire2/src/server/node_modules/pg/lib/connection.js:567:11)
    at Connection.parseMessage (/Users/pineapple/git/mapita/maptionnaire2/src/server/node_modules/pg/lib/connection.js:391:17)
    at Socket.<anonymous> (/Users/pineapple/git/mapita/maptionnaire2/src/server/node_modules/pg/lib/connection.js:129:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TCP.onread (net.js:547:20)
  name: 'error',
  length: 241,
  severity: 'ERROR',
  code: '23505',
  detail: 'Key ("textId", "languageCode")=(test, ??) already exists.',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'maptionnaire',
  table: 'MultilingualText',
  column: undefined,
  dataType: undefined,
  constraint: 'MultilingualText_pkey',
  file: 'nbtinsert.c',
  line: '406',
  routine: '_bt_check_unique' }
```

**Comment by pineapplemachine** [comment]
Not a bug, just a user error http://knexjs.org/#Builder-whereNotExists

I expected `whereNotExists` to behave like `where` if I passed it an object.

Though I would suggest throwing an error instead of silently failing

**Comment by pineapplemachine** [comment]
Reopening because actually I am having the same problem even if I write

``` js
app.db.Text.query().whereNotExists(app.db.Text.where({
    "textId": request.body.textId,
    "languageCode": text.languageCode,
})).insert({
    "textId": request.body.textId,
    "languageCode": text.languageCode,
    "content": text.content,
    "contentOrigin": text.contentOrigin,
})
```

or

``` js
app.db.Text.query().whereNotExists(() => app.db.Text.where({
    "textId": request.body.textId,
    "languageCode": text.languageCode,
})).insert({
    "textId": request.body.textId,
    "languageCode": text.languageCode,
    "content": text.content,
    "contentOrigin": text.contentOrigin,
})
```

**Comment by newhouse** [comment]
To see if you can get it working, then later determine if it's still a bug, try changing your `whereNotExists` function argument to actually use `this.select(...)...` rather than an Objection query builder. In my experience you have to play by Knex's rules once you are that deep in. Also be sure to **not** use an arrow function as the argument but instead a regular old anonymous function so that the scope of `this` changes inside as it should, e.g.:
// from iPhone from bed example:
`...whereNotIn(function() { this.select(...)...})`

**Comment by pineapplemachine** [comment]
This also does not work

``` js
app.db.Text.query().whereNotExists(function(){
    return this.select("*").from("maptionnaire.MultilingualText").where({
        "textId": request.body.textId,
        "languageCode": text.languageCode,
    });
}).insert({
    "textId": request.body.textId,
    "languageCode": text.languageCode,
    "content": text.content,
    "contentOrigin": text.contentOrigin,
})
```

**Comment by fl0w** [comment]
Can you try something like:
```js
app.db.Text.query().whereNotExists(
    app.db.MultilingualText").query().where({
        "textId": request.body.textId,
        "languageCode": text.languageCode,
    })
).insert({
    "textId": request.body.textId,
    "languageCode": text.languageCode,
    "content": text.content,
    "contentOrigin": text.contentOrigin,
})
```

**Comment by pineapplemachine** [comment]
Ah sorry - I should have clarified that I extended the model so that `Text.where(...)` is the same as `Text.query().where(...)`.

``` js
app.db.Text.query().whereNotExists(
    app.db.Text.query().where({
        "textId": request.body.textId,
        "languageCode": text.languageCode,
    })
).insert({
    "textId": request.body.textId,
    "languageCode": text.languageCode,
    "content": text.content,
    "contentOrigin": text.contentOrigin,
})
```

outputs

```
insert into "maptionnaire"."MultilingualText" ("content", "contentOrigin", "languageCode", "textId") values ('LOL', 'userEntry', '??', 'test') returning "textId", "languageCode"
{ method: 'insert',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 'LOL', 'userEntry', '??', 'test' ],
  __knexQueryUid: '7bc11a61-345f-47ce-bf9f-50027174869e',
  sql: 'insert into "maptionnaire"."MultilingualText" ("content", "contentOrigin", "languageCode", "textId") values (?, ?, ?, ?) returning "textId", "languageCode"',
  returning: [ 'textId', 'languageCode' ] }
{ error: insert into "maptionnaire"."MultilingualText" ("content", "contentOrigin", "languageCode", "textId") values ($1, $2, $3, $4) returning "textId", "languageCode" - duplicate key value violates unique constraint "MultilingualText_pkey"
    at Connection.parseE (/Users/pineapple/git/mapita/maptionnaire2/src/server/node_modules/pg/lib/connection.js:567:11)
    at Connection.parseMessage (/Users/pineapple/git/mapita/maptionnaire2/src/server/node_modules/pg/lib/connection.js:391:17)
    at Socket.<anonymous> (/Users/pineapple/git/mapita/maptionnaire2/src/server/node_modules/pg/lib/connection.js:129:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TCP.onread (net.js:547:20)
  name: 'error',
  length: 241,
  severity: 'ERROR',
  code: '23505',
  detail: 'Key ("textId", "languageCode")=(test, ??) already exists.',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'maptionnaire',
  table: 'MultilingualText',
  column: undefined,
  dataType: undefined,
  constraint: 'MultilingualText_pkey',
  file: 'nbtinsert.c',
  line: '406',
  routine: '_bt_check_unique' }
```

**Comment by fl0w** [comment]
Yea, maybe knex doesn't support `where*Exists` in combination with `insert`. I'm in an awkward position so I can't check right now, but maybe later unless you've solved it. In worst case scenario you'd have use `raw`.

**Comment by pineapplemachine** [comment]
Ah this does appear to be an issue with knex

https://github.com/tgriesser/knex/issues/871

The reason I need this is to do an upsert. Is there some other pattern recommended for this?

**Comment by koskimas** [comment]
Maybe `INSERT ... ON CONFLICT UPDATE`, but you probably need to use `raw` for that. And of course you can use two queries in a transaction. I'm closing this since this is a knex issue. Knex also has an open ticket for `upsert`. Maybe that will get implemented one day.

**Comment by pineapplemachine** [comment]
I did a lot of googling and found some possible upsert implementations, including one you (@koskimas) posted in response to a similar issue, but none of the ones I tried worked for me; I think they only applied to older versions of knex. I really am not that familiar with the library - It would be wonderfully helpful if you could point me toward an example of how to actually use `ON CONFLICT UPDATE`, at least without completely forfeiting the advantages of knex's dynamic query building

**Comment by fl0w** [comment]
Well, using bookshelf.js I do something close to an (untested) objection.js equivalent of:

```js
const { raw, QueryBuilder } = require('objection')

class MyQueryBuilder extends objection.QueryBuilder {
  upsert (model, conflictId = 'id') {
    // update all fields if conflict occurs on conflictId
    const onConflict = Object.keys(o).map(c => `${c} = EXCLUDED.${c}`).join(', ')
    const insertQuery = Model.query().insert(obj).toString()   
    return raw(`${insertQuery} ON CONFLICT (${conflictId}) DO UPDATE ${onConflict}`)
  }
}
```

I have a bit more options (like specifying what fields to update on conflict and whatever), but I think maybe this helps?

**Comment by elhigu** [comment]
@fl0w when dealing with knex queries, you don't need to do `toString()`, when passing sub-queries to raw. 

When sub-queries are passed as `?` value bindings then internal value bindings of the sub-query will be passed to database driver as bindings (safer against sql injection and values containing `?` marks).

So safer version where column names are also escaped would be like:

```js
const onConflictSql = Object.keys(obj).map(c => `?? = EXCLUDED.??`).join(', ');
const onConflictBindings = Object.keys(obj).reduce((bindings, c) => {
  bindings.push(c);
  bindings.push(c);
  return bindings;
}, []);
const onConflict = raw(onConflictSql, onConflictBindings);
return raw('? ON CONFLICT (??) DO UPDATE SET ?', [insertQuery, conflictId, onConflict]);
```

But thanks for the snippet though! I just wanted to mention about the dangers of using `${}` when combining `knex` queries to raw queries.

**Comment by fl0w** [comment]
@elhigu not sure why I've never thought of using value binding for SQL queries. I think I just assumed `?`would wrap a query in quotes, and `??` in double quotes - but of course, it behaves as expected with ints and so I should have concluded that it does coerce correctly for query builder objects. Thanks for that - sometimes once you see it, it instantly makes sense. Weird how old habits sometimes inhibits obvious patterns.

Thought I do use value binding for everything else  - my mistake not providing a cleaner example. In my defence, this was the last thing I did before I fell asleep :).

**Comment by pineapplemachine** [comment]
Could someone help me out? When I try to upsert with this, I don't get any error but neither is any change made to the database. The returned query object does not have `debug` or `toSql` attributes which is making this difficult to troubleshoot.

``` js
class MyQueryBuilder extends objection.QueryBuilder {
    upsert(insertion, conflictIds = undefined){
        // Get conflict columns, default to ID columns
        let conflicts = conflictIds || this.modelClass().idColumn;
        if(typeof(conflicts) === "string") conflicts = [conflicts];
        // Build the "DO UPDATE SET ..." part of the query
        let conflictSql = "";
        let conflictBindings = [];
        for(const conflictName in conflicts){
            if(conflictSql.length) conflictSql += ", ";
            conflictSql += "??";
            conflictBindings.push(conflictName);
        }
        const onConflict = objection.raw(conflictSql, conflictBindings);
        // Build the "ON CONFLICT (...)" part of the query.
        let setSql = "";
        let setBindings = [];
        for(const columnName in insertion){
            if(setSql.length) setSql += ", ";
            setSql += "?? = EXCLUDED.??";
            setBindings.push(columnName, columnName);
        }
        const onConflictSet = objection.raw(setSql, setBindings);
        // Put everything together and return.
        return objection.raw("? ON CONFLICT (?) DO UPDATE SET ?", [
            this.insert(insertion), onConflict, onConflictSet
        ]);
    }
}
```

Here's what I see when I `console.log` the returned query object:

``` text
RawBuilder {
  _sql: '? ON CONFLICT (?) DO UPDATE SET ?',
  _args:
   [ MyQueryBuilder {
       _knex: [Object],
       _operations: [Object],
       _context: [Object],
       _modelClass: [Function: Text],
       _explicitRejectValue: null,
       _explicitResolveValue: null,
       _eagerExpression: null,
       _eagerFilterExpressions: [],
       _allowedEagerExpression: null,
       _allowedInsertExpression: null,
       _findOperationOptions: {},
       _eagerOperationOptions: {},
       _findOperationFactory: [Function],
       _insertOperationFactory: [Function],
       _updateOperationFactory: [Function],
       _patchOperationFactory: [Function],
       _relateOperationFactory: [Function],
       _unrelateOperationFactory: [Function],
       _deleteOperationFactory: [Function],
       _eagerOperationFactory: [Function: WhereInEagerAlgorithm] },
     RawBuilder { _sql: '??, ??', _args: [Object] },
     RawBuilder {
       _sql: '?? = EXCLUDED.??, ?? = EXCLUDED.??, ?? = EXCLUDED.??, ?? = EXCLUDED.??',
       _args: [Object] } ] }
RawBuilder {
  _sql: '? ON CONFLICT (?) DO UPDATE SET ?',
  _args:
   [ MyQueryBuilder {
       _knex: [Object],
       _operations: [Object],
       _context: [Object],
       _modelClass: [Function: Text],
       _explicitRejectValue: null,
       _explicitResolveValue: null,
       _eagerExpression: null,
       _eagerFilterExpressions: [],
       _allowedEagerExpression: null,
       _allowedInsertExpression: null,
       _findOperationOptions: {},
       _eagerOperationOptions: {},
       _findOperationFactory: [Function],
       _insertOperationFactory: [Function],
       _updateOperationFactory: [Function],
       _patchOperationFactory: [Function],
       _relateOperationFactory: [Function],
       _unrelateOperationFactory: [Function],
       _deleteOperationFactory: [Function],
       _eagerOperationFactory: [Function: WhereInEagerAlgorithm] },
     RawBuilder { _sql: '??, ??', _args: [Object] },
     RawBuilder {
       _sql: '?? = EXCLUDED.??, ?? = EXCLUDED.??, ?? = EXCLUDED.??, ?? = EXCLUDED.??',
       _args: [Object] } ] }
```

**Comment by pineapplemachine** [comment]
I have been experimenting with `objection.raw` and even with definitely valid raw query strings with no substitutions, the returned object is not thennable and does not support any of the other methods I expect from a query object either. Am I just misusing `raw`? But I'm doing the same thing as was given as an example in the comments above.

**Comment by koskimas** [comment]
`objection.raw` is no not the same as `knex.raw`. It's a wrapper that is specifically meant to be knex independent. You can just use `knex.raw` or `Model.raw` to create raw queries.

**Comment by pineapplemachine** [comment]
Ok, that did help, but I'm now stuck on incorporating the insertion query.

Here's my implementation currently:

``` js
class MyQueryBuilder extends objection.QueryBuilder {
    upsert(insertion, conflictIds = undefined){
        // Get conflict columns, default to ID columns
        let conflicts = conflictIds || this.modelClass().idColumn;
        if(typeof(conflicts) === "string") conflicts = [conflicts];
        // Build the "ON CONFLICT (...)" part of the query.
        let conflictSql = "";
        let conflictBindings = [];
        for(const conflictName of conflicts){
            if(conflictSql.length) conflictSql += ", ";
            conflictSql += "??";
            conflictBindings.push(conflictName);
        }
        const onConflict = this.modelClass().raw(conflictSql, conflictBindings);
        // Build the "DO UPDATE SET ..." part of the query
        let setSql = "";
        let setBindings = [];
        for(const columnName in insertion){
            if(setSql.length) setSql += ", ";
            setSql += "?? = EXCLUDED.??";
            setBindings.push(columnName, columnName);
        }
        const onConflictSet = this.modelClass().raw(setSql, setBindings);
        // Put everything together and return.
        const insertQuery = this.modelClass().query().insert(insertion);
        return this.modelClass().raw("? ON CONFLICT (?) DO UPDATE SET ?", [
            insertQuery.toSql(), onConflict, onConflictSet,
        ]);
    }
}
```

I get this error because `insertQuery` is incorrectly substituted:

``` text
{ error: $1 ON CONFLICT ("textId", "languageCode") DO UPDATE SET "textId" = EXCLUDED."textId", "languageCode" = EXCLUDED."languageCode", "content" = EXCLUDED."content", "contentOrigin" = EXCLUDED."contentOrigin" - syntax error at or near "$1"
    at Connection.parseE (/Users/pineapple/git/mapita/maptionnaire2/src/server/node_modules/pg/lib/connection.js:567:11)
    at Connection.parseMessage (/Users/pineapple/git/mapita/maptionnaire2/src/server/node_modules/pg/lib/connection.js:391:17)
    at Socket.<anonymous> (/Users/pineapple/git/mapita/maptionnaire2/src/server/node_modules/pg/lib/connection.js:129:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TCP.onread (net.js:547:20)
  name: 'error',
  length: 83,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '1',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1053',
  routine: 'scanner_yyerror' }
```

When I try putting `insertQuery` in the bindings instead of `insertQuery.toSql()` I get a different error:

``` text
Error: Undefined binding(s) detected when compiling RAW query: ? ON CONFLICT ("textId", "languageCode") DO UPDATE SET "textId" = EXCLUDED."textId", "languageCode" = EXCLUDED."languageCode", "content" = EXCLUDED."content", "contentOrigin" = EXCLUDED."contentOrigin"
    at Raw.toSQL (/Users/pineapple/git/mapita/maptionnaire2/src/server/node_modules/knex/lib/raw.js:152:13)
    at Object./text/set [as call] (/Users/pineapple/git/mapita/maptionnaire2/src/server/api/v1/text.js:117:31)
    at app.(anonymous function).error (/Users/pineapple/git/mapita/maptionnaire2/src/server/api/routes.js:37:23)
    at Layer.handle [as handle_request] (/Users/pineapple/git/mapita/maptionnaire2/src/server/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/pineapple/git/mapita/maptionnaire2/src/server/node_modules/express/lib/router/route.js:137:13)
    at app.auth.useActiveSession.then (/Users/pineapple/git/mapita/maptionnaire2/src/server/api/routes.js:132:17)
    at tryCatcher (/Users/pineapple/git/mapita/maptionnaire2/src/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/pineapple/git/mapita/maptionnaire2/src/server/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/pineapple/git/mapita/maptionnaire2/src/server/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._fulfillPromises (/Users/pineapple/git/mapita/maptionnaire2/src/server/node_modules/bluebird/js/release/promise.js:668:14)
    at Promise._settlePromises (/Users/pineapple/git/mapita/maptionnaire2/src/server/node_modules/bluebird/js/release/promise.js:694:18)
    at Async._drainQueue (/Users/pineapple/git/mapita/maptionnaire2/src/server/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/pineapple/git/mapita/maptionnaire2/src/server/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/pineapple/git/mapita/maptionnaire2/src/server/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by elhigu** [comment]
That query combining with `knex.raw`, works currently only for queries generated with knex. Queries returned by objection does not work when passed to `knex.raw()`. 

https://runkit.com/embed/j0mq97zqe30u

 And I don't know if there are any possible ways to support it either with objection, since objection query builder creates some times multiple queries per each builder method and that really cannot be compiled to single replacement for adding to `raw()`.

I wish there was a way to support this in objection somehow (maybe for builders that actually generate only single queries) without dropping to `knex` level completely.

AFAIK currently the only way to do that kind of query combining is to use knex query builders and knex.raw directly.

**Comment by pineapplemachine** [comment]
Here is something that seems to be constructing queries as expected

I realized in so succeeding that the version of postgres I'm using doesn't support `ON CONFLICT`

I will update postgres and report back later

``` js
class MyQueryBuilder extends objection.QueryBuilder {
    upsert(insertion, conflictIds = undefined){
        // Get conflict columns, default to ID columns
        let conflicts = conflictIds || this.modelClass().idColumn;
        if(typeof(conflicts) === "string") conflicts = [conflicts];
        // Build the "ON CONFLICT (...)" part of the query.
        let conflictSql = "";
        let conflictBindings = [];
        for(const conflictName of conflicts){
            if(conflictSql.length) conflictSql += ", ";
            conflictSql += "??";
            conflictBindings.push(conflictName);
        }
        const onConflict = this.modelClass().raw("(" + conflictSql + ")", conflictBindings);
        // Build the "DO UPDATE SET ..." part of the query
        let setSql = "";
        let setBindings = [];
        for(const columnName in insertion){
            if(setSql.length) setSql += ", ";
            setSql += "?? = EXCLUDED.??";
            setBindings.push(columnName, columnName);
        }
        const onConflictSet = this.modelClass().raw(setSql, setBindings);
        // Build the INSERT INTO <table> (...) part of the query
        // Build the VALUES(...) part of the query
        // Build the RETURNING ... part of the query
        let insertColumnsSql = "";
        let insertColumnBindings = [];
        let valuesSql = "";
        let valuesBindings = [];
        let returningSql = "";
        let returningBindings = [];
        for(const columnName in insertion){
            if(insertColumnsSql.length) insertColumnsSql += ", ";
            insertColumnsSql += "??";
            insertColumnBindings.push(columnName);
            if(valuesSql.length) valuesSql += ", ";
            valuesSql += "?";
            valuesBindings.push(insertion[columnName]);
            if(returningSql.length) returningSql += ", ";
            returningSql += "??";
            returningBindings.push(columnName);
        }
        const insertColumns = this.modelClass().raw("(" + insertColumnsSql + ")", insertColumnBindings);
        const values = this.modelClass().raw("(" + valuesSql + ")", valuesBindings);
        const returning = this.modelClass().raw(returningSql, returningBindings);
        return this.modelClass().raw("INSERT INTO ?? ? VALUES ? RETURNING ? ON CONFLICT ? DO UPDATE SET ?", [
            this.modelClass().tableName, insertColumns, values, returning, onConflict, onConflictSet,
        ]);
    }
}
```

**Comment by pineapplemachine** [comment]
For any future users trying to write an upsert with objection, here is my solution:

``` js
class MyQueryBuilder extends objection.QueryBuilder{
    // https://github.com/Vincit/objection.js/issues/447
    upsert(insertion, conflictIds = undefined){
        // Get conflict columns, default to ID columns
        let conflicts = conflictIds || this.modelClass().idColumn;
        if(typeof(conflicts) === "string") conflicts = [conflicts];
        // Build the "ON CONFLICT (...)" part of the query.
        let conflictSql = "";
        const conflictBindings = [];
        for(const conflictName of conflicts){
            if(conflictSql.length) conflictSql += ", ";
            conflictSql += "??";
            conflictBindings.push(conflictName);
        }
        const onConflict = this.modelClass().raw(
            "(" + conflictSql + ")", conflictBindings
        );
        // Build the "DO UPDATE SET ..." part of the query
        // Build the INSERT INTO <table> (...) part of the query
        // Build the VALUES(...) part of the query
        // Build the RETURNING ... part of the query
        let setSql = "";
        const setBindings = [];
        let insertColumnsSql = "";
        const insertColumnBindings = [];
        let valuesSql = "";
        const valuesBindings = [];
        let returningSql = "";
        const returningBindings = [];
        for(const columnName in insertion){
            if(setSql.length){
                setSql += ", ";
                insertColumnsSql += ", ";
                valuesSql += ", ";
                returningSql += ", ";
            }
            setSql += "?? = EXCLUDED.??";
            insertColumnsSql += "??";
            valuesSql += "?";
            returningSql += "??";
            setBindings.push(columnName, columnName);
            insertColumnBindings.push(columnName);
            valuesBindings.push(insertion[columnName]);
            returningBindings.push(columnName);
        }
        const onConflictSet = this.modelClass().raw(setSql, setBindings);
        const insertColumns = this.modelClass().raw(
            "(" + insertColumnsSql + ")", insertColumnBindings
        );
        const values = this.modelClass().raw(
            "(" + valuesSql + ")", valuesBindings
        );
        const returning = this.modelClass().raw(
            returningSql, returningBindings
        );
        return this.modelClass().raw(
            "INSERT INTO ?? ? VALUES ? ON CONFLICT ? DO UPDATE SET ? RETURNING ?", [
                this.modelClass().tableName, insertColumns, values,
                onConflict, onConflictSet, returning
            ]
        );
    }
}
```

**Comment by fl0w** [comment]
To avoid future headache, you probably should check for `hasOwnProperty` in that `for-in` loop :)

**Comment by jeshicawang** [comment]
This is not an upsert, but I'm sure it could be modified to be.

Here's my solution for my use case where I wanted an `ON CONFLICT DO NOTHING`, so that conflicting rows would be ignored when inserting.

```javascript
class BaseQueryBuilder extends objection.QueryBuilder {

  safeInsert(data, conflictCols) {
    const entries = Array.isArray(data) ? data : [data];
    const conflictSql = Array(conflictCols.length).fill('??').join(', ');
    const conflict = this.modelClass().raw(conflictSql, conflictCols);
    const insertSql = this.insert(entries).returning().toSql();
    return this.modelClass().raw(`${insertSql} ON CONFLICT (?) DO NOTHING`, [conflict]);
  }

}
```
