### ISSUE TITLE
Subqueries cannot reference relations

### ISSUE THREAD

**Issue by devinivy** [Vincit/objection.js#538]
First, I'm running objection v0.8.8.

This example is a bit contrived, but say I want all users who have young pets ordered by their account creation dates.  Consider the following query,
```js
const resultQuery = Users.query()
    .joinEager('pets')
    .where('pets.age', '<', 2)
    .groupBy('Users.id');

const usersWithYoungPets = await Users.query().from(resultQuery).orderBy('createdAt');
```

This fails with the following stacktrace,
```
TypeError: Uncaught error: Cannot read property 'columns' of undefined
at RelationJoinBuilder.buildSelects (/project/node_modules/objection/lib/queryBuilder/operations/eager/RelationJoinBuilder.js:355:58)
at RelationJoinBuilder.doBuild (/project/node_modules/objection/lib/queryBuilder/operations/eager/RelationJoinBuilder.js:255:12)
at RelationJoinBuilder.build (/project/node_modules/objection/lib/queryBuilder/operations/eager/RelationJoinBuilder.js:112:10)
at JoinEagerOperation.onBuild (/project/node_modules/objection/lib/queryBuilder/operations/eager/JoinEagerOperation.js:51:22)
at QueryBuilder.buildInto (/project/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:177:10)
at buildInto (/project/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1096:25)
at QueryBuilder.build (/project/node_modules/objection/lib/queryBuilder/QueryBuilder.js:458:19)
at convertQueryBuilderBase (/project/node_modules/objection/lib/queryBuilder/operations/ObjectionToKnexConvertingOperation.js:93:18)
at convertArgs (/project/node_modules/objection/lib/queryBuilder/operations/ObjectionToKnexConvertingOperation.js:43:16)
at FromOperation.onAdd (/project/node_modules/objection/lib/queryBuilder/operations/ObjectionToKnexConvertingOperation.js:23:17)
at FromOperation.onAdd (/project/node_modules/objection/lib/queryBuilder/operations/FromOperation.js:17:23)
at QueryBuilder.addOperation (/project/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:134:33)
at QueryBuilder.from (/project/node_modules/objection/lib/queryBuilder/QueryBuilder.js:971:17)
at my project code
```

The issue is that the `before2` JoinEagerOperation hook required to generate the query (by fetching column names) would be called to execute the subquery (though naturally we're not executing it) but is not called just to build the subquery.

**Comment by jeff3yan** [comment]
You could try something like a `join distinct`, since you're not interested in eagerly fetching the pets data anywhere:

```
const idColumn = 'Users.id';

const filterQuery = Users
  .query()
  .distinct(idColumn)
  .joinRelation('pets')
  .where('pets.age', '<', 2);

const usersWithYoungPets = await Users
  .query()
  .innerJoin(
    filterQuery.as('filter_query'),
    idColumn,
    'filter_query.id'
  );
```

**Comment by devinivy** [comment]
That's a good idea, thanks!  I have worked around my issue now as I didn't really need all those columns, but I still think it might be worthwhile to investigate a fix for this.

**Comment by koskimas** [comment]
There's no easy way to fix this and @jeff3yan is right, you should use `joinRelation` instead. It's just like `joinEager` but without the output mapping into a tree of models. `joinEager` doesn't really make sense as a subquery.
