### ISSUE TITLE
EACCES when using socket and requesting more eager expressions than min connections

### ISSUE THREAD

**Issue by amosyuen** [Vincit/objection.js#540]
I'm using objection v0.8.9 in a docker linux container on Windows.

When I make a request that has a more eager expressions than the default pool connections in knex, it gives me this error:
```
Error: connect EACCES /var/lib/mysql/mysql.sock
    at Object._errnoException (util.js:1019:11)
    at _exceptionWithHostPort (util.js:1041:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)
From previous event:
    at Client_MySQL2.acquireRawConnection (/code/api/src/node_modules/knex/lib/dialects/mysql2/index.js:74:12)
    at Object.create (/code/api/src/node_modules/knex/lib/client.js:239:16)
    at Pool._createResource (/code/api/src/node_modules/generic-pool/lib/generic-pool.js:354:17)
    at Pool.dispense [as _dispense] (/code/api/src/node_modules/generic-pool/lib/generic-pool.js:314:10)
    at Pool.acquire (/code/api/src/node_modules/generic-pool/lib/generic-pool.js:436:8)
    at /code/api/src/node_modules/knex/lib/client.js:289:19
From previous event:
    at Client_MySQL2.acquireConnection (/code/api/src/node_modules/knex/lib/client.js:280:12)
    at /code/api/src/node_modules/knex/lib/runner.js:208:30
From previous event:
    at /code/api/src/node_modules/knex/lib/runner.js:206:35
From previous event:
    at Runner.ensureConnection (/code/api/src/node_modules/knex/lib/runner.js:205:34)
    at Runner.run (/code/api/src/node_modules/knex/lib/runner.js:51:42)
    at Builder.Target.then (/code/api/src/node_modules/knex/lib/interface.js:35:43)
    at Builder.Target.(anonymous function) [as bind] (/code/api/src/node_modules/knex/lib/interface.js:85:26)
    at Object.<anonymous> (/code/api/src/node_modules/objection/lib/queryBuilder/QueryBuilder.js:512:31)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at QueryBuilder.execute (/code/api/src/node_modules/objection/lib/queryBuilder/QueryBuilder.js:497:20)
    at QueryBuilder.then (/code/api/src/node_modules/objection/lib/queryBuilder/QueryBuilder.js:393:26)
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

+ I'm using the default WhereInEagerAlgorithm
+ I'm connecting to mysql using a socket. If I use a host and port instead, there is no problem.
+ By default the knex config has a connection pool with min connections of 2 and max of 10. So if I request more 2 eager relations, the query works fine. If I request more than 2 it throws the above error. If I increase the min connection pool to 3, then I can request up to 3 eager relations.

**Comment by koskimas** [comment]
Unfortunately there is nothing that van be done in objection. This is a bug in knex or the mysql node client. Objection simply starts parallel queries using knex, nothing more. You can probably reproduce the bug without objection by doing parallel queries. You can use a transaction as a workaround.
