### ISSUE TITLE
upsertGraph: undefined passed as argument #1 for 'whereComposite' operation

### ISSUE THREAD

**Issue by zacharynevin** [Vincit/objection.js#601]
When I try to update an existing model with `upsertGraph`, I get the following error (full stacktrace):

```
Error: undefined passed as argument #1 for 'whereComposite' operation. Call skipUndefined() method to ignore the undefined values.
    at convertUndefined (/project/node_modules/objection/lib/queryBuilder/operations/ObjectionToKnexConvertingOperation.js:67:11)
    at convertArgs (/project/node_modules/objection/lib/queryBuilder/operations/ObjectionToKnexConvertingOperation.js:38:14)
    at WhereCompositeOperation.onAdd (/project/node_modules/objection/lib/queryBuilder/operations/ObjectionToKnexConvertingOperation.js:22:17)
    at QueryBuilder.addOperation (/project/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:147:33)
    at QueryBuilder.whereComposite (/project/node_modules/objection/lib/queryBuilder/QueryBuilderBase.js:485:17)
    at InstanceUpdateOperation.onBuild (/project/node_modules/objection/lib/queryBuilder/operations/InstanceUpdateOperation.js:30:13)
    at QueryBuilder.buildInto (/project/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:190:10)
    at buildInto (/project/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1129:25)
    at Object.<anonymous> (/project/node_modules/objection/lib/queryBuilder/QueryBuilder.js:532:25)
    at Object.tryCatcher (/project/node_modules/objection/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/project/node_modules/objection/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/project/node_modules/objection/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/project/node_modules/objection/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/project/node_modules/objection/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/project/node_modules/objection/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/project/node_modules/objection/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/project/node_modules/objection/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
```

When I am calling the `upsertGraph` operation, I am passing in the model root `id`. As a last-ditch effort to try and understand what is happening, I went into `ObjectionToKnexConvertingOperation.js` and logged `args` under the `convertArgs` function. I also turned on `debug()`.

For the following update:

```
{
  "title": "Mytitle",
  "startDate": "2018-06-18T08:07:09.728Z",
  "createdAt": "2017-11-07T00:18:56.511Z",
  "id": "9"
}
```
I got the following log output from `convertArgs`:

```
{ '0': 'meetings.id', '1': [ '9' ] }
[ 'meetings.id' ]
[]
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ '9' ],
  __knexQueryUid: 'e2e4b1fa-e77d-4848-a05b-838785667a3d',
  sql: 'select "meetings"."id" from "meetings" where "meetings"."id" in (?)' }
[]
[]
{ '0': 'meetings.id', '1': undefined }
```

It seems as if at some point, the root `id` is undefined? I should also note that I went into the database schema and removed all the `onDelete('CASCADE')` parts, in case that was interfering.

Thank you!

**Comment by koskimas** [comment]
Could you post the actual query that fails with the actual data that fails? You are not giving me much to work with here, or are you assuming `upsertGraph` is completely broken and every query will give that error?

**Comment by zacharynevin** [comment]
Hi there,

I am assuming that `upsertGraph` is completely broken and every query seems to be giving that error. I originally had some relations in my query but stripped them out in the debugging process.

I would be happy to post a full query. Give me a few minutes

**Comment by koskimas** [comment]
Sigh.. I can assure you that upsertGraph is not completely broken. It has a quite comprehensive test suite. Please in the future, don't assume that and provide enough information for us to help you. 95% of the time the problem is in the users's code and not in objection.

**Comment by zacharynevin** [comment]
I didn't mean any offense. I guess what I am trying to get at is that I seem to have landed on some obscure edge case. 

Imagine I have the following schema:

```
Meeting {
  id: integer
  title: string
  createdAt: date
  deal: Deal
  contacts: Array<Contact>
}

Deal {
  id: integer
  contacts: Array<Contact>
  createdAt: Date
}

Contact {
  id: integer
  name: string
  email: string
  createdAt: Date
  Deals: Array<Deal>
}
```
Here, I have meetings which has many contacts. A deal also has many contacts, and a contact has many deals. When I create a meeting, I also ensure that any contacts I add to my meeting are also associated with the deal.

To support his schema I have the following tables:
```
meetings:
- id: integer PRIMARY
- accountID: integer NOT NULLABLE
- title: varchar NOT NULLABLE
- createdAt: timestamp NOT NULLABLE 
- dealID: integer FOREIGN KEY REFERENCES deal.id

deals:
- id: integer PRIMARY
- accountID: integer NOT NULLABLE
- createdAt: timestamp NOT NULLABLE

contacts:
- id: integer PRIMARY
- accountID: integer NOT NULLABLE
- name: string NOT NULLABLE
- email: string NOT NULLABLE
- createdAt: timestamp NOT NULLABLE

deal_contacts:
- id: integer PRIMARY
- dealID: integer FOREIGN KEY REFERENCES deals.id
- contactID: integer FOREIGN KEY REFERENCES contacts.id

meeting_contacts:
- id: integer PRIMARY
- meetingID: integer FOREIGN KEY REFERENCES meetings.id
- contactID: integer FOREIGN KEY REFERENCES contacts.id
```

Now imagine that I have the following meeting already (I pulled this from my test logs):
```
Meeting {
  title: 'Esi zeki fivwip nezatfep indid haf zikjinid tos biwlopce pamoz num cijol feasu hoak watan wavius ej nuklaz.',
  accountID: 'feae23bc8effe164ed1ebf562dbf00ed180368bf',
  deal: 
   Deal {
     accountID: 'feae23bc8effe164ed1ebf562dbf00ed180368bf',
     createdAt: 2017-11-07T01:10:40.799Z,
     id: 23 },
  createdAt: 2017-11-07T01:10:40.799Z,
  contacts: 
   [ Contact {
       accountID: 'feae23bc8effe164ed1ebf562dbf00ed180368bf',
       name: 'Mae Perez',
       email: 'rapocan@pod.tw',
       createdAt: 2017-11-07T01:10:40.799Z,
       id: 16 } ],
  dealID: 23,
  id: 11
}
```

So now lets say that I want to update the title of the meeting. The exact query I am running is: 

```
let meeting = await Meeting.query(trx).upsertGraph({
 "title": "Mytitle",
 "accountID": "feae23bc8effe164ed1ebf562dbf00ed180368bf",
 "deal": {
  "id": 23,
  "contacts": [
   {
    "#ref": "sUjZ84q26hl87UVRvkawJEJD8Y2pr3"
   }
  ]
 },
 "startDate": "2018-03-03T04:59:54.650Z",
 "createdAt": "2017-11-07T01:10:40.799Z",
 "contacts": [
  {
   "id": 16,
   "#id": "sUjZ84q26hl87UVRvkawJEJD8Y2pr3"
  }
 ],
 "dealID": 23,
 "id": "11"
}, {
  relate: true,
  unrelate: true,
  noDelete: true
})
```
