### ISSUE TITLE
Connection not available error when trying to override static query() method and add some initial calls to every created query builder

### ISSUE THREAD

**Issue by elhigu** [Vincit/objection.js#642]
This is the code I prototyped:

```js
require('sqlite3');
const Knex = require('knex');
const {Model} = require('objection');

const knexSqlite = Knex({
  client: 'sqlite',
  connection: ':memory:'
  useNullAsDefault: true
});

class Child extends Model {
  static get tableName() {
    return 'Child';
  }
}

class Parent extends Model {
  static get tableName() {
    return 'Parent';
  }

  static query(connection) {
    // passing .where here causes  no database connection available for a query error
    return super.query(connection).where('id', 0);
    // this works though
    // return super.query(connection);
  }

  static get relationMappings() {
    return {
      child: {
        relation: Model.HasOneRelation,
        modelClass: Child,
        join: {
          from: 'Parent.id',
          to: 'Child.parentId'
        }
      }
    };
  }
}

async function main() {
  await knexSqlite.schema.createTable('Parent', t => {
    t.increments('id').primary();
    t.string('name');
  });

  await knexSqlite.schema.createTable('Child', t => {
    t.increments('id').primary();
    t.string('data');
    t.integer('parentId');
  });

  const results = await Parent.query(knexSqlite).insertGraphAndFetch([
    {name: 'foo parent', child: {data: 'foo'}},
    {name: 'bar parent', child: {data: 'bar'}}
  ]);

  console.log('Res', results);
}

main()
  .catch(e => console.log('Got error', e))
  .then(() => knexSqlite.destroy());
```

And it throws:

```bash
Got error Error: no database connection available for a query. You need to bind the model class or the query to a knex instance.
    at QueryBuilder.knex (/Users/mikaelle/Projects/stuffs/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:61:15)
    at convertArgs (/Users/mikaelle/Projects/stuffs/node_modules/objection/lib/queryBuilder/operations/ObjectionToKnexConvertingOperation.js:29:24)
    at KnexOperation.onAdd (/Users/mikaelle/Projects/stuffs/node_modules/objection/lib/queryBuilder/operations/ObjectionToKnexConvertingOperation.js:22:17)
    at QueryBuilder.addOperation (/Users/mikaelle/Projects/stuffs/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:147:33)
    at QueryBuilder.where (/Users/mikaelle/Projects/stuffs/node_modules/objection/lib/queryBuilder/QueryBuilderBase.js:181:17)
    at Function.query (/Users/mikaelle/Projects/stuffs/test.js:23:36)
    at tableInsertion (/Users/mikaelle/Projects/stuffs/node_modules/objection/lib/queryBuilder/graphInserter/inserter.js:19:49)
    at Promise.all.Object.keys.map.tableName (/Users/mikaelle/Projects/stuffs/node_modules/objection/lib/queryBuilder/graphInserter/GraphInserter.js:54:16)
    at Array.map (<anonymous>)
    at GraphInserter._executeNextBatch (/Users/mikaelle/Projects/stuffs/node_modules/objection/lib/queryBuilder/graphInserter/GraphInserter.js:48:26)
    at GraphInserter._executeNormalBatches (/Users/mikaelle/Projects/stuffs/node_modules/objection/lib/queryBuilder/graphInserter/GraphInserter.js:35:17)
    at Promise.try (/Users/mikaelle/Projects/stuffs/node_modules/objection/lib/queryBuilder/graphInserter/GraphInserter.js:21:35)
    at tryCatcher (/Users/mikaelle/Projects/stuffs/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/mikaelle/Projects/stuffs/node_modules/bluebird/js/release/method.js:39:29)
    at GraphInserter.execute (/Users/mikaelle/Projects/stuffs/node_modules/objection/lib/queryBuilder/graphInserter/GraphInserter.js:21:23)
    at InsertGraphOperation.onAfter1 (/Users/mikaelle/Projects/stuffs/node_modules/objection/lib/queryBuilder/operations/InsertGraphOperation.js:98:26)
```

Is this a bug or am I just doing something wrong?

**Comment by elhigu** [comment]
I traced the problem here: 

https://github.com/Vincit/objection.js/blob/e944679cbce440764c59f4e3bc9b176921fdc3af/lib/queryBuilder/graphInserter/inserter.js#L19

```js
let insertQuery = tableInsertion.modelClass.query().childQueryOf(builder);
```

builder has knex conenction in context, but it is not passed to the query() which creates new query builder. 

Not sure if this even should work like this at all.

**Comment by koskimas** [comment]
What if you pass `...args` to the super query call instead of the first argument?

**Comment by elhigu** [comment]
The same error remains after this:

```js
  static query(connection) {
    console.dir('ARGS');
    console.dir(arguments);
    // passing .where here causes  no database connection available for a query error
    return super.query(...arguments).where('id', 0);
    // this works though
    // return super.query(connection);
  }
```

**Comment by elhigu** [comment]
I passed builder.knex() to  couple of places in code and then example code did seem to execute correctly:

https://github.com/Vincit/objection.js/blob/e944679cbce440764c59f4e3bc9b176921fdc3af/lib/queryBuilder/graphInserter/inserter.js#L19

=> 
```js
let insertQuery = tableInsertion.modelClass.query(builder.knex()).childQueryOf(builder);
```

and 

https://github.com/Vincit/objection.js/blob/e944679cbce440764c59f4e3bc9b176921fdc3af/lib/queryBuilder/operations/InsertGraphAndFetchOperation.js#L34

=> 

```js

    return modelClass
      .query(builder.knex())
      .childQueryOf(builder)
      .whereIn(builder.fullIdColumnFor(modelClass), ids)
      .eager(eager)
      .then(models => {
        return this.isArray ? models : models[0] || null;
      });
```

Ofc I have no idea if that introduces other problems... I think I'll check next code in `.childQueryOf`if I'm able to create some workaround. 

Any ideas how to go around this problem?

**Comment by elhigu** [comment]
I was able to implement this using `onBuild` instead of directly passing stuff to query.

**Comment by koskimas** [comment]
The connection should get passed along with childQueryOf. I'll reopen this as it seems like a bug

**Comment by koskimas** [comment]
This seems to be a corner case bug when using models without globally binding them to knex and overriding `query()`. The database connection is passed just after calling `query()` using `childQueryOf`. `onBuild` hook is a good solution.
