### ISSUE TITLE
JoinEagerAlgorithm is not working

### ISSUE THREAD

**Issue by seeden** [Vincit/objection.js#684]
When I use next code
```js
const items = await QuizCoverPhoto
      .query()
      .whereIn('quizCoverPhoto.id', quizIds)
      .eagerAlgorithm(QuizCoverPhoto.JoinEagerAlgorithm)
      .eager('photo');
```

It will produce next SQL query (it is correct)
```sql
select "photo"."id" as "photo:id", "photo"."created_at" as "photo:created_at", "photo"."updated_at" as "photo:updated_at", "photo"."name" as "photo:name", "photo"."position" as "photo:position", "photo"."size" as "photo:size", "photo"."type" as "photo:type", "photo"."ext" as "photo:ext", "photo"."description" as "photo:description", "photo"."storage" as "photo:storage", "photo"."metadata" as "photo:metadata", "photo"."reactions" as "photo:reactions", "photo"."banned" as "photo:banned", "photo"."album_id" as "photo:album_id", "photo"."user_id" as "photo:user_id" from "quiz_cover_photo" left join "photos" as "photo" on "photo"."id" = "quiz_cover_photo"."photo_id" where "quiz_cover_photo"."id" in ($1, $2, $3)
```

But after query I can see next error
```js
TypeError: Cannot read property 'photo' of undefined
    at OneToOnePathInfo.getModelFromBranch (/Users/seeden/Documents/git/node_modules/objection/lib/queryBuilder/operations/eager/RelationJoinBuilder.js:712:18)
    at RelationJoinBuilder.rowsToTree (/Users/seeden/Documents/git/node_modules/objection/lib/queryBuilder/operations/eager/RelationJoinBuilder.js:142:23)
    at JoinEagerOperation.onRawResult (/Users/seeden/Documents/git/node_modules/objection/lib/queryBuilder/operations/eager/JoinEagerOperation.js:42:29)
    at promise.then.result (/Users/seeden/Documents/git/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1099:45)
    at tryCatcher (/Users/seeden/Documents/git/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/seeden/Documents/git/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/seeden/Documents/git/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/seeden/Documents/git/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/seeden/Documents/git/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/seeden/Documents/git/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/seeden/Documents/git/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/seeden/Documents/git/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)
```

**Comment by seeden** [comment]
After little bit of debugging I can see that encParentPath is empty

```js
OneToOnePathInfo {
  path: 'photo',
  encPath: 'photo',
  encParentPath: '',
  modelClass: { [Function: Model] dataLoader: null },
  relation:
   BelongsToOneRelation {
     name: 'photo',
     ownerModelClass: { [Function: Model] dataLoader: null },
     relatedModelClass: { [Function: Model] dataLoader: null },
     ownerProp:
      RelationProperty {
        _refs: [Array],
        _modelClass: [Function],
        _props: [Array],
        _cols: [Array],
        _propGetters: [Array],
        _propSetters: [Array] },
     relatedProp:
      RelationProperty {
        _refs: [Array],
        _modelClass: [Function],
        _props: [Array],
        _cols: [Array],
        _propGetters: [Array],
        _propSetters: [Array] },
     joinTableModelClass: null,
     joinTableOwnerProp: null,
     joinTableRelatedProp: null,
     joinTableBeforeInsert: null,
     joinTableExtras: [],
     modify: [Function: modify],
     beforeInsert: [Function: beforeInsert] },
  omitCols: {},
  children: {},
  idGetter: [Function],
  relationAlias: 'photo',
  parentPath: '' }
```

**Comment by koskimas** [comment]
It does work. There are hundreds of tests that make sure of it. Could you provide a reproduction? You can use the reproduction-template.js in the repo root.

**Comment by seeden** [comment]
First of all I will try to fix it by myself. Maybe I missed something.

**Comment by koskimas** [comment]
That's one of the reasons I always ask for a reproduction: trying to reproduce the problem from the scratch is a great way to find the error if there is one. If the problem ends up being an objection bug, the reproduction makes my life a lot easier.

**Comment by koskimas** [comment]
@seeden What are you using to do the `snake_case` --> `camelCase` conversion?

**Comment by seeden** [comment]
I have used your knexSnakeCaseMappers for knex.

**Comment by seeden** [comment]
I am trying to create minimal example right now.
I found that you are trying to get information about schema but with bad camelCase

```js
  knex:query select * from information_schema.columns where table_name = $1 and table_catalog = $2 and table_schema = current_schema +14ms
  knex:bindings [ 'quizCoverPhotoTest', 'quizana' ]
```

as you can see table name is quizCoverPhotoTest but in the table is quizCoverPhotoTest

**Comment by seeden** [comment]
Here is my reproduction

```js
import Knex from 'knex';
import { Model, knexSnakeCaseMappers } from 'objection';

class Photo extends Model {
  static modelName = 'Photo';
  static tableName = 'photosTest';
  static jsonAttributes = ['metadata'];

  static relationMappings() {
    return {
      quizCoverPhoto: {
        relation: this.HasOneRelation,
        modelClass: QuizCoverPhoto,
        join: {
          from: `${this.tableName}.id`,
          to: `${QuizCoverPhoto.tableName}.photoId`,
        },
      },
    };
  }
}

class QuizCoverPhoto extends Model {
  static modelName = 'QuizCoverPhoto';
  static tableName = 'quizCoverPhotoTest';

  static relationMappings() {
    return {
      photo: {
        relation: this.BelongsToOneRelation,
        modelClass: Photo,
        join: {
          from: `${this.tableName}.photoId`,
          to: `${Photo.tableName}.id`,
        },
      },
    };
  }

  static async getPhotos(ids) {
    const items = await this
      .query()
      .whereIn(`${QuizCoverPhoto.tableName}.id`, ids)
      .eagerAlgorithm(this.JoinEagerAlgorithm)
      .eager('photo');

    const byIds = {};
    items.forEach(item => byIds[item.id] = item);

    return items.map(id => byIds[id] && byIds[id].photo);
  }
}

const knex = Knex({
  ...knexSnakeCaseMappers(),
  client: 'postgresql',
  connection: process.env.POSTGRESQL_URL,
  // debug: true,
  pool: {
    min: 5,
    max: 15,
    idleTimeoutMillis: 30000,
  },
  migrations: {
    tableName: 'knex_migrations',
  },
});

const models = {
  Photo,
  QuizCoverPhoto,
};

// we need to register all models
Object.keys(models).forEach((m) => {
  // extend current model
  const model = models[m];
  model.knex(knex);
});

async function test() {
  await knex.schema.dropTableIfExists(QuizCoverPhoto.tableName);
  await knex.schema.dropTableIfExists(Photo.tableName);

  // init db
  await knex.schema.createTableIfNotExists(Photo.tableName, (table) => {
    table.increments('id').primary().unsigned();
    table.timestamps(true, true);
    table.string('name');
  });

  await knex.schema.createTableIfNotExists(QuizCoverPhoto.tableName, (table) => {
    table.increments('id').primary().unsigned();
    table.timestamps(true, true);

    table
      .integer('photoId')
      .unsigned()
      .notNullable()
      .index()
      .references('id')
      .inTable('photosTest')
      .onDelete('CASCADE');
  });

  // add db items
  const photo = await models.Photo
    .query()
    .insert({
      name: 'test',
    })
    .returning('*');

  const quizCoverPhoto = await models.QuizCoverPhoto
    .query()
    .insert({
      photoId: photo.id,
    })
    .returning('*');

  // run code
  const result = await models.QuizCoverPhoto.getPhotos([quizCoverPhoto.id]);
  console.log(result);
}

test();

```

**Comment by seeden** [comment]
It looks like knex.columnInfo is not using wrapIdentifier or postProcessResponse. :(

**Comment by seeden** [comment]
I have tried to add snakeCase into the knex and it is working fine now. But it is just local solution

**Comment by koskimas** [comment]
@seeden Did you open an issue in knex github? This should be fixed there.

**Comment by koskimas** [comment]
Actually this is pretty much impossible to fix in objection without copying the knex code to objection for all dialects.

**Comment by koskimas** [comment]
@seeden https://github.com/tgriesser/knex/pull/2405

**Comment by seeden** [comment]
thanks @koskimas you rock 👍

**Comment by seeden** [comment]
I am closing this and waiting for merge in knex
