### ISSUE TITLE
raw not working in a subquery

### ISSUE THREAD

**Issue by koskimas** [Vincit/objection.js#710]
Query:

```js
    published: query => query
      .from(subQuery => subQuery 
        .max('id as publishedId')
        .from('FontFamily')
        .where('published', true)
        .groupBy('name')
        .as('published')
      )
      .where(raw('1 = 1'))
      .join('FontFamily', 'id', 'publishedId'),
```

Error:

```js
{ error: column "_sql" does not exist }
```

**Comment by koskimas** [comment]
@lehni In the original stack trace, there's this

```
/Users/lehni/Development/Lineto/knex/node_modules/pg/lib/connection.js:567:11)
```

why isn't that `knex` inside `node_modules`? Are you using some kind of local fork of knex?

**Comment by lehni** [comment]
@koskimas yes I've linked up all projects locally that I tend to work on and fix bugs for, using `yarn link`. So my local version of `objection` has `knex` linked in, and my project has both `objection` and `knex` linked locally. That way, I can work on all these three projects and don't need to keep installing from NPM. I use `nodemon` to restart the app whenever any of these change, making for a fast and direct workflow.

**Comment by lehni** [comment]
BTW, this setup also avoids the issue that you refer to in #713 with multiple versions fo knex. If I don't create all this links then I do indeed end up with two versions of knex, and all kind of things start to happen : )

**Comment by koskimas** [comment]
The error in this issue smells like one of those "multiple knexes" cases again. Are you sure that's not what's happening here?

**Comment by lehni** [comment]
I can easily verify this by clearing and reinstalling `node-modules` and running this again. One sec.

**Comment by lehni** [comment]
I just tested this again, with a fresh install of `node-modules`, and the same error occurs:

```js
import { raw } from 'objection'
[...]
      .where(raw('true'))
```

```js
{ error: column "_sql" does not exist
    at Connection.parseE ([...]/node_modules/pg/lib/connection.js:545:11)
    at Connection.parseMessage ([...]/node_modules/pg/lib/connection.js:370:19)
    at Socket.<anonymous> ([...]/node_modules/pg/lib/connection.js:113:22)
    at Socket.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onread (net.js:608:20)
  name: 'error',
  length: 105,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '191',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3293',
  routine: 'errorMissingColumn' }
```

**Comment by lehni** [comment]
And with `raw()` from `knex`, I get this error:

```js
import { raw } from 'knex'

// [...]

      .where(raw('true'))
```

```js
Error: undefined passed as a property in argument #0 for 'where' operation. Call skipUndefined() method to ignore the undefined values.
    at convertPlainObject (/Users/lehni/Development/Lineto/lineto-backend/node_modules/objection/lib/queryBuilder/operations/ObjectionToKnexConvertingOperation.js:174:15)
    at convertArgs (/Users/lehni/Development/Lineto/lineto-backend/node_modules/objection/lib/queryBuilder/operations/ObjectionToKnexConvertingOperation.js:67:16)
    at KnexOperation.onBuild (/Users/lehni/Development/Lineto/lineto-backend/node_modules/objection/lib/queryBuilder/operations/ObjectionToKnexConvertingOperation.js:25:17)
    at QueryBuilder.buildInto (/Users/lehni/Development/Lineto/lineto-backend/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:206:10)
    at buildInto (/Users/lehni/Development/Lineto/lineto-backend/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1169:25)
    at doExecute (/Users/lehni/Development/Lineto/lineto-backend/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1084:23)
    at Promise.try.then (/Users/lehni/Development/Lineto/lineto-backend/node_modules/objection/lib/queryBuilder/QueryBuilder.js:521:19)
    at tryCatcher (/Users/lehni/Development/Lineto/lineto-backend/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/lehni/Development/Lineto/lineto-backend/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/lehni/Development/Lineto/lineto-backend/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/Users/lehni/Development/Lineto/lineto-backend/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/Users/lehni/Development/Lineto/lineto-backend/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Users/lehni/Development/Lineto/lineto-backend/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/lehni/Development/Lineto/lineto-backend/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)```

**Comment by koskimas** [comment]
I think you need to have `knex` as a context for the knex raw like this: `knex.raw('1 = 1')`

**Comment by lehni** [comment]
Then I'm getting this, plus the same error as above:

```
Knex:warning - global Knex.raw is deprecated, use knex.raw (chain off an initialized knex object)
```

**Comment by koskimas** [comment]
Well what happens if you do what it tells you?

**Comment by lehni** [comment]
: ) one sec

**Comment by lehni** [comment]
The warning disappears, but the error remains:
```
Error: undefined passed as a property in argument #0 for 'where' operation. Call skipUndefined() method to ignore the undefined values.
```

**Comment by koskimas** [comment]
Superweird.. Could you check what `knex.raw('1 = 1')` actually returns in that case? Is it really returning undefined?

**Comment by lehni** [comment]
It's this:

```js
Raw {
  client:
   Client_PG {
     config:
      { client: 'postgresql',
        connection: [Object],
        pool: [Object],
        wrapIdentifier: [Function: wrapIdentifier],
        postProcessResponse: [Function: postProcessResponse] },
     connectionSettings:
      { host: 'localhost',
        port: 5432,
        user: 'lehni',
        password: '0h4l43tz',
        database: 'lineto-backend' },
     driver:
      PG {
        defaults: [Object],
        Client: [Function],
        Query: [Function],
        Pool: [Function],
        _pools: [],
        Connection: [Function],
        types: [Object],
        native: [Getter] },
     __cid: 'client0',
     pool:
      Pool {
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        _config: [PoolOptions],
        _Promise: [Function],
        _factory: [Object],
        _draining: false,
        _started: true,
        _waitingClientsQueue: [PriorityQueue],
        _factoryCreateOperations: Set {},
        _factoryDestroyOperations: Set {},
        _availableObjects: [Deque],
        _testOnBorrowResources: Set {},
        _testOnReturnResources: Set {},
        _validationOperations: Set {},
        _allObjects: [Set],
        _resourceLoans: Map {},
        _evictionIterator: [DequeIterator],
        _evictor: DefaultEvictor {},
        _scheduledEviction: null },
     valueForUndefined:
      Raw {
        client: [Circular],
        sql: 'DEFAULT',
        bindings: undefined,
        _wrappedBefore: undefined,
        _wrappedAfter: undefined,
        _debug: undefined },
     _events:
      { start: [Function],
        query: [Function],
        'query-error': [Function],
        'query-response': [Function] },
     _eventsCount: 4,
     makeKnex: [Function: makeKnex],
     version: '10.1' },
  sql: '1 = 1',
  bindings: undefined,
  _wrappedBefore: undefined,
  _wrappedAfter: undefined,
  _debug: undefined }
```

**Comment by lehni** [comment]
So `convertPlainObject()` ends up being called on this! Why? It chokes on the `undefined` values then.

**Comment by lehni** [comment]
It looks like `convertArgs()` isn't actually equipped to receive Knex raw objects? The only thing it checks for is `hasToKnexRawMethod()` not if it already is a raw object.

**Comment by lehni** [comment]
But why is `isPlainObject()` returning `true` for this Knex raw object?

**Comment by lehni** [comment]
Oh damn, I'm sorry! This is caused by code on my side.

**Comment by lehni** [comment]
I have overridden `where` & co. to do some extra magic:

```js
// Add conversion of identifiers to all `where` statements, by detecting use of
// model properties and expanding them to `${modelClass.name}.${propertyName}`,
// for unambiguous identification of used properties in complex statements.
for (const key of [
  'where', 'whereNot', 'whereIn', 'whereNotIn', 'whereNull', 'whereNotNull',
  'whereBetween', 'whereNotBetween'
]) {
  const method = QueryBuilder.prototype[key]
  QueryBuilder.prototype[key] = function (arg, ...args) {
    const modelClass = this.modelClass()
    const { properties } = modelClass.definition

    const convertIdentifier = identifier => identifier in properties
      ? `${modelClass.name}.${identifier}`
      : identifier

    if (isString(arg)) {
      arg = convertIdentifier(arg)
    } else if (isPlainObject(arg)) {
      const converted = {}
      for (const key in arg) {
        converted[convertIdentifier(key)] = arg[key]
      }
      arg = converted
    }
    return method.call(this, arg, ...args)
  }
}
```

Problem was, I was using `isObject()` and not `isPlainObject()` there...

**Comment by koskimas** [comment]
No problemo ☺️
