### ISSUE TITLE
Paging with joinEager fails on first fetch

### ISSUE THREAD

**Issue by canadianveggie** [Vincit/objection.js#747]
I found a bug with paging and eager joins. The first query to do a paged load of a joined relationship will fail if the RelationJoinBuilder.columnInfo isn't yet populated. ColumnInfo gets populated by the main query in JoinEagerOperation.onBefore2, but the count(*) operation runs in parallel and gets an error when it tries to access the columnInfo.

Ex:
```
class Foo extends Model {

  static get relationMappings() {
    const Bar = require('./Bar');
    return {
      bar: {
        relation: Model.HasOneRelation,
        modelClass: Bar,
        join: {
          from: 'Foo.id',
          to: 'Bar.fooId'
} } } } }

Foo.query().joinEager('[bar]').page(0, 5);
```

The first time this runs, you will get the following error. After that, the RelationJoinBuilder.columnInfo cache will be populated and queries will succeed.

TypeError: Cannot read property 'length' of undefined
    at RelationJoinBuilder.buildSelects (node_modules/objection/lib/queryBuilder/operations/eager/RelationJoinBuilder.js:357:33)
    at RelationJoinBuilder.doBuild (node_modules/objection/lib/queryBuilder/operations/eager/RelationJoinBuilder.js:256:12)
    at RelationJoinBuilder.build (node_modules/objection/lib/queryBuilder/operations/eager/RelationJoinBuilder.js:113:10)
    at JoinEagerOperation.onBuild (node_modules/objection/lib/queryBuilder/operations/eager/JoinEagerOperation.js:50:22)
    at QueryBuilder.buildInto (node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:190:10)
    at buildInto (node_modules/objection/lib/queryBuilder/QueryBuilder.js:1199:25)
    at QueryBuilder.build (node_modules/objection/lib/queryBuilder/QueryBuilder.js:524:19)
    at Builder.knex.count.from.knexBuilder (node_modules/objection/lib/queryBuilder/QueryBuilder.js:496:15)
    at Formatter.compileCallback (node_modules/knex/lib/formatter.js:181:14)
    at Formatter.wrap (node_modules/knex/lib/formatter.js:135:38)
    at QueryCompiler_PG.get (node_modules/knex/lib/query/compiler.js:669:52)
    at QueryCompiler_PG.columns (node_modules/knex/lib/query/compiler.js:242:79)
    at node_modules/knex/lib/query/compiler.js:157:31
    at Array.map (<anonymous>)
    at QueryCompiler_PG.select (node_modules/knex/lib/query/compiler.js:156:33)
    at QueryCompiler_PG.toSQL (node_modules/knex/lib/query/compiler.js:110:27) } }

**Comment by koskimas** [comment]
Seems to be a bug. I'll fix this asap.

Are you sure you want to page a `joinEager` query though? You will not get the correct results if you join even a single `HasManyRelation` or a `ManyToManyRelation`. You will __only__ get correct results if you page a `joinEager` query that only has `BelongsToOneRelations` and `HasOneRelations` in the eager expression. This is all explained in the docs.

**Comment by canadianveggie** [comment]
Good point, but I think it works in our case. We have a HasOneRelation and we're fetching from table A based on a property in table B.

**Comment by canadianveggie** [comment]
Thanks for the quick fix. I can confirm it fixes the bug for me.

**Comment by koskimas** [comment]
Awesome. I'll release a new 1.0 RC in a couple of minutes. It will include this fix. If you're not yet using the RC, note that the documentation site is still for 0.9.4. You can find the same documentation in `docs` folder of the repo. [Here's the changelog](https://github.com/Vincit/objection.js/blob/master/doc/includes/CHANGELOG.md)

**Comment by drew-r** [comment]
@koskimas  heads up - I have the same issue here in 1.0.0 caused by `.resultSize()`
