### ISSUE TITLE
jsonSchema errors get eaten

### ISSUE THREAD

**Issue by jmeyers91** [Vincit/objection.js#785]
The error handler in `createRelationProperty` in `lib/relations/Relation.js` (see below) eats `jsonSchema` errors and throws a confusing unhelpful error.

```
if (err instanceof RelationProperty.ModelNotFoundError) {
  throw ctx.createError(
    `join: either \`from\` or \`to\` must point to the owner model table and the other one to the related table. It might be that specified table '${
      err.tableName
    }' is not correct`
  );
} else {
  throw ctx.createError(
    `${propName} must have format TableName.columnName. For example "SomeTable.id" or in case of composite key ["SomeTable.a", "SomeTable.b"].`
  );
}
```

The `else` block above causes any errors other than `ModelNotFoundError` thrown during the creation of `new RelationProperty` to be replaced by an error message like this:

`Lesson.relationMappings.sentences: join.to must have format TableName.columnName. For example "SomeTable.id" or in case of composite key ["SomeTable.a", "SomeTable.b"].`

This is confusing when the actual error (the value of `err`) is this (caused by trying to use an undefined variable `schema` in a `jsonSchema` getter):

```
ReferenceError: schema is not defined
    at Function.get jsonSchema [as jsonSchema] (/Users/james/projects/stem_familia/Server/lib/models/Sentence.js:15:15)
    at Function.getJsonSchema (/Users/james/projects/stem_familia/Server/nrbp/node_modules/objection/lib/model/Model.js:380:62)
    at getJsonAttributes (/Users/james/projects/stem_familia/Server/nrbp/node_modules/objection/lib/model/modelJsonAttributes.js:57:18)
    at Function.getJsonAttributes (/Users/james/projects/stem_familia/Server/nrbp/node_modules/objection/lib/model/Model.js:390:61)
    at parseJsonAttributes (/Users/james/projects/stem_familia/Server/nrbp/node_modules/objection/lib/model/modelJsonAttributes.js:7:31)
    at Sentence.$parseDatabaseJson (/Users/james/projects/stem_familia/Server/nrbp/node_modules/objection/lib/model/Model.js:161:12)
    at Sentence.$parseDatabaseJson (/Users/james/projects/stem_familia/Server/nrbp/lib/Model.js:49:21)
    at columnNameToPropertyName (/Users/james/projects/stem_familia/Server/nrbp/node_modules/objection/lib/model/modelColPropMap.js:7:40)
    at Function.columnNameToPropertyName (/Users/james/projects/stem_familia/Server/nrbp/node_modules/objection/lib/model/Model.js:414:38)
    at refs.map.ref (/Users/james/projects/stem_familia/Server/nrbp/node_modules/objection/lib/relations/RelationProperty.js:190:29)
    at Array.map (<anonymous>)
    at createPaths (/Users/james/projects/stem_familia/Server/nrbp/node_modules/objection/lib/relations/RelationProperty.js:179:15)
    at new RelationProperty (/Users/james/projects/stem_familia/Server/nrbp/node_modules/objection/lib/relations/RelationProperty.js:36:19)
    at createRelationProperty (/Users/james/projects/stem_familia/Server/nrbp/node_modules/objection/lib/relations/Relation.js:308:12)
    at createJoinProperties (/Users/james/projects/stem_familia/Server/nrbp/node_modules/objection/lib/relations/Relation.js:284:18)
    at HasManyRelation.setMapping (/Users/james/projects/stem_familia/Server/nrbp/node_modules/objection/lib/relations/Relation.js:53:11)
```

**Comment by koskimas** [comment]
Thanks!
