### ISSUE TITLE
Cannot use 'in' operator to search for 'key' in undefined

### ISSUE THREAD

**Issue by igor-savin-ht** [Vincit/objection.js#869]
EDIT BY @koskimas: This has been fixed in 1.1.3

Seems to be a regression in 1.1.2.

When calling JSON.stringify(entities); (which, e. g., happens when you are trying to send an array of Objection entities as a response from Express), an error is thrown.
Error seems to only manifest itself when entity in question has custom idColumn defined (in this particular case it was defined as
```
	static get idColumn() {
		return 'key';
	}
```
)

Error stacktrace:

TypeError: Cannot use 'in' operator to search for 'key' in undefined
    at assignJsonValue (C:\sources\lms-api\models\node_modules\objection\lib\model\modelToJson.js:79:33)
    at toExternalJsonImpl (C:\sources\lms-api\models\node_modules\objection\lib\model\modelToJson.js:51:5)
    at toJson (C:\sources\lms-api\models\node_modules\objection\lib\model\modelToJson.js:20:14)
    at Brand.$toJson (C:\sources\lms-api\models\node_modules\objection\lib\model\Model.js:204:12)
    at Brand.toJSON (C:\sources\lms-api\models\node_modules\objection\lib\model\Model.js:208:17)
    at JSON.stringify (<anonymous>)
    at eval (eval at stringify (C:\sources\lms-api\api\node_modules\express\lib\response.js:1117:14), <anonymous>:1:6)
    at stringify (C:\sources\lms-api\api\node_modules\express\lib\response.js:1117:14)
    at ServerResponse.json (C:\sources\lms-api\api\node_modules\express\lib\response.js:260:14)
    at ServerResponse.send (C:\sources\lms-api\api\node_modules\express\lib\response.js:158:21)
    at router.get (C:\sources\lms-api\api\controllers\brands.controller.js:44:7)
    at <anonymous>

Surprisingly, this works fine when single entity is being stringified.

**Comment by koskimas** [comment]
I'll need a repro for this. I was not able to reproduce this.

**Comment by igor-savin-ht** [comment]
@koskimas Will create a failing test ASAP

**Comment by koskimas** [comment]
Silly me, this throws:

```js
const { Model } = require('./');

class Person extends Model {
  static get idColumn() {
    return 'key';
  }
}

const p1 = Person.fromJson({ key: 1 });
const p2 = Person.fromJson({ key: 2 });

JSON.stringify([p1, p2]);
```

@igor-savin-ht No need for repro anymore.

**Comment by koskimas** [comment]
Fixed. A new version will be out in a couple of minutes. Sorry about this 😬

**Comment by kibertoad** [comment]
ah, sorry, missed your update. Thank you for the quick fix!

**Comment by kibertoad** [comment]
@koskimas Shouldn't this be closed :)? Published fix worked, btw.

**Comment by koskimas** [comment]
@kibertoad Other people may have hit the same bug and they'll come looking for an answer. Let's keep this open for a couple of days.

**Comment by kibertoad** [comment]
Makes sense.
