### ISSUE TITLE
Validation fails with $relatedQuery

### ISSUE THREAD

**Issue by larryosborn** [Vincit/objection.js#886]
I'm not sure if this is expected behavior or not, but I am assuming the validation should pass in my sample problem. 

I have to models called City and State. State can have many Cities. and its related by city.state_id to state_id.

The jsonSchema requires state_id on the City model. While I don't specifically supply the state_id when inserting with $relatedQuery.insert() it is provided by Objection. However this fails validation when it is required in the jsonSchema. 

It seems unnecessary to require the state_id explicitly when it is automatically added. Can the validation happen after the foreign key is added to the object being inserted?

```javascript
const Model = require('objection').Model
const Knex = require('knex')
const knex = Knex({ client: 'pg', connection: 'postgres://localhost/objection_test' })
Model.knex(knex)

class City extends Model {

    static get tableName() {
        return 'city'
    }

    static get relationMappings() {
        return {
            state: {
                relation: Model.BelongsToOneRelation,
                modelClass: State,
                join: {
                    from: 'city.state_id',
                    to: 'state.id'
                },
            },
        }
    }

    static get jsonSchema() {
        return {
            type: 'object',
            required: ['name', 'state_id'],
            properties: {
                id: { type: 'integer' },
                name: { type: 'string' },
                state_id: { type: 'integer' },
            }
        }
    }

}

class State extends Model {

    static get tableName() {
        return 'state'
    }

    static get relationMappings() {
        return {
            cities: {
                relation: Model.HasManyRelation,
                modelClass: City,
                join: {
                    from: 'state.id',
                    to: 'city.state_id'
                },
            },
        }
    }

    static get jsonSchema() {
        return {
            type: 'object',
            required: ['name'],
            properties: {
                id: { type: 'integer' },
                name: { type: 'string' },
            }
        }
    }

}

const testGood = async function() {

    try {
        const city = await City.query().insert({ name: 'Los Angeles', state_id: 1 })
        console.log(city)
        // City { name: 'Los Angeles', state_id: 1, id: 3 }
    }
    catch (error) {
        console.error(error)
    }

}


const testBad = async function() {

    try {
        const state = await State.query().first()
        console.log(state)
        // State { id: 1, name: 'California' }

        const city = await state.$relatedQuery('cities').insert({ name: 'San Jose' })
        console.log(city)
    }
    catch (error) {
        console.error(error)
        /*
        { Error: state_id: is a required property
            at Function.createValidationError (/test/node_modules/objection/lib/model/Model.js:344:12)
            at parseValidationError (/test/node_modules/objection/lib/model/AjvValidator.js:178:21)
            at AjvValidator.validate (/test/node_modules/objection/lib/model/AjvValidator.js:75:13)
            at validate (/test/node_modules/objection/lib/model/modelValidate.js:30:20)
            at City.$validate (/test/node_modules/objection/lib/model/Model.js:146:12)
            at setJson (/test/node_modules/objection/lib/model/modelSet.js:27:16)
            at City.$setJson (/test/node_modules/objection/lib/model/Model.js:184:12)
            at Function.fromJson (/test/node_modules/objection/lib/model/Model.js:311:11)
            at Function.ensureModel (/test/node_modules/objection/lib/model/Model.js:630:25)
            at Function.ensureModelArray (/test/node_modules/objection/lib/model/Model.js:648:20)
            at HasManyInsertOperation.onAdd (/test/node_modules/objection/lib/queryBuilder/operations/InsertOperation.js:21:30)
            at HasManyInsertOperation.onAdd (/test/node_modules/objection/lib/relations/hasMany/HasManyInsertOperation.js:6:26)
            at QueryBuilder.addOperation (/test/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:180:33)
            at writeOperation (/test/node_modules/objection/lib/queryBuilder/QueryBuilder.js:761:12)
            at writeOperation (/test/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1366:5)
            at QueryBuilder.insert (/test/node_modules/objection/lib/queryBuilder/QueryBuilder.js:758:12)
          type: 'ModelValidation',
          data: { state_id: [ [Object] ] },
          statusCode: 400 }
        */
    }

}

testGood()
testBad()
```

**Comment by koskimas** [comment]
Validation happens before the insert, so this is expected. You shouldn't think of `jsonSchema` as the database schema, but as the "input schema". You don't need to give `state_id` when you insert a city using `$relatedQuery` --> don't add `state_id` as required. Instead you should make the `state_id` `notNullable` in the database.
