### ISSUE TITLE
mapping.relation is not a constructor

### ISSUE THREAD

**Issue by slim-hmidi** [Vincit/objection.js#890]
I create the model PricePerOccupation.js:
```
const { Model } = require('objection');
const OccupationType = require('./occupationType');
const ProductPricePeriod = require('./productPricePeriod');


class PricePerOccupation extends Model {
  static get tableName() {
    return 'price_per_occupation';
  }

  static get jsonSchema() {
    return {
      type: 'object',
      properties: {
        id: { type: 'integer' },
        product_price_period_id: { type: 'integer' },
        occupation_type_id: { type: 'integer' },
        price: { type: 'number' },
      },
    };
  }

  static get relationMappings() {
    return {
      occupationType: {
        relation: Model.BelongsToOneRelation,
        modelClass: OccupationType,
        join: {
          from: 'price_per_occupation.occupation_type_id',
          to: 'occupation_type.id',
        },
      },
      productPricePeriod: {
        realtion: Model.HasManyRelation,
        modelClass: ProductPricePeriod,
        join: {
          from: 'product_price_period.id',
          to: 'price_per_occupation.product_price_period_id',
        },
      },

    };
  }
}

module.exports = PricePerOccupation;
```
Then I tried to use the `GraphInsert` function to insert some data:
```
await PricePerOccupation
    .query()
    .insertGraph({
      productPricePeriod: [
        {
         '#id': 'productPricePeriod',
          product_id: req.body.product_id,
          price_mode_id: req.body.price_mode_id,
          price_period: req.body.price_period,
         },
       ],
       product_price_period_id: '#ref{productPricePeriod.id}',
      occupation_type_id: req.body.occupation_type_id,
      price: req.body.price,
    });
```
I got this error:
```
mapping.relation is not a constructor
at Object.keys.reduce (/home/user1/git/Taiga/backend/node_modules/objection/lib/model/Model.js:489:35)    
at Array.reduce (<anonymous>)\n    at Function.getRelations (/home/user1/git/Taiga/backend/node_modules/objection/lib/model/Model.js:486:61)
at getRelationArray (/home/user1/git/Taiga/backend/node_modules/objection/lib/model/Model.js:722:32)
at Function.getRelationArray (/home/user1/git/Taiga/backend/node_modules/objection/lib/model/Model.js:505:60)
at parseRelationsIntoModelInstances (/home/user1/git/Taiga/backend/node_modules/objection/lib/model/modelParseRelations.js:5:32)
at setJson (/home/user1/git/Taiga/backend/node_modules/objection/lib/model/modelSet.js:34:5)
at PricePerOccupation.$setJson (/home/user1/git/Taiga/backend/node_modules/objection/lib/model/Model.js:185:12)
at Function.fromJson (/home/user1/git/Taiga/backend/node_modules/objection/lib/model/Model.js:312:11)
at Function.ensureModel (/home/user1/git/Taiga/backend/node_modules/objection/lib/model/Model.js:574:25)
at Function.ensureModelArray (/home/user1/git/Taiga/backend/node_modules/objection/lib/model/Model.js:592:20)
at InsertOperation.onAdd (/home/user1/git/Taiga/backend/node_modules/objection/lib/queryBuilder/operations/InsertOperation.js:23:30)
at InsertGraphOperation.onAdd (/home/user1/git/Taiga/backend/node_modules/objection/lib/queryBuilder/operations/DelegateOperation.js:20:26)
at InsertGraphOperation.onAdd (/home/user1/git/Taiga/backend/node_modules/objection/lib/queryBuilder/operations/InsertGraphOperation.js:25:26)
at QueryBuilder.addOperation (/home/user1/git/Taiga/backend/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:165:33)
at writeOperation (/home/user1/git/Taiga/backend/node_modules/objection/lib/queryBuilder/QueryBuilder.js:694:12)\nFrom previous event:
at QueryBuilder.execute (/home/user1/git/Taiga/backend/node_modules/objection/lib/queryBuilder/QueryBuilder.js:519:8)
 at QueryBuilder.then (/home/user1/git/Taiga/backend/node_modules/objection/lib/queryBuilder/QueryBuilder.js:425:26)
at process._tickCallback (internal/process/next_tick.js:188:7)
```

Do I make a mistake in the model's creation or I miss something?

**Comment by koskimas** [comment]
You have `realtion` there instead of `relation` in `relationMappings`
