### ISSUE TITLE
Unable to insert many lines into a table with graphInsert

### ISSUE THREAD

**Issue by slim-hmidi** [Vincit/objection.js#893]
I have these models:
ProductPricePeriod.js
```
const { Model } = require('objection');
const ProductPriceSubPeriod = require('./productPriceSubPeriod');

class ProductPricePeriod extends Model {
  static get tableName() {
    return 'product_price_period';
  }

  static get jsonSchema() {
    return {
      type: 'object',
      properties: {
        id: { type: 'integer' },
        price_period: { type: 'string' },
        checked_days: {type: 'array' },
      },
    };
  }

  static get relationMappings() {
    return {
      productPriceSubPeriod: {
        relation: Model.HasManyRelation,
        modelClass: ProductPriceSubPeriod,
        join: {
          from: 'product_price_period.id',
          to: 'product_price_sub_period.product_price_period_id',
        },
      },
    };
  }
}
```
and ProductPriceSubPeriod.js:
```
const { Model } = require('objection');
class ProductPriceSubPeriod extends Model {
  static get tableName() {
    return 'product_price_sub_period';
  }

  static get jsonSchema() {
    return {
      type: 'object',
      properties: {
        id: { type: 'integer' },
        product_price_period_id: { type: 'integer' },
        price_sub_period: { type: 'string' },
      },
    };
  }
}
```
I'm trying to put some data like:
```
{
   price_period: "[1992-08-05, 1992-08-31]",
   checked_days: [0,2,3]
}
```
I wrote this code snippet:
```
const startDate = ((req.body.price_period.replace(/[[ \]]/g, '')).split(','))[0]; 
const endDate = ((req.body.price_period.replace(/[[ \]]/g, '')).split(','))[1];
const periodStart = moment(startDate).format('YYYY-MM-DD');
const periodEnd = moment(endDate).format('YYYY-MM-DD');

const productPricePeriod = await ProductPricePeriod
    .query()
    .insertGraph({
      price_period: req.body.price_period,
      productPriceSubPeriod: decomposePeriod(periodStart, periodEnd, daysChecked),
    });

```
With a given `startDate`, `endDate` and `dyasChecked`, the function `decomposePeriod` divides the given period into sub periods based on some rules and gives a result such as:
```
 [ '[1992-08-05, 1992-08-05]',
  '[1992-08-07, 1992-08-07]',
  '[1992-08-10, 1992-08-12]',
  '[1992-08-14, 1992-08-14]',
  '[1992-08-17, 1992-08-19]',
  '[1992-08-21, 1992-08-21]',
  '[1992-08-24, 1992-08-26]',
  '[1992-08-28, 1992-08-28]',
  '[1992-08-31, 1992-08-31]' ] 
```
I run the program and I got this error:
```
"notModel\": \"not a model\"\n}
at Function.createValidationError (/home/user1/project/node_modules/objection/lib/model/Model.js:345:12)
at DependencyGraph.buildForModel (/home/user1/project/node_modules/objection/lib/queryBuilder/graphInserter/DependencyGraph.js:52:24)
at DependencyGraph.buildForRelations (/home/user1/project/node_modules/objection/lib/queryBuilder/graphInserter/DependencyGraph.js:131:16)
 at DependencyGraph.buildForModel (/home/user1/project/node_modules/objection/lib/queryBuilder/graphInserter/DependencyGraph.js:106:10)
   at DependencyGraph.build (/home/user1/project/node_modules/objection/lib/queryBuilder/graphInserter/DependencyGraph.js:32:14)
   at GraphInserter._buildDependencyGraph (/home/user1/project/node_modules/objection/lib/queryBuilder/graphInserter/GraphInserter.js:29:11)
   at new GraphInserter (/home/user1/project/node_modules/objection/lib/queryBuilder/graphInserter/GraphInserter.js:18:23)
 at InsertGraphOperation.onAfter1 (/home/user1/project/node_modules/objection/lib/queryBuilder/operations/InsertGraphOperation.js:79:27)
    at promise.then.result (/home/user1/project/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1114:43)
From previous event:\n   at builder._operations.forEach.op (/home/user1/project/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1114:25)
    at Array.forEach (<anonymous>)\n at afterExecute (/home/user1/project/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1112:23)
    at Promise.try.then.then.result (/home/user1/project/node_modules/objection/lib/queryBuilder/QueryBuilder.js:520:23)
    at Immediate.<anonymous> (/home/user1/project/node_modules/async-listener/glue.js:188:31)
   at runCallback (timers.js:794:20)
 at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)\nFrom previous event:\n    at QueryBuilder.execute (/home/user1/project/node_modules/objection/lib/queryBuilder/QueryBuilder.js:520:8)
    at QueryBuilder.then (/home/user1/project/node_modules/objection/lib/queryBuilder/QueryBuilder.js:425:26)
  at process._tickCallback (internal/process/next_tick.js:188:7)


Is it possible to insert an array of periods into the productPriceSubPeriod table.Each row will contain a value from the subPeriods array.How can I fix that?

**Comment by koskimas** [comment]
You should ask these kind of things in gitter. While I like to help people, the github issues are mainly meant for bugs, feature requests and other development related things.
