### ISSUE TITLE
Cannot use toSql or subquery with innerJoin, joinEager?

### ISSUE THREAD

**Issue by heisian** [Vincit/objection.js#946]
Unable to use a `query` built with `eagerOptions` with `innerJoin` and `joinEager` ..

```node
const search = 'something'

const query = Model.query()
  .eagerOptions({ joinOperation: 'innerJoin' })
  .joinEager('identity')

console.log(query.toSql()) // outputs 'This query cannot be built synchronously. Consider using debug() method instead.'

await Model.query()
  .count(this.Model.raw(1))
  .from(query.as('results'))
/*
Throws:
        "TypeError: Cannot read property 'columns' of null",
        "    at RelationJoinBuilder.buildSelects (/Users/heisian/Web/ethos/ethos/node_modules/objection/lib/queryBuilder/operations/eager/RelationJoinBuilder.js:319:9)",
        "    at RelationJoinBuilder.doBuild (/Users/heisian/Web/ethos/ethos/node_modules/objection/lib/queryBuilder/operations/eager/RelationJoinBuilder.js:218:12)",
        "    at RelationJoinBuilder.build (/Users/heisian/Web/ethos/ethos/node_modules/objection/lib/queryBuilder/operations/eager/RelationJoinBuilder.js:72:10)",
        "    at JoinEagerOperation.onBuild (/Users/heisian/Web/ethos/ethos/node_modules/objection/lib/queryBuilder/operations/eager/JoinEagerOperation.js:37:22)",
        "    at CustomQueryBuilder.executeOnBuild (/Users/heisian/Web/ethos/ethos/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:259:11)",
        "    at CustomQueryBuilder.buildInto (/Users/heisian/Web/ethos/ethos/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:232:10)",
        "    at buildInto (/Users/heisian/Web/ethos/ethos/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1275:25)",
        "    at CustomQueryBuilder.build (/Users/heisian/Web/ethos/ethos/node_modules/objection/lib/queryBuilder/QueryBuilder.js:578:19)",
        "    at convertQueryBuilderBase (/Users/heisian/Web/ethos/ethos/node_modules/objection/lib/queryBuilder/operations/ObjectionToKnexConvertingOperation.js:93:35)",
        "    at convertArgs (/Users/heisian/Web/ethos/ethos/node_modules/objection/lib/queryBuilder/operations/ObjectionToKnexConvertingOperation.js:59:16)",
        "    at FromOperation.onBuild (/Users/heisian/Web/ethos/ethos/node_modules/objection/lib/queryBuilder/operations/ObjectionToKnexConvertingOperation.js:25:17)",
        "    at CustomQueryBuilder.executeOnBuild (/Users/heisian/Web/ethos/ethos/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:259:11)",
        "    at CustomQueryBuilder.buildInto (/Users/heisian/Web/ethos/ethos/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:232:10)",
        "    at buildInto (/Users/heisian/Web/ethos/ethos/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1275:25)",
        "    at doExecute (/Users/heisian/Web/ethos/ethos/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1177:23)",
        "    at Promise.try.then (/Users/heisian/Web/ethos/ethos/node_modules/objection/lib/queryBuilder/QueryBuilder.js:595:19)",
        "    at runCallback (timers.js:781:20)",
        "    at tryOnImmediate (timers.js:743:5)",
        "    at processImmediate [as _immediateCallback] (timers.js:714:5)",
        "From previous event:",
        "    at CustomQueryBuilder.execute (/Users/heisian/Web/ethos/ethos/node_modules/objection/lib/queryBuilder/QueryBuilder.js:595:8)",
        "    at CustomQueryBuilder.then (/Users/heisian/Web/ethos/ethos/node_modules/objection/lib/queryBuilder/QueryBuilder.js:501:26)"
*/

**Comment by heisian** [comment]
Actually, can't reproduce this when doing the same thing in the node REPL, so may be app logic-related.. closing until further notice..

**Comment by heisian** [comment]
Strange.. seems to be non-deterministic behaviour, as a successive session in the NODE repl produces the error again:
```node
> db.TermPolicy.query().eagerOptions({ joinOperation: 'innerJoin' }).joinEager('identity').toSql()
'This query cannot be built synchronously. Consider using debug() method instead.'
```

**Comment by koskimas** [comment]
joinEager makes no  sens as a subquery. You should use `joinRelation` instead.

**Comment by heisian** [comment]
I'm not sure I agree, because below is the SQL string generated by Objection/Knex placed inside a `SELECT .. FROM(...)` as a subquery:
```sql
SELECT COUNT(1) FROM (
SELECT     "policy"."term_policies"."id"                       AS "id", 
           "policy"."term_policies"."identity_id"              AS "identity_id", 
           "policy"."term_policies"."carrier"                  AS "carrier", 
           "policy"."term_policies"."carrier_status"           AS "carrier_status", 
           "policy"."term_policies"."carrier_case_id"          AS "carrier_case_id", 
           "policy"."term_policies"."carrier_policy_number"    AS "carrier_policy_number", 
           "policy"."term_policies"."carrier_data"             AS "carrier_data", 
           "policy"."term_policies"."docusign_status"          AS "docusign_status", 
           "policy"."term_policies"."docusign_envelope_id"     AS "docusign_envelope_id", 
           "policy"."term_policies"."purpose_of_insurance"     AS "purpose_of_insurance", 
           "policy"."term_policies"."intent_to_sell"           AS "intent_to_sell", 
           "policy"."term_policies"."manual_underwriting"      AS "manual_underwriting", 
           "policy"."term_policies"."manual_state_replacement" AS "manual_state_replacement", 
           "policy"."term_policies"."payment_plan"             AS "payment_plan", 
           "policy"."term_policies"."client_data"              AS "client_data", 
           "policy"."term_policies"."object_id"                AS "object_id", 
           "policy"."term_policies"."created_at"               AS "created_at", 
           "policy"."term_policies"."updated_at"               AS "updated_at", 
           "policy"."term_policies"."case_created_at"          AS "case_created_at", 
           "policy"."term_policies"."submitted_at"             AS "submitted_at", 
           "policy"."term_policies"."carrier_submitted_at"     AS "carrier_submitted_at", 
           "policy"."term_policies"."approved_at"              AS "approved_at", 
           "policy"."term_policies"."issued_at"                AS "issued_at", 
           "policy"."term_policies"."activated_at"             AS "activated_at", 
           "policy"."term_policies"."effective_at"             AS "effective_at", 
           "policy"."term_policies"."expires_at"               AS "expires_at", 
           "policy"."term_policies"."closed_at"                AS "closed_at", 
           "policy"."term_policies"."deleted_at"               AS "deleted_at", 
           "policy"."term_policies"."close_reason"             AS "close_reason", 
           "policy"."term_policies"."intent_to_sell_agreement" AS "intent_to_sell_agreement", 
           "identity"."id"                                     AS "identity:id", 
           "identity"."user_id"                                AS "identity:user_id", 
           "identity"."primary"                                AS "identity:primary", 
           "identity"."name_first"                             AS "identity:name_first", 
           "identity"."name_middle"                            AS "identity:name_middle", 
           "identity"."name_last"                              AS "identity:name_last", 
           "identity"."gender"                                 AS "identity:gender", 
           "identity"."birth_date"                             AS "identity:birth_date", 
           "identity"."birth_country"                          AS "identity:birth_country", 
           "identity"."created_at"                             AS "identity:created_at", 
           "identity"."updated_at"                             AS "identity:updated_at", 
           "identity"."deleted_at"                             AS "identity:deleted_at", 
           "identity"."allow_lead_share"                       AS "identity:allow_lead_share", 
           "identity"."birth_state"                            AS "identity:birth_state", 
           "identity:user"."id"                                AS "identity:user:id", 
           "identity:user"."lead_id"                           AS "identity:user:lead_id", 
           "identity:user"."password"                          AS "identity:user:password", 
           "identity:user"."object_id"                         AS "identity:user:object_id", 
           "identity:user"."lead_object_id"                    AS "identity:user:lead_object_id",
           "identity:user"."referrer_object_id"                AS "identity:user:referrer_object_id",
           "identity:user"."created_at"                        AS "identity:user:created_at", 
           "identity:user"."updated_at"                        AS "identity:user:updated_at", 
           "identity:user"."deleted_at"                        AS "identity:user:deleted_at", 
           "identity:user:emails"."id"                         AS "identity:user:emails:id", 
           "identity:user:emails"."user_id"                    AS "identity:user:emails:user_id",
           "identity:user:emails"."email"                      AS "identity:user:emails:email", 
           "identity:user:emails"."primary"                    AS "identity:user:emails:primary",
           "identity:user:emails"."verified"                   AS "identity:user:emails:verified",
           "identity:user:emails"."created_at"                 AS "identity:user:emails:created_at",
           "identity:user:emails"."updated_at"                 AS "identity:user:emails:updated_at",
           "identity:user:emails"."deleted_at"                 AS "identity:user:emails:deleted_at"
FROM       "policy"."term_policies" 
inner join 
           ( 
                  SELECT "identity"."identities".* 
                  FROM   "identity"."identities" 
                  WHERE  Concat_ws(' ', name_first, name_last) ilike '%tim%'
                  OR     concat_ws(' ', name_first, name_middle, name_last) ilike '%tim%') AS "identity"
ON         "identity"."id" = "policy"."term_policies"."identity_id" 
inner join "auth"."users" AS "identity:user" 
ON         "identity:user"."id" = "identity"."user_id" 
inner join 
           ( 
                  SELECT "auth"."emails".* 
                  FROM   "auth"."emails" 
                  WHERE  "email" ilike '%tim%') AS "identity:user:emails" 
ON         "identity:user:emails".user_id = "identity:user".id
WHERE      "policy"."term_policies"."deleted_at" IS NULL 
ORDER BY   "policy"."term_policies"."updated_at" DESC
) AS results;
```

The subquery was a direct copy from the debug output of my `joinEager` query being run.

**Comment by heisian** [comment]
Additionally, your response doesn't explain why `toSql()` fails, and I'm not sure how to get any visibility beyond the stack-traceless `This query cannot be built synchronously. Consider using debug() method instead.` error.

**Comment by heisian** [comment]
Also, the issue with `joinRelation` is that it places the related data in the top level of the returned object.

**Comment by koskimas** [comment]
`toSql` should only be used for debugging. Interpolating a query in SQL is dangerous because no escaping is done. Your queries will be very prone to injection attacks.

`joinEager` basically runs `leftJoinRelation` and in addition to that, it builds the select clauses so that the data can be parsed into a tree structure. The select clause building requires a metadata query, which cannot be ran synchronously. That's why `toSql` doesn't work. But you should not be using it anyways. I should probably remove the method.

**Comment by koskimas** [comment]
Each SQL join "places the data on the top level of the query". `joinEager` simply parses that data into a tree structure, but since you are using it as a subquery, the result data never reaches your application. No parsing is done ever.

**Comment by heisian** [comment]
Got it - so there's essentially not an easy way to retrieve the record count of this (semi) complex join without writing raw SQL. Which is what I wanted `toSql` for.

I understand the sanitization aspects of the method - but if my only option here to get the `COUNT` of this join is to run raw SQL, it seems that is what I must do, unless you have another suggestion.

**Comment by heisian** [comment]
And for the record, this **does** work:
```node
TermPolicy.query()
  .eagerOptions({ joinOperation: 'innerJoin' })
  .joinEager('identity')
  .context({
    onBuild: (b) => { process.stdout.write(b.toSql()) }
  })
```

Outputs
```
select "policy"."term_policies"."id" as "id", "policy"."term_policies"."identity_id" as "identity_id", "policy"."term_policies"."carrier" as "carrier", "policy"."term_policies"."carrier_status" as "carrier_status", "policy"."term_policies"."carrier_case_id" as "carrier_case_id", "policy"."term_policies"."carrier_policy_number" as "carrier_policy_number", "policy"."term_policies"."carrier_data" as "carrier_data", "policy"."term_policies"."docusign_status" as "docusign_status", "policy"."term_policies"."docusign_envelope_id" as "docusign_envelope_id", "policy"."term_policies"."purpose_of_insurance" as "purpose_of_insurance", "policy"."term_policies"."intent_to_sell" as "intent_to_sell", "policy"."term_policies"."manual_underwriting" as "manual_underwriting", "policy"."term_policies"."manual_state_replacement" as "manual_state_replacement", "policy"."term_policies"."payment_plan" as "payment_plan", "policy"."term_policies"."client_data" as "client_data", "policy"."term_policies"."object_id" as "object_id", "policy"."term_policies"."created_at" as "created_at", "policy"."term_policies"."updated_at" as "updated_at", "policy"."term_policies"."case_created_at" as "case_created_at", "policy"."term_policies"."submitted_at" as "submitted_at", "policy"."term_policies"."carrier_submitted_at" as "carrier_submitted_at", "policy"."term_policies"."approved_at" as "approved_at", "policy"."term_policies"."issued_at" as "issued_at", "policy"."term_policies"."activated_at" as "activated_at", "policy"."term_policies"."effective_at" as "effective_at", "policy"."term_policies"."expires_at" as "expires_at", "policy"."term_policies"."closed_at" as "closed_at", "policy"."term_policies"."deleted_at" as "deleted_at", "policy"."term_policies"."close_reason" as "close_reason", "policy"."term_policies"."intent_to_sell_agreement" as "intent_to_sell_agreement", "identity"."id" as "identity:id", "identity"."user_id" as "identity:user_id", "identity"."primary" as "identity:primary", "identity"."name_first" as "identity:name_first", "identity"."name_middle" as "identity:name_middle", "identity"."name_last" as "identity:name_last", "identity"."gender" as "identity:gender", "identity"."birth_date" as "identity:birth_date", "identity"."birth_country" as "identity:birth_country", "identity"."created_at" as "identity:created_at", "identity"."updated_at" as "identity:updated_at", "identity"."deleted_at" as "identity:deleted_at", "identity"."allow_lead_share" as "identity:allow_lead_share", "identity"."birth_state" as "identity:birth_state" from "policy"."term_policies" inner join "identity"."identities" as "identity" on "identity"."id" = "policy"."term_policies"."identity_id"
```

**Comment by koskimas** [comment]
Also I don't understand why you don't just do this:

```js
const query = Model.query()
  .joinRelation('identity')
  .count()
```

you don't need the subquery. If you think using the subquery will cause the query to count the non-flattened results, you are wrong. The non-flattening is done in the javascript side. There is no way to return anything but flat rows from the database.

**Comment by koskimas** [comment]
You should probably try running those queries using a `pgadmin`, `psql` or some other tool and you'd see what kind of data joins *always* return.

**Comment by heisian** [comment]
Yes, I've already run the queries against my db via the psql console and verified that everything I wrote works. BTW `pgadmin` is terrible, https://pgmodeler.io is much better.

**Comment by heisian** [comment]
@koskimas 
> **it is excatly the same subquery in all possible ways**
Makes sense, I get it now, thank you

**Comment by heisian** [comment]
> you don't need the subquery. If you think using the subquery will cause the query to count the non-flattened results, you are wrong. The non-flattening (turning flat rows into a tree structure) is done in the javascript side. There is no way to return anything but flat rows from the database.

Yup, I was ignoring that fact and only thinking in the ORM context without connecting the dots of what the actual results are - thanks for that.

**Comment by heisian** [comment]
@koskimas And actually using the filters `byIdentity` and `byEmail` to create subqueries with the joins as in the SQL I posted produced incorrect results - so because of your explanation it now works better than before - thanks for your patience and I apologize for my own confusion.
