### ISSUE TITLE
print the error which is thrown when a require of a relation fails

### ISSUE THREAD

**Issue by capaj** [Vincit/objection.js#962]
currently this error is swallowed and instead this is thrown:
https://github.com/Vincit/objection.js/blob/a4158140ecd6728ea05fa2c02751f4c645681dd2/lib/utils/resolveModel.js#L25

The original error is found here:
https://github.com/Vincit/objection.js/blob/a4158140ecd6728ea05fa2c02751f4c645681dd2/lib/utils/resolveModel.js#L48

I had this failing in production and it took some detective work to track down because I test in jest and it worked there because I am using `moduleNameMapper` there, but It failed to ignore style imports for production.
If the error would have been:
```

/home/capaj/git_projects/looop/project-alpha/node_modules/react-select/dist/react-select.css:8
.Select {
^

SyntaxError: Unexpected token .
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/capaj/.nvm/versions/node/v8.11.1/lib/node_modules/ts-node/src/index.ts:414:14)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/capaj/git_projects/looop/project-alpha/node_modules/@capaj/react-select-timezone/build/SelectTimezone.js:28:1)
    at Module._compile (module.js:652:30)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/capaj/.nvm/versions/node/v8.11.1/lib/node_modules/ts-node/src/index.ts:414:14)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)

```

instead of 

```
Error: OrganisationModel.relationMappings.events: modelClass: /var/app/current/back-end/src/models/EventModel is an invalid file path to a model class
```

I'd have much easier time figuring it out.

**Comment by capaj** [comment]
@heisian sorry about confusing you and everyone else. I have a react component which is used in the backend to render an email in an objection.js model. This react component requires a css file. This usecase does not really matter. If I had a syntax error in the model file it would have ended up the same-the syntax error would have been swallowed by objection.js model resolve code. That's what this bug is about. It certainly does not have anything to do with css.

**Comment by heisian** [comment]
Got it - I agree with you @capaj, the error should at least show the original stack trace.
